### ISSUE TITLE
Added crossing node on un/marked crossing way has incomplete tags

### ISSUE THREAD

**Issue by atiannicelli** [facebook/Rapid#1015]
### Description

When I ask rapid to create a crossing node on an unmarked or marked crossing it successfully adds the node, but then it indicates that the node that it created has incomplete tags.

### Version

2.0.3

### What browser are you seeing the problem on? What version are you running?

Chrome v115.0

### The OS you're using

mac

### Steps to reproduce

Create a way with highway=yes
Create a unmarked crossing way that crosses it but doesn't connect.
You will see a validation issue pop up that indicates that the two ways should be connected. Perfect.
I then click on the "connect the features" link.
A node is created with some but not all the necessary tags.

Before creating the node to connect the two ways:
<img width="1214" alt="Screenshot 2023-08-10 at 2 48 33 PM" src="https://github.com/facebook/Rapid/assets/5851115/eabac2ff-0104-44ea-9012-de1c2ccea411">
After having rapid create the node to connect both ways.
<img width="1308" alt="Screenshot 2023-08-10 at 2 48 54 PM" src="https://github.com/facebook/Rapid/assets/5851115/aec0ad65-9d89-4fb8-a1ea-ebd62ed74db9">

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=n-7&map=22.66/33.44470/-88.79238

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

**Comment by bhousel** [comment]
Ugh, yeah this is because they keep changing the crossing presets in the https://github.com/openstreetmap/id-tagging-schema project 😞

**Comment by atiannicelli** [comment]
I noticed one small issue with this fix. When I click on the "connect features" option in the warning dialog box, the box doesn't go away. If I click on the "connect features" again and again it continues to add more, unconnected, crossing nodes.

https://github.com/facebook/Rapid/assets/5851115/a973dc11-fe8c-49be-9670-93bae8a076bc
