### ISSUE TITLE
Please reinstate depiction of some borders for areas (Barriers/Walls/Fences, etc)

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#1020]
### Description

Since 2.0 areas that have tags like barriers (Walls/Fences/etc) are no longer depicted as such, like it happen in ID and used to be Rapid as well.

This is quite helpful

Please note the landuse=education both in ID and Rapid

### Version

2.0.3

### What browser are you seeing the problem on? What version are you running?

Chrome Version 105.0.5195.127 (Official Build) (64-bit)

### Steps to reproduce

Just draw an area and tag landuse=residential and add the tag barrier=wall

The there is no diference in depiction of the border of the area, as it should be.

Thanks

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=17.80/-17.73938/-67.92055

**Comment by jjiglesiasg** [comment]
![Screenshot (48)](https://github.com/facebook/Rapid/assets/22849578/fa7d359a-70e2-4b4b-a4b8-9a6139a495dc)
![Screenshot (47)](https://github.com/facebook/Rapid/assets/22849578/b0b1cb78-ca0c-47ca-b7eb-93d8be4efe81)

**Comment by Bonkles** [comment]
Thank you for the report! Our renderer isn't honoring any of the dash line data that we currently have buried in the code for these sorts of shapes. This does need to be fixed.

**Comment by Bonkles** [comment]
Working on it- here's a quick vid showing the progress. Needs further proving/testing. 

https://github.com/facebook/Rapid/assets/1887955/e0a3400d-5e11-4342-a295-9ba7d72fffa2

**Comment by Bonkles** [comment]
Also tested multipolys with the new draw code- this is a residential area with a 'hole' in it, and the hole also renders with the correct dash styling. 

![image](https://github.com/facebook/Rapid/assets/1887955/48cd5466-1422-4a65-ab6c-d07fc62aafc4)
