### ISSUE TITLE
The 3D Map keyboard shortcut should have the 'Rapid' icon next to it. 

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#1030]
### Description

We have put the rapid icon next to several of the rapid-only options available to mappers: this is brand new and should get similar treatment: 
![image](https://github.com/facebook/Rapid/assets/1887955/5d19d9cb-efcf-4ee7-ab5e-951779e99698)

### Version

2.1.0

### What browser are you seeing the problem on? What version are you running?

Chrome v116.0

### The OS you're using

mac

### Steps to reproduce

just hit '?' to look at the help to see that it is missing the icon

### The browser URL at the time you encountered the bug

http://127.0.0.1:8080/#background=geodata.md.gov-MD_SixInchImagery&datasets=fbRoads,msBuildings&disable_features=aerialways,others&map=18.00/39.57322/-75.97396

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

**Comment by bhousel** [comment]
Added!  👍 

<img width="357" alt="Screenshot 2023-08-23 at 10 37 33 AM" src="https://github.com/facebook/Rapid/assets/38784/2228fb71-102c-4bc3-9512-861422750e91">
