### ISSUE TITLE
Long-pressing space bar on an OSM feature does not bring up the right-click menu

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#1031]
### Description

This *used* to work in rapid v1, looks like 2.0 removed the long-press-space-bar ability. 

video of v1 in action, and long-pressing space bar: 

https://github.com/facebook/Rapid/assets/1887955/348e2ec3-f15c-4948-b2ed-949055c02d5a

### Version

2.1.0

### What browser are you seeing the problem on? What version are you running?

Chrome v116.0

### The OS you're using

mac

### Steps to reproduce

select something with spacebar while hovering over it. 

 then hold spacebar and observe that the context (edit) menu does NOT appear. 

### The browser URL at the time you encountered the bug

http://127.0.0.1:8080/#background=geodata.md.gov-MD_SixInchImagery&datasets=fbRoads,msBuildings&disable_features=aerialways,others&map=18.45/39.57321/-75.97405

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

**Comment by bhousel** [comment]
I don't remember this feature - did someone request it?
It just isn't a thing that most apps have?

**Comment by Bonkles** [comment]
This *used* to be a thing, and it still works in iD. Just found that it is a regression in v2- I am okay with leaving it by the wayside.

**Comment by bhousel** [comment]
Yeah I'd really prefer to drop this one - I'm not sure when this behavior snuck in..  
Holding down the space bar is already used for quickdrawing, so I wouldn't want it to also be used to sometimes bring up a contextmenu.

**Comment by Bonkles** [comment]
I approve this message, the behavior kind of surprised me too!
