### ISSUE TITLE
Places search does not zoom/pan to the item clicked on

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#1033]
### Description

If you search for an item it seems the UI doesn't always respond by zooming/panning you to the appropriate place on click. 

### Version

2.1.0

### What browser are you seeing the problem on? What version are you running?

Chrome v116.0

### The OS you're using

mac

### Steps to reproduce

Open rapid with no pre-existing params or URL stuff. 

Type something into the search bar, I used 'Chelmsford, ma'

I got one response- the administrative border for that town. 

When clicked on, the sidebar shows the item I clicked on, but the map stays at zoom 2/0.0/0.0

![image](https://github.com/facebook/Rapid/assets/1887955/d47dc5ea-e60a-494f-9628-a69e989e030d)

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid/b1ab600-16.x-/index.html#background=EsriWorldImagery&datasets=fbRoads,msBuildings&disable_features=boundaries&id=r1801797&map=2.00/0.0/0.0

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

**Comment by jjiglesiasg** [comment]
I was about to report the same issue. In my case it does not find anything. Contrasted with ID and there is working.

**Comment by Bonkles** [comment]
> I was about to report the same issue. In my case it does not find anything. Contrasted with ID and there is working.

The bug you're reporting is already fixed in 2.1, which is undergoing final testing before we ship. That bug is #1007. The nominatim server that served places to us changed its API, so nothing worked. 

This issue is not quite as bad, as it does actually return results!

**Comment by Bonkles** [comment]
Root cause determined. The code that loads the entity clicked on then determines whether it's in the scene. 

When you're zoomed out to zoom/x/y 2/0/0 (i.e. looking at the entire world), EVERYTHING fits into the scene. :) 

Fix was to add a forceFit flag to `selectEntityID`, which tells the map to always zoom to the thing being clicked on from the search list.
