### ISSUE TITLE
Turn restrictions in a node that connect 2 highways are not shown.

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#1035]
### Description

Every time that two (or more) highways are connected, the connecting node, should show the turn restrictions applicable, or to be selected. 

Currently do not show such diagram. ID does correctly.

### Version

2.0.3

### What browser are you seeing the problem on? What version are you running?

Version 114.0.5735.199 (Official Build) (64-bit)

### Steps to reproduce

Just draw 2 highways (ie trunk) and connect them, and them select the connecting node. Is only shown as a Point no other menu available. In images the comparison between ID and Rapid:

![Screenshot (80)](https://github.com/facebook/Rapid/assets/22849578/e861f3d6-609a-4a08-8914-c05ee56ab235)
![Screenshot (79)](https://github.com/facebook/Rapid/assets/22849578/3ecf9055-dc1a-4fd8-a6d8-41a6aba0a6c1)

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=n11137345976&map=18.00/-17.45047/-67.49917

**Comment by bhousel** [comment]
Yep, this is #503 
The old SVG code to draw the intersection editor is no more and needs to be replaced with new WebGL code. 😢
