### ISSUE TITLE
Neither Cutting nor Embarkment produce any graphical differentiation once applied to a highway

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#1036]
### Description

If you tag a highway (or a segment) with Cutting or Embarkment there is no difference with the depiction of the standard highway Tunnels and Bridges show a different depiction but the first ones no.

### Version

2.0.3

### What browser are you seeing the problem on? What version are you running?

Version 114.0.5735.199 (Official Build) (64-bit)

### Steps to reproduce

Just draw a way or use a existing one and place in a segment the different attributes (Structure) like Tunnel, Bridge, Embarkment and Cutting. And you will see the difference of depiction. Embarkment and Cutting has no difference.

Ford has no difference as well, but that's equal to ID

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=18.48/-17.49807/-67.47451

**Comment by bhousel** [comment]
Thanks for the report!  I just restored the style for cuttings/embankments.
I see this a bunch on railroads..
<img width="686" alt="Screenshot 2023-08-23 at 10 11 12 AM" src="https://github.com/facebook/Rapid/assets/38784/43e70c6a-5640-4e9e-8c2e-e1c79fda37fe">
