### ISSUE TITLE
Buildings request: Vietnam

### ISSUE THREAD

**Issue by AndreyGurevich** [facebook/Rapid#104]
It will be great to have buildings for Vietnam, at least for Ho Shi Mihn city. Thank you!

**Comment by jeffdefacto** [comment]
Thanks for the request. Currently, our only building support is through Microsoft

You can directly reach out to them at MS_Buildings_MwAI@microsoft.com but we'll also track the request here to help monitor interest.

**Comment by cbeddow** [comment]
@AndreyGurevich does it look good now? I see buildings in this area from the data now: https://mapwith.ai/rapid#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries,past_future,others&id=r1973756&map=16.42/10.75417/106.78688
