### ISSUE TITLE
Blue highlight doesn't always clear

### ISSUE THREAD

**Issue by bhousel** [facebook/Rapid#1040]
I noticed that there are some things that cause the blue highlight to appear
- hovering issues
- hovering relation members (#939)
- hovering on search results

And sometimes it goes away when you are done hovering, but sometimes it doesnt.
(Here I searched for the Space Needle - it stays blue after I've moved on to other things).

<img width="356" alt="Screenshot 2023-08-23 at 11 30 39 AM" src="https://github.com/facebook/Rapid/assets/38784/a4f99d79-9fbc-4637-8331-9ed9edc44686">

We can probably just clear this class on mode change?  Or be more diligent about removing the highlight?   Not sure.

**Comment by bhousel** [comment]
I just opened Rapid in New Jersey and searched for "Space Needle", clicked "Search Worldwide", clicked first result (the tower building itself), and it remains blue even after interacting with other features.

**Comment by bhousel** [comment]
This was pretty simple - there was just an extra `else` branch missing the code to clear the highlight.

**Comment by yaomtc** [comment]
I see this once in a while. Here's a screenshot from 2.5.7.

<img width="561" height="283" alt="Image" src="https://github.com/user-attachments/assets/66ada90a-7485-4fae-8642-6e5689260f1d" />
