### ISSUE TITLE
Search bar does not return results

### ISSUE THREAD

**Issue by cbeddow** [facebook/Rapid#1046]
### Description

At zoomed out global view on page load, I search `san diego, ca` and get no results. Clicking search worldwide also yields no results.

Switching to just `san diego` also has no results on type, no results on click. All lower case. Something broken. 

Was at exactly this URL: https://rapideditor.org/edit#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=2.72/34.55/3.95

### Version

2.0.3

### What browser are you seeing the problem on? What version are you running?

Chrome v115.0

### The OS you're using

win

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=2.72/34.55/3.95

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

**Comment by atiannicelli** [comment]
Confirmed - I'm seeing the same thing

**Comment by tordans** [comment]
Sounds like https://github.com/facebook/Rapid/issues/1007

**Comment by bhousel** [comment]
yea the Nominatim issue looks fixed now, I am testing with this url:
https://rapideditor.org/rapid/aa8f4b0-16.x-/index.html

I agree that that search box should probably just do a geocoder/nominatim search in most situations.

**Comment by Bonkles** [comment]
Woops! Should have closed this one. #1017 fixed it.
