### ISSUE TITLE
Fintune Mapillary image overlay

### ISSUE THREAD

**Issue by tordans** [facebook/Rapid#1047]
### Description

We are happy to have a lot of Mapillary images in Berlin. As a side effect, the styling for Mapillary images on the editor map is quite important in order to still comprehend the map data.

I suggest to fine tune the way images are displayed on the map to make them less prominent. For example remove the black outline from all image notes but the selected sequence.

It is also helpful that in iD the sequence line highlights together with the image mouseover.

As a side note, this location also shows an issue with a missing line between some of the images. 

| Rapid | iD |
|--------|--------|
| [Link](https://rapideditor.org/rapid#background=Berlin-2022&datasets=fbRoads,msBuildings&disable_features=boundaries&map=19.72/52.42095/13.51582&photo_overlay=mapillary) | [Link](https://ideditor.netlify.app/#background=Berlin-2018&datasets=fbRoads,msBuildings&disable_features=boundaries&map=19.62/52.42096/13.51583&photo=mapillary/3071715123151195&photo_overlay=mapillary) |
| <img width="983" alt="image" src="https://github.com/facebook/Rapid/assets/111561/ad16b701-32d5-4f81-836f-b10e1139e713"> | <img width="979" alt="image" src="https://github.com/facebook/Rapid/assets/111561/eabe7fcf-ede2-49f6-b78f-6af939867d78"> |

**Comment by bhousel** [comment]
this is still just #539
