### ISSUE TITLE
Make a public development version of rapid available

### ISSUE THREAD

**Issue by tordans** [facebook/Rapid#1051]
### Description

Bonkles, we chatted about this before but after running into this again https://github.com/facebook/Rapid/issues/762#issuecomment-1693254214 and others as well (eg https://github.com/facebook/Rapid/issues/1046#issue-1866889006), I think it would be a good idea to have the current development version released via Vercel or Netlify so we can check there before reporting an issue or request.
It would save me some time … and you as well.

**Comment by bhousel** [comment]
We have a github action that continuously deploys every commit to s3, but is not easy to find.
https://github.com/facebook/Rapid/actions/workflows/deploy.yml

When we do the s3 push, we could probably just alias this to `rapideditor.com/canary` or `/unstable` or something

**Comment by Bonkles** [comment]
Yeah, we'd need to furthermore copy the latest build artifact from the `main` branch to some well-known place, like 'rapiddev'. Shouldn't be too terribly difficult, we've just never had the public interest in our dev builds!

**Comment by Bonkles** [comment]
Looks like we can conditionally fire extra github action steps dependent upon certain conditions- we should be able to modify the existing 'deploy' flow to check if the action came from the `main` branch, and if so just update a well-known url, such as rapideditor.org/rapid-main-branch-latest

**Comment by bhousel** [comment]
I made it so that the deploy action saves the latest build of the `main` branch here:  https://rapideditor.org/canary

Note that this [canary build](https://www.pcmag.com/encyclopedia/term/canary-build) of Rapid may be unstable and buggy!
