### ISSUE TITLE
UNDO actions delete all the nodes in a sequence, not the last one only (2.1.0)

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#1056]
### Description

If you are drawing a line or an area, and you hit the undo button. All the sequence of nodes are deleted instead of only the last one as in ID. These is quite anoying and could promt to delete several dozens or even hundreds of nodes

### Version

2.1.0

### What browser are you seeing the problem on? What version are you running?

Version 114.0.5735.199 (Official Build) (64-bit)

### Steps to reproduce

Just draw any line or area with several nodes and them hit Undo button, and everything will dissapear

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w458000025&map=19.00/-17.87747/-62.82296

**Comment by bhousel** [comment]
Yup, still #858 - in the v2.1 code I did a bunch of work under the hood on making our edit history system easier to work with, so we can make better progress on this one now.
