### ISSUE TITLE
Solving two ways overlap. Produce connecting node, but also could produce more nodes (2.1.0)

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#1059]
### Description

If you ovelap two ways (anykind) without a connection node. A warning show up, if you chose for solution the connecting node shows up, but the Warning do not dissapear. If you hit again the warning another (free) node is created, and you can create several more nodes without the warning dissapearing. 
![Screenshot (85)](https://github.com/facebook/Rapid/assets/22849578/a422a211-2516-46f6-9f98-709048e3de2a)
![Screenshot (84)](https://github.com/facebook/Rapid/assets/22849578/e918b4b6-64f9-4152-ad30-f897fa2df5a3)

### Version

2.1.0

### What browser are you seeing the problem on? What version are you running?

Version 114.0.5735.199 (Official Build) (64-bit)

### Steps to reproduce

Just draw 2 overlaping ways without connecting them and follow instructions of the warning...

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=18.04/-17.80349/-62.90914

**Comment by jjiglesiasg** [comment]
Now also Ways over Waterways do NOT generate a warning.

https://rapideditor.org/rapid#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=17.80/-17.93699/-63.10062
![Screenshot (91)](https://github.com/facebook/Rapid/assets/22849578/dac90890-7c38-439b-b8f3-83b50d3443ce)

**Comment by jjiglesiasg** [comment]
Checked in 2.1.1. and still there is NO WARNING or solution for way over waterway. That's a major issue in Undeveloped countries were fords are in the millions

**Comment by bhousel** [comment]
In #1018 you asked us to remove the warnings when intermittent waterways were involved in the crossing.

**Comment by jjiglesiasg** [comment]
Yes but it was for the Warnings that DUPLICATE THEMSELVES and do NOT dissapear once solved. Not for all of them.

Perhaps I did not explain myself correctly
