### ISSUE TITLE
How to use RapId with local data osm ?

### ISSUE THREAD

**Issue by cuongnc5** [facebook/RapiD#106]
I have a local osm database. Can i use RapId with AI predicted roads that are missing from my local data?

**Comment by Bonkles** [comment]
There are a couple of considerations here. My take: 
1) We *do* want to allow folks to 'Bring Your Own' dataset into RapiD and use it to add features to the map. That is something we're currently looking at / investigating heavily. 
> Can i use RapId with AI predicted roads that are missing from my local data?
2) This is a bit tougher. RapiD doesn't have the ability to merge / conflate seamlessly with other data sets- the back-end service that generates the roads only keeps standard OSM features in mind. To do what you need, we'd have two options: 
a ) our backend service would need to be somehow made aware of your local osm database, which is not something we're prepared to support. 
b) RapiD would need to be taught to do feature conflation on its own- doable, but definitely not high on our priority list right now.

**Comment by cuongnc5** [comment]
Thanks for your response.
I like option 2-a. I can build  my osm api server and RapId can call my osm api and AI predicted roads that are missing from my local data. I hope!

**Comment by gaoxm** [comment]
> Thanks for your response.
> I like option 2-a. I can build my osm api server and RapId can call my osm api and AI predicted roads that are missing from my local data. I hope!

@cuongnc5 yeah that may work - if you are willing to touch the code and build RapiD on your own laptop, give it a shot by updating the urlroot and oauth key and secret here https://github.com/facebookincubator/RapiD/blob/master/modules/services/osm.js#L25

as @Bonkles explained, the AI roads you get will still be conflated with official OSM data, so you may see dupes and missing connection nodes between the AI roads and features pulled from your own OSM API server, but with some additional manual editing you may be able to submit changesets to your own OSM API server; good luck 😄
