### ISSUE TITLE
Number of edits remains on screen after upload

### ISSUE THREAD

**Issue by misibacsi** [facebook/Rapid#1060]
### Description

In the upper right corner the number of edits remains on screen after a successful upload.
After a page refresh in browser the number disappears.
In the previous version the number  was shown correctly - it disappeared after upload.
![2023-08-29 Rapid v210 error](https://github.com/facebook/Rapid/assets/11352049/bce0f024-234e-466f-b690-89d71f9242f1)

### Version

2.1.0

### What browser are you seeing the problem on? What version are you running?

Firefox v116.0

### The OS you're using

win11

### Steps to reproduce

Make some edits and upload to OSM.

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=FOMI_2007_2010&datasets=fbRoads,msBuildings&disable_features=landuse,pistes,aerialways,past_future&map=18.35/46.37995/16.89776

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0

**Comment by jjiglesiasg** [comment]
Same happens to me...

**Comment by joecaruso** [comment]
I have seen this as well.

**Comment by Bonkles** [comment]
Thanks for the report! This is one we'll have to tackle soon in a minor patch release.

**Comment by jjiglesiasg** [comment]
The numbers are fixed in 2.1.1. but the warnings remain in the lower section. Attached image 
![Screenshot (93)](https://github.com/facebook/Rapid/assets/22849578/809366eb-f7db-4371-980d-e3a02427d0b3)
