### ISSUE TITLE
Unmarked crosswalk always needs tag upgrade after accepting warning recommendation

### ISSUE THREAD

**Issue by cbeddow** [facebook/Rapid#1063]
### Description

when I draw an unmarked crosswalks and then accept the warning recommendation to connect to the road, it adds a crossing node but it always prompts me to upgrade the tags when I go to submit.

### Version

2.1

### What browser are you seeing the problem on? What version are you running?

Chrome 115.0.5790.173 64-bit

### The OS you're using

Windows 11

### Steps to reproduce

Add an unmarked crosswalk line, but do not join to the road

Go to upload changeset and check warnings

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit?#background=Mapbox&datasets=msBuildings&disable_features=boundaries&gpx=https://mwai-tasking-manager-production-api.mapwith.ai/api/v2/projects/147/tasks/queries/gpx/%3Ftasks%3D2555&map=18.52/32.69383/-117.17153

**Comment by bhousel** [comment]
Thanks, I'll check it - I really thought I covered all the cases with #1015  😢

**Comment by Bonkles** [comment]
Okay! This should be a thing of the past. 

Interestingly, there are two cases to consider here: 
1) The base case- a completely new way being drawn over a highway of some type.
![image](https://github.com/facebook/Rapid/assets/1887955/352016e5-e75f-4232-8434-1fd501d00c9c)

In this case, drawing a 'pedestrian crossing' does not imply any markings whatsoever, so to avoid being told to upgrade the tags, we assume that the node should be created with `crossing:markings=no`. 

If the way being drawn is specifically an 'unmarked crossing' as per the preset, we will create the node with `crossing:markings=no` and `crossing=unmarked`. 

If the way being drawn is marked with `crossing:markings=zebra` and `crossing=marked`, then we will use those same tags in the crossing node. 

![image](https://github.com/facebook/Rapid/assets/1887955/08ff4c86-db75-428a-bfe8-f8716f147d6f)


2) The special case where the existing highway already had a crossing node of some kind
![image](https://github.com/facebook/Rapid/assets/1887955/ad2c5bc9-715c-4d9b-be87-334806d526de)

in this case, we will NOT attempt to do anything except stitch the new crossing way to the existing node. Any issues the pre-existing node's tags had will need to be fixed as normal.
