### ISSUE TITLE
Marked crosswalk lines generate generic crossing node instead of marked crosswalk node

### ISSUE THREAD

**Issue by cbeddow** [facebook/Rapid#1064]
### Description

when I draw a marked crosswalk, and accept the warning to join it to the road, it just adds a generic crossing node, but not a specifically marked crossing node.

### Version

2.1

### What browser are you seeing the problem on? What version are you running?

Chrome 115.0.5790.173 64-bit

### The OS you're using

Windows 11

### Steps to reproduce

Add marked crosswalk line

Check warnings that the line crosses a road

Accept warning recommendation

check new crossing node tag

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit?#background=Mapbox&datasets=msBuildings&disable_features=boundaries&gpx=https://mwai-tasking-manager-production-api.mapwith.ai/api/v2/projects/147/tasks/queries/gpx/%3Ftasks%3D2555&map=18.52/32.69383/-117.17153

**Comment by bhousel** [comment]
Thanks, I'll check it - I really thought I covered all the cases with #1015  😢

**Comment by Bonkles** [comment]
Quick vid showing that we now correctly update the tags in this case: 

https://github.com/facebook/Rapid/assets/1887955/363f43aa-654c-4e81-a3f1-714fa9b8e01f
