### ISSUE TITLE
Rapid freeze quite often and unable to add tags to an element using the +

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#1066]
### Description

The app seems to freeze even without many elements added. And in several cases you are unable to add tags for a selected element using the + option. Attached image
![Screenshot (87)](https://github.com/facebook/Rapid/assets/22849578/571197a8-821f-4d91-be9b-596fc71c58d6)

### Version

2.1.0

### What browser are you seeing the problem on? What version are you running?

Version 114.0.5735.199 (Official Build) (64-bit)

### Steps to reproduce

Choose or create an element and try to add different tags pressing the + (black) key option. Nothing happen
![Screenshot (88)](https://github.com/facebook/Rapid/assets/22849578/ef60c960-c838-4f7a-9dbf-5e0fde417f06)

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=n-746&map=17.08/-17.80498/-62.90783

**Comment by bhousel** [comment]
Weird - I notice you're getting the "You have made too many edits to back up" message.. That's really unusual for having only made 3 edits.  Is it possible you have a browser extension installed that is preventing Rapid or iD from accessing localStorage?

Also, you can open the developer tools and see whether there are any errors happening - I think on Windows Chrome <kbd>F12</kbd> can do this?  

It can also be found under that kebab menu in the upper right: <sub><sub><img width="33" alt="Screenshot 2023-08-30 at 10 20 59 AM" src="https://github.com/facebook/Rapid/assets/38784/da9de8f5-67b7-495c-aeab-1e0fb6d2c62a"></sub></sub>

**Comment by jjiglesiasg** [comment]
Hi Bryan. That warning remains from the previous Changest and not from the current one that I was doing.

**Comment by bhousel** [comment]
It looks like this is now working in the latest code on `main`.. It likely got fixed during #1084 or #1156
