### ISSUE TITLE
3D Buildings freezes the UI

### ISSUE THREAD

**Issue by tordans** [facebook/Rapid#1067]
### Description

Update: This has nothing to do with the preview panel, it looks like some data in this location freezes the UI.

1. I open https://rapideditor.org/edit#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=18.91/52.47307/13.44840
2. I activate 3D Buildings
3. I pan the 3D Preview Map to the right so more on the left is visible… but there is only white space
4. Now the main window is frozen and cannot be panned anymore

The console says:

```
Uncaught Error: Entity w166430018 not found
    at t.entity (Graph.js:96:13)
    at relation.js:229:76
…
```

### Version

2.1.0

### What browser are you seeing the problem on? What version are you running?

Chrome v115.0

### The OS you're using

mac

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=18.91/52.47307/13.44840

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

**Comment by Bonkles** [comment]
Looks like this had to do with panning over a large relation that included ways that were very far away. in this case, we should simply omit displaying the relations for the 3D map, as they aren't what we're really after.
