### ISSUE TITLE
3D Buildings: Store UI state in URL

### ISSUE THREAD

**Issue by tordans** [facebook/Rapid#1068]
### Description

I want to lobby to store all UI configuration state in the URL as a default approach. I find it super annoying to not be able to store the configuration of iD via URLs between sessions.

In this specific case, having 3D buildings active/hidden is not stored in the URL and thus cannot be shared or preserved between reloads or via bookmarks.

**Comment by alhridoy** [comment]
Hi @tordans Which file you are referring to. I would love to work on it.

**Comment by Bonkles** [comment]
@voscarmv another prospective issue for you to work on here- also pertaining to the URL Hash system. 

When you click the `command-/` keyboard shortcut a 3D map component will open. It would be nice to store the state of the 3D map in the URL parameter hashes, so this will build off your current work!

**Comment by voscarmv** [comment]
Working on this, @Bonkles !
