### ISSUE TITLE
Selecting Multiple elements with Press and Hold Shift Key, deselect itself

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#1071]
### Description

if you press and hold the SHIFT key and start to select multiple elements, if you DO NOT release the SHIFT KEY all selected elements should be keep selected whatsoever you touch by mistake or you miss to touch another element.

Currently all elements are unselected whatsoever you keep pressing the SHIFT KEY.

### Version

2.1.0

### What browser are you seeing the problem on? What version are you running?

Version 114.0.5735.199 (Official Build) (64-bit)

### Steps to reproduce

Press and hold SHIFT KEY and start to select elements, in a given moment, just touch any area without elements, and the all elements previously choosen are "released" even keeping the Shift key pressed.

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=Bing&datasets=fbRoads,msBuildings&disable_features=points,boundaries,power&map=16.40/-17.87395/-62.97283

**Comment by mxxcon** [comment]
This is a very frustrating behavior. Often even while I keep holding down shift and click on additional nodes RapiD loses the whole selection.

The point of shift-selecting multiple nodes is when I want to tag them all the same way (for example all curbs on an intersection) to minimize number of clicks I have to do (vs tagging each node one at a time). But the fact that RapiD randomly loses selection is EXTREMELY frustrating to the point of infuriating  (╯°□°）╯︵ ┻━┻. It often cost me more clicks to keep reselecting lost selections than to just manually tag each node one at a time.
