### ISSUE TITLE
Clicking "Restore My Changes" too fast can cause crash

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#1074]
### Description

If you make some editions (not reaching the warning level) and by any circumstance the app is closed. Them it does not retrieve the unsaved editions but stall in an endless loops like loading, but nothing happens.

It happens the same couple of days ago, but I guess it was because the poweruser feature. Now none of that was in place and still do not upload the unsaved data.

![Screenshot (90)](https://github.com/facebook/Rapid/assets/22849578/77b18fb5-84cb-43a9-ae3e-83427ba6807b)

### Version

2.1.0

### What browser are you seeing the problem on? What version are you running?

Version 114.0.5735.199 (Official Build) (64-bit)

### Steps to reproduce

As described above

Quite annoying

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=18.00/-14.76062/-68.43293

**Comment by bhousel** [comment]
I think what's happening here is a bug that's not tracked yet but that @Bonkles and I have run into before.. 

If the user clicks the "Restore my Changes" button too fast, the system gets into a bad state.   (I can reproduce this pretty easily by restoring changes quickly while the map is loading, it will crash in the validator code).
