### ISSUE TITLE
Rapid latest published version

### ISSUE THREAD

**Issue by bhousel** [facebook/Rapid#1075]
Starting with Rapid v2.1, we've started publishing our releases as a NPM package here: [@rapideditor/rapid](https://www.npmjs.com/package/@rapideditor/rapid)

Some people have asked in the past for "how to have a Rapid that just always fetches the latest version". 
We can probably do that now!

So this issue is just for me to make an example html page that just loads latest release of Rapid from the [jsDelivr CDN](https://www.jsdelivr.com/).

**Comment by tsmock** [comment]
>  We can probably do that now!

As part of my work on getting Rapid v2 into the TM, I did exactly that with the jsdelivr CDN. It was a bit different from your static HTML page though.

Anyway, I used `~` to restrict the semver version to patch releases (to avoid breakage due to API changes). Example:

```js
// We import from a CDN using a SEMVER minor version range
import { version as rapidVersion, name as rapidName } from '@rapideditor/rapid/package.json';

const baseCdnUrl = `https://cdn.jsdelivr.net/npm/${rapidName}@~${rapidVersion}/dist/`;
```

Later on in the javascript, I did the following to dynamically load Rapid
```js
    // Add the style element
    const style = document.createElement('link');
    style.setAttribute('type', 'text/css');
    style.setAttribute('rel', 'stylesheet');
    style.setAttribute('href', baseCdnUrl + 'rapid.css');
    document.head.appendChild(style);
    // Now add the editor
    const script = document.createElement('script');
    script.src = baseCdnUrl + 'rapid.js';
    script.async = true;
    script.onload = () => { /* do stuff after rapid script load, like setting up rapid */ };
    document.body.appendChild(script);
```
