### ISSUE TITLE
The Plus (+) button for adding additional tags to an element is not working quite often 

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#1087]
### Description

Select an element and try to add more tags. Sometimes works sometimes not

### Version

2.1.0

### What browser are you seeing the problem on? What version are you running?

Version 114.0.5735.199 (Official Build) (64-bit)

### Steps to reproduce

Just select any element or create one, and use the Black Plus (+) command; several times do not work

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=16.36/-17.91774/-63.06816

**Comment by bhousel** [comment]
This could be a duplicate of #1084 - a lot of stuff was affected by that, but only _after_ the user saved the first time.

**Comment by bhousel** [comment]
also #1066

**Comment by bhousel** [comment]
It looks like this is now working in the latest code on `main`.. It likely got fixed during #1084 or #1156
