### ISSUE TITLE
Version discrepancy 

### ISSUE THREAD

**Issue by gyCfjSnO** [facebook/Rapid#1088]
### Description

The reported Rapid version doesn't match the latest one in the changelog.

### Version

2.0.3

### What browser are you seeing the problem on? What version are you running?

Edge v116.0

### The OS you're using

win

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=EsriWorldImagery&datasets=fbRoads,msBuildings&disable_features=boundaries&map=2.00/0.0/0.0

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.62

**Comment by bhousel** [comment]
> The reported Rapid version doesn't match the latest one in the changelog.

The changelog sometimes includes stuff for the next release -  We're planning to release 2.1.1 today, so we will have to update that date that is on there.  (it should probably say "pending release" or something instead of a real date)

**Comment by Bonkles** [comment]
Actually @gyCfjSnO your bug report says that you're still using 2.0.3. That shouldn't be happening anymore- can you please hard reload your browser and see if the 2.1.0 release replaces it?

**Comment by bhousel** [comment]
v2.1.1 is released and live on rapideditor.org now, so I'm going to close this

**Comment by gyCfjSnO** [comment]
`CTRL + SHIFT + R` _(Reload the current page, ignoring cached content)_ resolved this issue.
