### ISSUE TITLE
Metromap API key exposed in changeset

### ISSUE THREAD

**Issue by antburnett** [facebook/Rapid#1096]
### Description

When using the Aerometrex Metromap API, the API key is exposed in the changeset.

The iD editor masks the key as follows:
![image](https://github.com/facebook/Rapid/assets/15881590/cc0bf810-fb3d-46bf-b6e2-4ee353a3f6c7)

The Rapid editor does not:
![image](https://github.com/facebook/Rapid/assets/15881590/3df2499f-0a37-46f2-a0d9-7e72e51f6d65)

### Version

1.1.9

### What browser are you seeing the problem on? What version are you running?

Edge Version 116.0.1938.69 (Official build) (arm64)

### The OS you're using

MacOS 14.0

### Steps to reproduce

Perform an edit with iD, and review the changeset summary. The "imagery_used" will read _Custom ([https://api-v3.metromap.com.au/tiles/xyz/Australia_latest/{z}/{y}/{x}.png?key={apikey}](https://api-v3.metromap.com.au/tiles/xyz/Australia_latest/%7Bz%7D/%7By%7D/%7Bx%7D.png?key={apikey}) )_

Do a new edit, this time with Rapid via https://ideditor.org/rapid. Review the changeset and "imagery_used" will read _Custom ([https://api-v3.metromap.com.au/tiles/xyz/Australia_latest/{z}/{y}/{x}.png?key=aw5vi7v3pi3...t5t](https://api-v3.metromap.com.au/tiles/xyz/Australia_latest/%7Bz%7D/%7By%7D/%7Bx%7D.png?key=aw5vi7v3pi3...t5t) )_

### The browser URL at the time you encountered the bug

https://www.openstreetmap.org/changeset/140827236#map=17/-33.87055/151.18296

**Comment by tsmock** [comment]
1. https://ideditor/rapid is using 1.1.9 instead of 2.1. I don't know if we can update that. If we cannot, use https://rapideditor/edit instead.
2. It looks like iD did this in https://github.com/openstreetmap/iD/commit/72af994b2cd4af1a56577749708aa2598eaf8d48 . I'll see if I can cherry-pick the missing commit and modify it to work with the new structure.

**Comment by tsmock** [comment]
I've got a branch (https://github.com/facebook/Rapid/tree/fixup-1096). I'd open a PR, but I've been getting a GH "oops" page when I try.

**Comment by antburnett** [comment]
The problem is not restricted to version 1. I just tried my new API key in Rapid 2.1.1 and the issue is there too:
![image](https://github.com/facebook/Rapid/assets/15881590/82aab8e1-84a9-40fa-af1a-44d67c85b4bc)
