### ISSUE TITLE
Opening Rapid with id=... query parameter does not zoom to object

### ISSUE THREAD

**Issue by elevenchars** [facebook/Rapid#1108]
### Description

When I open Rapid with an `id` query parameter, it shows up in the left "Edit feature" pane but it does not zoom the map to the location of the object. However, pressing "zoom to selection" zooms to the object correctly.

### Version

2.1.1

### What browser are you seeing the problem on? What version are you running?

Firefox 117

### The OS you're using

MacOS 13.5.2

### Steps to reproduce

1. Open a Rapid url which contains an valid id query parameter. (Here is the one that I originally noticed this with, generated by OSMCha: https://mapwith.ai/rapid#id=w1204555438)
2. Observe that the editor does not zoom to the object as expected.

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w1204555438&map=2.00/0.0/0.0

**Comment by Bonkles** [comment]
Reassigning to @voscarmv, our third cohort member for the MLH pod joining us this fall

**Comment by voscarmv** [comment]
Glad to be here!

**Comment by bhousel** [comment]
I actually think this issue might have been fixed already.

**Comment by elevenchars** [comment]
I just tested it on latest commit of main and the issue is still present. Is the fix on another branch ?

**Comment by bhousel** [comment]
Thanks for confirming - I just tested and I agree, it's wrong! 😄 
http://127.0.0.1:8080/#background=Bing&id=w1204555438&map=2.00/0.0/0.0

I'll take care of this myself - it's related to code that I recently moved from Context into MapSystem, but UrlHashSystem is involved too.  This relates to the order that things start up and events fire.

**Comment by voscarmv** [comment]
Hi @bhousel I just subitted a PR for this!

**Comment by voscarmv** [comment]
> Hi @bhousel I just subitted a PR for this!
> 
> Here it is: #1170

PR #1170 is 16 commits behind the main branch.

I made another PR but this time it's rebased on the latest Rapid commit, here: https://github.com/facebook/Rapid/pull/1173

I'd appreciate your code review please. Thank you!
