### ISSUE TITLE
Warning says train platform crosses transit shelter (but they are connected)

### ISSUE THREAD

**Issue by cbeddow** [facebook/Rapid#1112]
### Description

I have a transit shelter polygon and a train platform polygon that share nodes. When I go to submit a changeset a warning says they cross, but they are fully connected.

### Version

2.1.1

### What browser are you seeing the problem on? What version are you running?

Chrome v115.0

### The OS you're using

win

### Steps to reproduce

Go to submit changeset or check warnings

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=swisstopo_swissimage&datasets=fbRoads,msBuildings&disable_features=boundaries&map=21.76/47.04974/8.54992

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

**Comment by cbeddow** [comment]
@Bonkles ah seems the link in the bug report snapped to somewhere else

So here: https://rapideditor.org/edit?fbclid=IwAR0pA1Osa0rmY-U_Ei0se7GtCWnZ8CatDzHwNnqFkqOs8KBY866fHXjkZdY#background=swisstopo_swissimage&datasets=fbRoads,msBuildings&disable_features=boundaries&map=21.52/47.04906/8.54839

It's this building: 

![image](https://github.com/facebook/Rapid/assets/10554922/62d35b90-f49f-4633-8958-f9738f9d0bc8)

building:
w1138811606

transit platform:
w121135463

**Comment by cbeddow** [comment]
It looks like me like it is resolved, but the editor was still showing the conflict as a lag, even after I resolved it, then caught up

**Comment by Bonkles** [comment]
Got it thanks! - I'll close this one and pursue updates (or the lack thereof) for the validations in #1116
