### ISSUE TITLE
Feature request: automatically join marked/unmarked crosswalk lines to roads when created

### ISSUE THREAD

**Issue by cbeddow** [facebook/Rapid#1115]
### Description

When I create an unmarked or marked crosswalk, I find I then have to either manually create a node or look for the warning message to autojoin it to the road it crosses.

For some way types like sidewalk or path or other road, it makes sense to warn and choose bridge, tunnel, connect.

For crosswalk I would prefer it to auto connect to other roads (but not to things like streams, rivers, etc of course). This saves me from slowing down to fix the connection.

**Comment by mxxcon** [comment]
No way should auto connect to other intersecting ways. It takes a lot less effort to connect relevant ways to each other than to undo incorrect connections, which can result in data loss, especially if done by inexperienced users.

At most this should be an option or a modifier and not the default behavior.

**Comment by Bonkles** [comment]
I tend to agree with @mxxcon here for general use, but something like this may be more appropriate for a power user feature.

**Comment by Bonkles** [comment]
Upon some further reflection, I am going to close this as 'will not implement'. I have made edits and updates to a couple of crossing validations so that the user has fewer clicks to stitch a crossing into an intersecting way- that goes SOME of the way to helping this problem.
