### ISSUE TITLE
"You have made too many edits" warning does not disappear on save

### ISSUE THREAD

**Issue by Sellyme** [facebook/Rapid#1120]
### Description

When using Rapid in Power User mode, it's possible to make a large number of changes without being forced to save in order to continue. At some point, a red warning message at the bottom of the screen reading "You have made too many edits to back up. Consider saving your changes now." appears.

After saving, this warning stays visible, leading to an unusual situation where the editor is simultaneously saying I've made zero edits (top-right) and "too many edits" (bottom-right):
![image](https://github.com/facebook/Rapid/assets/1928024/05a00c98-81e7-4408-8002-9fd751ef12b2)

### Version

2.1.1

### What browser are you seeing the problem on? What version are you running?

Firefox Developer 118.0b8 (64-bit)

### The OS you're using

Windows 11 Pro N

### Steps to reproduce

* Open Rapid in poweruser mode

* Make many (~100) changes to the map, until the `api-status error` footer appears with the "You have made too many edits[...]" message appears

* Save your changes.

* Note that the footer remains with a no longer valid error message.

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=Bing&datasets=fbRoads,msBuildings&map=18.08/32.48759/107.10261&overlays=osm-gps&poweruser=true

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0

**Comment by Sellyme** [comment]
This is likely related to issue #1060, possibly whatever fix was applied for that missed this portion of the UI.

**Comment by simonschaufi** [comment]
Can this bug be fixed please? It should be quite easy to fix :)

**Comment by bhousel** [comment]
> @bhousel Can this bug be fixed please? It should be quite easy to fix :)

Sorry!  To be honest, I thought we fixed this already.  I'll take a look..
(I agree that it should be easy, and it's probably like #1060)

**Comment by simonschaufi** [comment]
It still shows up after 170 changes.

**Comment by bhousel** [comment]
Yep, that number is less an actual number, and more to do with how complex the thing is being edited.  Waterways, landuse, coastlines, and similar things can really fill the storage up, because we try to store what it looked like before the user started their edits.

**Comment by simonschaufi** [comment]
The number can stay the same but the message should be gone after save, that's the whole point ;)

**Comment by bhousel** [comment]
Over the past few days I've done a bunch of work on how we surface the status issues to the user, and can confirm that this is fixed now 👍

**Comment by simonschaufi** [comment]
Nice, can you also release that please?
