### ISSUE TITLE
Data layers provided by Mapbox no longer working

### ISSUE THREAD

**Issue by elevenchars** [facebook/Rapid#1122]
### Description

The following data layers are not working on Rapid for me:
- U.S. Forest Roads Overlay
- TIGER Roads 2020
- TIGER Roads 2021
- TIGER Roads 2022

From looking at network tab they are all returning HTTP 401. Looks like the layers are provided by Mapbox and the keys need to be rotated. See: https://github.com/osmlab/editor-layer-index/pull/2060

### Version

2.1.1

### What browser are you seeing the problem on? What version are you running?

Firefox 117.0.1

### The OS you're using

Fedora 38 Linux

### Steps to reproduce

1. Enable any of the listed data layers
2. Observe that none of the layers load

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid#background=Mapbox&datasets=fbRoads,msBuildings&disable_features=boundaries&map=18.24/31.10634/-97.69862&overlays=US_Forest_Service_roads_overlay,US-TIGER-Roads-2020,US-TIGER-Roads-2021,US-TIGER-Roads-2022

**Comment by bhousel** [comment]
Yes, this is expected - we'll bundle a fresh copy of editor-layer-index the next time we make a release.

**Comment by elevenchars** [comment]
Would it be possible to make a new release for this? Thanks!

**Comment by bhousel** [comment]
Yes! We are going do do a release mid December that includes this.  

I think in the mean time you can also test the new version at http://rapideditor.org/canary and the imagery list there is pretty up to date.

**Comment by bhousel** [comment]
Can close this - we've made several recent releases that include updated imagery ...
