### ISSUE TITLE
OSM username isn't escaped properly

### ISSUE THREAD

**Issue by jleedev** [facebook/Rapid#1124]
### Description

See: https://github.com/openstreetmap/iD/issues/8813

### Version

2.1.1

### The browser URL at the time you encountered the bug

Cannot bookmark a link to the dev server. https://rapideditor.org/edit#map=18.00/40.43877/-79.97923

**Comment by RitaDee** [comment]
I would love to give this a try.

**Comment by Bonkles** [comment]
Awesome @RitaDee! I stand corrected- I can, in fact, assign you this task. :)
