### ISSUE TITLE
Road connectivity warnings don't update when connected

### ISSUE THREAD

**Issue by Sellyme** [facebook/Rapid#1125]
### Description

Under some circumstances when making additions to the road network, a newly created (unconnected) road will display a warning upon its addition to the map, but not get *rid* of this warning when a new road is created connecting it to the rest of the network. The warning seems to only go away if the original way is modified further **after** having been connected to the network.

### Version

2.1.1

### What browser are you seeing the problem on? What version are you running?

Firefox 117.0.1 (64-bit)

### The OS you're using

Windows 10 Home

### Steps to reproduce

1. Find an area with incomplete road mapping:

![image](https://github.com/facebook/Rapid/assets/1928024/68f99807-8b1d-4fd2-af20-99bda651abf3)

2. Create a way that is **not** yet connected to the pre-existing road network, and tag it appropriately:

![image](https://github.com/facebook/Rapid/assets/1928024/0009dbfa-b117-450b-b3fa-5ecbd589e64e)

3. Noting the error that has appeared, create a new way connecting this road to the existing road network:

![image](https://github.com/facebook/Rapid/assets/1928024/cfdc3c7c-db23-4d0c-b545-2ebda0d9ca8d)

4. Observe that the existing way still has a now-incorrect warning:

![image](https://github.com/facebook/Rapid/assets/1928024/d7e42207-445d-4072-a9fc-54584611f62c)

5. At this stage, any movement of any node attached to the way created in step 2 will result in the error message going away, **even if the modification is immediately undone**. So the engine is aware that the way is connected, it's just not checking to see if the status of the way has changed on connections, only on modifications.

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w-81&map=19.42/-33.72847/150.88405&overlays=osm-gps&poweruser=true

**Comment by jjiglesiasg** [comment]
Already reported since 2.0, still not solved..

**Comment by bhousel** [comment]
Yeah, this one is something that has been around since the iD code
https://github.com/openstreetmap/iD/issues/8758

**Comment by jjiglesiasg** [comment]
By the way this issue create a permanent "Issue (errot)" in OSMI for routing, likewise when you add a NoExit tag at the end of the road, if it's close to another way. OSMI and OSMOSE both keep the issue open...
