### ISSUE TITLE
Restoring backup too fast causes crash

### ISSUE THREAD

**Issue by bhousel** [facebook/Rapid#1126]
If you click the "Restore my changes" button too fast, Bad Things happen.

Sometimes it's:
```
Uncaught TypeError: Cannot read properties of undefined (reading '_stack')
  at _childNodesLoaded (EditSystem.js:751:37)
  at OsmService.js:1353:7
```
But I've also seen it as an "Entity not found" kind of error.

![restore too fast](https://github.com/facebook/Rapid/assets/38784/6ecdbc54-b38d-423e-aae3-4df14461842b)

**Comment by jjiglesiasg** [comment]
I cease using this app for a while because of this issue. I lost a huge amount of work and I was totally dissatisfied with the behavior of the app
