### ISSUE TITLE
All selected line features deselected when shift-click open area

### ISSUE THREAD

**Issue by bradlewt** [facebook/Rapid#1137]
### Description

When using shift-left click to select multiple features to edit them ensemble, like the line version of buildings in the attached video, if you don't click exactly on the line, the entire selection is lost.  This is particularly difficult with initially incorrect buildings saved as lines because normal buildings _can_ be selected from an internal click.
https://github.com/facebook/Rapid/assets/24398638/baff3d5a-e304-46b9-8d10-dc995c6bc268

### Version

2.0.3

### What browser are you seeing the problem on? What version are you running?

Chrome v117.0

### The OS you're using

win

### Steps to reproduce

1. Select initial line feature
2. hold shift and slick additional features
3. still holding shift, "accidentally" click somewhere other than on a feature
4. watch all previously selected features be deselected
5. gnash teeth

https://github.com/facebook/Rapid/assets/24398638/9211e363-055e-46f9-99d1-db83ec7377db

### The browser URL at the time you encountered the bug

https://maproulette.org/challenge/14016/task/62628601?#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w1116329185&map=19.96/12.87797/14.29784

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

**Comment by bhousel** [comment]
Thanks for the report, we'll try to investigate what's going on.
I see that you're using a slightly older version 2.0.3 through the maproulette embed - I can't remember whether this is an issue that we fixed in 2.1.  🤔
