### ISSUE TITLE
Too much overlap in AI suggested data elements (Buildings)

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#1144]
### Description

In crowded urban areas adding AI data for buildings produce too many overlapping warnings in adjacent elements (buildings) that require extensive edition of elements involved in the conflict.

Implementing the resizing (Up - Down) (Shift + or Shift -) as in ID. Could very much expedite this process, as in real life the elements are not overlapping themselves is just the AI data that shown them overlapped.

Thanks

**Comment by bhousel** [comment]
yep, reimplementing scaling is tracked on #912
