### ISSUE TITLE
Rapid is really slow

### ISSUE THREAD

**Issue by marcregan** [facebook/Rapid#1145]
### Description

* When I hover over an element, it takes 1-2 seconds to highlight.
* Same with selecting an element
* When I click and drag the map, it often doesn't move. Sometimes it will move a second later. 

https://github.com/facebook/Rapid/assets/1158294/069849bb-d667-4782-956a-36453ad5807f

https://github.com/facebook/Rapid/assets/1158294/738b1bd0-29ef-4988-afd1-c019344c2bf7

### Version

2.1.1

### What browser are you seeing the problem on? What version are you running?

Chrome v117.0

### The OS you're using

mac

### Steps to reproduce

This always happens. 
MacOS 13.5.2
Using a 5K external display.
Macbook 13-inch, M1, 2020.

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid#background=MassGIS_2021_Aerial&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w845058106&map=20.00/42.36584/-71.10221

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

**Comment by Bonkles** [comment]
> Using a 5K external display.

Hmmmmmm! That's very interesting. 

I'm using rapid in a 3440x1440 Ultrawide screen, but nothing near a 5k screen. I may have to do some testing with that display to see if there's something going on in webGL-land. 

If you disconnect from the monitor and use Rapid in your laptop screen, does that change the experience for you?

**Comment by bhousel** [comment]
Hey I was scanning the issues and I realized that this one has some news that might be useful for people reporting laggy rendering performance, particularly in Chrome or Safari, and particularly with Apple laptops.. (this seems to disproportionally affect the Meta folks - @cbeddow @marcregan, maybe others?)

For background, [ANGLE](https://en.wikipedia.org/wiki/ANGLE_(software)) is the technology used in most browsers to render accelerated 3D graphics.  This tech is being migrated from OpenGL to newer lower level libraries like [Vulkan](https://en.wikipedia.org/wiki/Vulkan) (non-Apple) and [Metal](https://en.wikipedia.org/wiki/Metal_(API)) (on Apple).

The new rendering backend should end up being more performant eventually, but right now it is still causing some issues, and the OpenGL option may be the best one for now.

@Bonkles learned that there is a flag you can use to switch this:

* In Chrome open a new tab and navigate to `chrome://flags/` 

* Find the "ANGLE graphics backend" option, and switch it to "OpenGL" - restart your browser and you might see vastly improved performance!

<img width="768" alt="Screenshot 2024-04-18 at 10 10 15 AM" src="https://github.com/facebook/Rapid/assets/38784/05d53d5b-af1b-442a-a346-1c68682aa245">



Let us know if it helps!

**Comment by gy-mate** [comment]
> @Bonkles learned that there is a flag you can use to switch this:
> 
> * In Chrome open a new tab and navigate to `chrome://flags/`

@bhousel Is there an option like that in Safari? I'm also experiencing slow performance on Safari `17.5`.

**Comment by bhousel** [comment]
> @bhousel Is there an option like that in Safari? I'm also experiencing slow performance on Safari `17.5`.

It looks like prior to Safari 17 there was a toggleable feature flag for "WebGL via Metal", but this has been removed and I guess they are considering it stable enough. 
https://ios.gadgethacks.com/how-to/safaris-massive-upgrade-comes-with-over-18-new-features-for-iphone-ipad-and-mac-0385417/

I do know there are lots of other places in our renderer where we can still improve the performance a bunch, so this will get better over time as we do more profiling and learn to use Pixi in a more efficient way.
 
Specifically I know that Safari doesn't support [`requestIdleCallback`](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback), which is a call we use to schedule validation work.  So, on Safari only, this work can interrupt other important things on the main thread. (this is part of why #1077 would be useful).

**Comment by gy-mate** [comment]
I see. Thank you for the answer!

**Comment by eneerhut** [comment]
I forgot about this issue and just reset the ANGLE graphics back to default only to see performance regress immediately. @bhousel @Bonkles do you think it could be worth notifying a user to make this change if we detect they are using an M1 mac?

**Comment by bhousel** [comment]
> do you think it could be worth notifying a user to make this change if we detect they are using an M1 mac?

My hope is that this can be fixed in the Pixi library and we don't need to bother our users with this detail.
I'm kind of hoping that the upgrade to v8 #1495 improves this, but once the upgrade is behind us, we can dig in more.

Incidentally , I think this might be the fix:
https://x.com/SebAaltonen/status/1796168886477324629

<img width="601" alt="Screenshot 2024-09-26 at 10 43 03 AM" src="https://github.com/user-attachments/assets/d5c59b19-59a1-4fd4-8275-efba041e199f">

**Comment by gy-mate** [comment]
@bhousel Wow, it's really smooth for me on Safari `18.1.1`, no lagging! Thanks a lot! :)

**Comment by bhousel** [comment]
Lots of people have reported that the performance is better now after the Pixi v8 upgrade in #1495 , so I'm considering this issue with the ANGLE backend closed 👍   

There are still a bunch of other performance improvements we can make by improving the scene, these are tracked on other issues.
