### ISSUE TITLE
Feature Request: Tactile pavement lowered curb node preset

### ISSUE THREAD

**Issue by cbeddow** [facebook/Rapid#1146]
### Description

Currently to add a lowered curb with tactile pavement at either end of a crosswalk, I have to first add a lowered curb tag, then manually select the tactile pavement=yes part. It would be great to search for "tactile pavement" and get a preset for that already to quickly map these. 

https://rapideditor.org/rapid#background=MassGIS_2021_Aerial&datasets=fbRoads,msBuildings&disable_features=boundaries&id=n-1&map=21.88/42.38073/-71.14114

![image](https://github.com/facebook/Rapid/assets/10554922/b6a90854-f2ad-4dc9-a74f-f72292b8787f)

**Comment by bhousel** [comment]
Good idea!  I added these as preset overrides, similar to #1182:

<img width="386" alt="Screenshot 2023-10-31 at 11 20 56 AM" src="https://github.com/facebook/Rapid/assets/38784/6905115d-f544-4577-9a96-d81c3c530c1f">

The are the same as the other curb presets, but with `tactile_paving=yes` tag set.
