### ISSUE TITLE
RapiD login bug

### ISSUE THREAD

**Issue by jmm1893** [facebook/Rapid#1147]
### Description

I am unable to login to RapiD. I am able to made edits and use the UI normally, however, when I try to upload a prompt asks me to login unsuccessfully. 

I have tried clearing chrome data and relogging in to both my OpenStreetMap account and Rapid account separately. I have also tried using incognito mode to no success. 

### Version

2.1.1

### What browser are you seeing the problem on? What version are you running?

Chrome v117.0

### The OS you're using

mac

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=3.59/24.61/-43.79

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36

**Comment by bhousel** [comment]
Thanks for reporting-  I also just started getting this a few minutes ago..
We'll investigate!

**Comment by tsmock** [comment]
This may be a known issue server-side. See https://github.com/openstreetmap/operations/issues/867#issuecomment-1747476977 .

**Comment by grischard** [comment]
The issue has been fixed server-side.

**Comment by bhousel** [comment]
Thanks!
