### ISSUE TITLE
Please consider changing the Magenta Color for AI suggested buildings

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#1151]
### Description

I am sure there is not a Fit for all solution, but buildings are not easilly to be seen in the dark magenta color is they are in a dark contrats enviroments like forrest, woods, jungle, etc. a Lighter or Brighter color should be very handy.

Roads has not the same problem becuase the size.

Thanks

**Comment by Bonkles** [comment]
@jjiglesiasg - you can change the color of the buildings using the color picker in the Rapid menu!: 

https://github.com/facebook/Rapid/assets/1887955/8cb68958-e405-4342-add3-19f4769e190e

Additionally, if the buildings don't stand out against the imagery you can change the imagery using the Background Imagery -> Image Options controls: 

https://github.com/facebook/Rapid/assets/1887955/e06b0a63-e423-4350-bd0e-3448c428acad

I usually find myself lowering the brightness or saturation in some areas to create a higher contrast with the map features. 

Hope that helps...

**Comment by jjiglesiasg** [comment]
Thanks, unaware of that feature. Sorry

**Comment by jjiglesiasg** [comment]
Much better. Age (and OSM Mapping) is taking a toll on my view.

![Screenshot (104)](https://github.com/facebook/Rapid/assets/22849578/2525c7f0-8ba2-448a-988b-193e1f5ba110)
