### ISSUE TITLE
Assist datasets are not loading

### ISSUE THREAD

**Issue by aronkvh** [facebook/Rapid#1152]
### Description

The AI datasets aren't loading in my editor. They are enabled, but no elements show on the map in any region.

### Version

2.1.1

### What browser are you seeing the problem on? What version are you running?

Firefox 118.0.2 (64-bit)

### The OS you're using

KDE Neon, Linux 6.2.0-32-generic

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w441882479&map=17.36/12.00345/8.52626

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0

**Comment by Bonkles** [comment]
@aronkvh is this still happening to you? It's possible that this lined up with a slowdown in the OSM servers, or a momentary hiccup on our end. I was just able to load AI datasets for Meta roads and MS Buildings over Rapid City, SD.
