### ISSUE TITLE
Combo box displaying raw text instead of html

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#1161]
This is a regression from #1124 - we should leave the combobox content displaying html, as we do use <span> content in there quite often. 

Screenshot: 
![image](https://github.com/facebook/Rapid/assets/1887955/4a89ff23-5273-4046-abd8-9044620b9e00)

**Comment by Bonkles** [comment]
@RitaDee please comment and acknowledge here! then I can assign you. :) We need to unwind a small bit of the work you did.  Bryan noticed that the combobox rendering pure text is an issue, as there ARE places in the code where we need to actually render html in the combobox.

**Comment by RitaDee** [comment]
I acknowledged being assigned to make the necessary changes.

**Comment by Bonkles** [comment]
@bhousel can you share your repro steps for getting this <span> info in the combo boxes?

**Comment by bhousel** [comment]
> @bhousel can you share your repro steps for getting this info in the combo boxes?

All the combo boxes seem to do it?

**Comment by RitaDee** [comment]
> > @bhousel can you share your repro steps for getting this info in the combo boxes?
> 
> All the combo boxes seem to do it?

How do I reproduce this on my end?

**Comment by bhousel** [comment]
> How do I reproduce this on my end?

* `git pull origin` to get latest code
* `npm run start`
* Open http://127.0.0.1:8080/ in a browser
* Find something on the map and click on it to select it
* In the sidebar, click on any combo box field - these are used for when there are a list of options (surfaces, tree types, building type, crosswalk type, etc).. They are used pretty frequently.   The "Add field" combo is broken too.

**Comment by RitaDee** [comment]
> > How do I reproduce this on my end?
> 
> * `git pull origin` to get latest code
> * `npm run start`
> * Open http://127.0.0.1:8080/ in a browser
> * Find something on the map and click on it to select it
> * In the sidebar, click on any combo box field - these are used for when there are a list of options (surfaces, tree types, building type, crosswalk type, etc).. They are used pretty frequently.   The "Add field" combo is broken too.

Thanks for this.
