### ISSUE TITLE
Pull Requests should run deployments and link to those deployments right in the PR actions

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#1163]
As this is an open source Repo mostly worked on by Meta employees, we don't have great tooling around our ability to ingest and test pull requests from the broader community. 

@RitaDee proposes to have our PRs build and deploy to AWS and surface the PR's code running from within our test environment- this would remove the need for maintainers (such as me!) to load the code in their local repo and test it manually.

**Comment by Bonkles** [comment]
@RitaDee - can you please link the example pages that you showed me of other OSS Repos with this functionality? Thanks!

**Comment by tordans** [comment]
@Bonkles you mean like here, where the GH Action comments on the PR with the link to the preview? https://github.com/openstreetmap/id-tagging-schema/pull/1026#issuecomment-1753633456

FYI, [the GH Action](https://github.com/openstreetmap/id-tagging-schema/tree/main/.github/workflows) has some special code to delete some stuff that is left over after the build which apparently takes up Github action space or minutes and one can safe time?/space? by removing it: https://github.com/openstreetmap/id-tagging-schema/blob/main/.github/workflows/deploy-preview.yml#L87-L107 I did not quite get what it was about in detail, but it might be worth optimizing as well.

**Comment by bhousel** [comment]
This shouldn't have been closed by #1166

**Comment by bhousel** [comment]
done in #1231
