### ISSUE TITLE
Restore WAY OVER WATERWAY warnings, whatsoever Permanent or Intermittent the waterway

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#1171]
### Description

Ways over Waterways (Fords) are a HAZARD, and should be properly identified and mapped. ID shows this hazards and Renders depict and issued a warning about them.

Rapid is NOT currently warning about the Way over Waterway; just Permanent, not for Interminent, Seasonal or Tidal water courses or bodies.

Is a hazard and mappers are NOT being warned about this condition, neither placed manually or atomatically the Fords.

**Comment by bhousel** [comment]
yeah this came up in #1059 too
In #1018 you asked us to remove the warnings when intermittent waterways were involved.

We can restore the warnings, but please try to be more clear when reporting issues.
