### ISSUE TITLE
Change color of Custom Data

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#1172]
### Description

Customer Data uploaded from databases or other files is currently depicted as a Light Blue color. Please consider using another color NOT STANDARD for the actual depiction of existing data (Blue color is the same of waterways).

Also consider INCREASING the Zoom level (Eye Altitude) that Customer data could be seen, in particular if the data are depicted as Nodes.

**Comment by bhousel** [comment]
Changing the color of the custom data is #1082, and someone is already working on it in #1168
