### ISSUE TITLE
Expand Contributing.md to include steps for making OS contributions

### ISSUE THREAD

**Issue by voscarmv** [facebook/Rapid#1179]
### Description

I'd like to include the following things on Contributing.md to make it easier for newcomers to participate:

1. Howto install and run Rapid in a local environment
2. A glossary of terms for the dir names of the code.
3. A quick and easy debugging guide.
4. Maybe a tiny example of how to fiddle with the UI.

Should probably have a draft tomorrow.

**Comment by voscarmv** [comment]
I got this

**Comment by bhousel** [comment]
This was done in #1181!
