### ISSUE TITLE
New Feature: Color System

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#1187]
### Description

This feature covers the implementation of a new file, `ColorSystem.js`, within Rapid. 

As covered before, the 'System' concept in rapid is for classes that provide core functionality. This system's function is to provide the color scheme for the map. 

For now, we will focus on not providing any actual changes to how rapid looks or behaves- we'll just be making modifications to *prepare* for future cool features, like the ability to swap color schemes on the fly. 

Checklist of functionality to implement: 

- [x] Create the skeleton of a class, called `ColorSystem`, in a new file inside the `modules/core` directory. 
   - It will need a constructor that takes the `Context` object as a parameter.  (See some of the other systems files for examples). 
   - it will need to extend the the `AbstractSystem` base class. 
 - [x] `ColorSystem` will need to have a dependency on the DataLoader system _(hint: see other System constructors in the core folder)_. 
 - [x] `ColorSystem` will need to be depended upon by the MapSystem, as the map shouldn't be able to draw anything without colors _(same as previous hint: see other systems)_. 
- [x] Create a new file in the `data` directory, called `colors.json`, which should contain a colors object (see below). 
- [x] The DataLoader system should be modified to load the color information from the colors.json file. 
- [x] The `ColorSystem` class should load the colors information during `startupAsync()` from the now-modified DataLoader system.
- [x] The `core/index.js` file will need to be updated to include references to the new ColorSystem. It needs to be imported, re-exported, and added to the `Systems.available` set.  
- [x] The `ColorSystem` will need to have its initAsync method called from inside the `Context.js` initAsync() method.  
- [x] The class will need to have one method, getColorScheme(), which returns a static object full of 'color' information to the `styles.js` file. 
 - [x] Finally, the `modules/pixi/styles.js` file will need to stop using its built-in color information and start using the colors from the new ColorSystem instead. 
 
color.json contents:  
```
{
    red: {
      fill: { color: 0xe06e5f, alpha: 0.3 }   // rgb(224, 110, 95)
    },
    green: {
      fill: { color: 0x8cd05f, alpha: 0.3 }   // rgb(140, 208, 95)
    },
    blue: {
      fill: { color: 0x77d4de, alpha: 0.3 }   // rgb(119, 211, 222)
    },
    yellow: {
      fill: { color: 0xffff94, alpha: 0.25 }  // rgb(255, 255, 148)
    },
    gold: {
      fill: { color: 0xc4be19, alpha: 0.3 }   // rgb(196, 189, 25)
    },
    orange: {
      fill: { color: 0xd6881a, alpha: 0.3 }   // rgb(214, 136, 26)
    },
    pink: {
      fill: { color: 0xe3a4f5, alpha: 0.3 }   // rgb(228, 164, 245)
    },
    teal: {
      fill: { color: 0x99e1aa, alpha: 0.3 }   // rgb(153, 225, 170)
    },
    lightgreen: {
      fill: { color: 0xbee83f, alpha: 0.3 }   // rgb(191, 232, 63)
    },
    tan: {
      fill: { color: 0xf5dcba, alpha: 0.3 }   // rgb(245, 220, 186)
    },
    darkgray: {
      fill: { color: 0x8c8c8c, alpha: 0.5 }   // rgb(140, 140, 140)
    },
    lightgray: {
      fill: { color: 0xaaaaaa, alpha: 0.3 }   // rgb(170, 170, 170)
    }
 }
```
  
As you complete this task, please link an associated draft PR with your progress, checking boxes with what you believe is currently implemented. This will give me some better context into how 'done' the PR is! This will be a long task but can be implemented in stages, a little bit at a time, for incremental progress. 

Please hit me up with any questions!

Javascript things that may be useful for this task: 
**JSON format**  (see the other .json files in the `data` directory for examples)
**Classes** 
**Promises** (for implementing the the `initAsync` and `startAsync` methods in the class)

Finally, as a reference, you may take a look at some of the code-splitting work I did to separate ALL the colors out from the styles.js file into two files: styles.js and colors.js. It is in this branch: 

https://github.com/facebook/Rapid/tree/colors

**Comment by Bonkles** [comment]
@lauble here you are! This exercise will be a little more structured than the last one, and you have quite a bit of latitude in how you fulfill some of these tasks.  If you're not sure where to start, I'd start with the modifications to the DataLoader system and see if you can extend it to load the colors information from the .json.

**Comment by lauble** [comment]
Awesome, thank you @Bonkles for the guidance and details! I'll get started ASAP 😄. Excited to contribute to this.
