### ISSUE TITLE
Feature Request: New crossing presets for the top 8 pedestrian crossing markings

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#1197]
### Description

This issue is to support @RitaDee in the issue she's working on (#1154). Currently in the id-tagging-schema we have only three crosswalk presets- unmarked, marked, and marked(zebra).  The marked(zebra) preset also has incorrect tagging: instead of `crossing:marking=zebra` it has `crossing=zebra`. 

I will submit a PR to the id-tagging-schema with this same proposed scheme: 

**Existing presets:** 
Unmarked: crossing=unmarked;crossing:markings=no
Marked: crossing=marked:crossing:markings=yes

**Existing preset but with incorrect crossing:marking:** 
Marked-Zebra: crossing=marked;crossing:markings=zebra

**New presets according to global tag popularity overrall:**
Marked-Lines: crossing=marked;crossing:markings=lines
Marked-Ladder: crossing=marked;crossing:markings=ladder
Marked-Dashes: crossing=marked;crossing:markings=dashes
Marked-Dots: crossing=marked;crossing:markings=dots
Marked-LadderSkewed: crossing=marked;crossing:markings=ladder:skewed

So, the idea here is that we have the ability to select which type of markings we want for a marked crosswalk, and to have those presets available for the hotkey to cycle.

**Comment by Bonkles** [comment]
Using the new overrides I can now get: 

![image](https://github.com/facebook/Rapid/assets/1887955/9dd8ab7a-b45a-495f-bd61-bb4c06b40ef8)

Preset strings: 
```
highway/footway/crossing/zebra
highway/footway/crossing/lines
highway/footway/crossing/ladder
highway/footway/crossing/dashes
highway/footway/crossing/dots
highway/footway/crossing/ladder:skewed
```

**Comment by bhousel** [comment]
This is awesome!   I love that we're using the new [`crossing:markings` tags](https://wiki.openstreetmap.org/wiki/Key:crossing:markings) that were approved last year 👍
