### ISSUE TITLE
Conflation in boston doesn't look like it is working

### ISSUE THREAD

**Issue by atiannicelli** [facebook/Rapid#1200]
### Description

Rapid buildings are being suggested ontop of already created buildings in Boston.

### Screenshots

![Screenshot 2023-11-02 at 1 42 23 PM](https://github.com/facebook/Rapid/assets/5851115/12dd6495-3c88-45d1-863a-e11020c35a05)

https://rapideditor.org/rapid#background=MassGIS_2021_Aerial&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w845711633&map=20.17/42.37451/-71.10560

### Version

2.1.1

### What browser are you seeing the problem on? What version are you running?

Chrome v119.0

### The OS you're using

mac

### Steps to reproduce

Go to the link I pasted above and see that rapid buildings are being displayed even where buildings already exist

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid#background=MassGIS_2021_Aerial&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w845711633&map=20.17/42.37451/-71.10560

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

**Comment by bhousel** [comment]
It does seem to be working now, so I'm going to close this issue..
We also have #602 , which would provide a way to let the user when conflation isn't working.  
(I don't know what could cause it - maybe our service being unable to talk to OSM?)
