### ISSUE TITLE
Microsoft Buildings license data url

### ISSUE THREAD

**Issue by Martinligabue** [facebook/Rapid#1201]
### Description

Microsoft did this commit: https://github.com/microsoft/USBuildingFootprints/commit/5fcad22be825f4dd04beb53c2ee7de6d6b79a01f

now the url in the Microsoft Buildings license is broken, and should be updated

### Version

2.1.1

### The OS you're using

Linux (Arch)

### Steps to reproduce

1. Open rapid
2. Open datasets
3. Click license of microsoft

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit

**Comment by SoNick** [comment]
Definitely seeing the same thing here. Tested in Chrome, Firefox, and Edge all on Win10 64-bit.
