### ISSUE TITLE
Can't edit in Rapid from MapRoulette

### ISSUE THREAD

**Issue by gyCfjSnO** [facebook/Rapid#1203]
### Description

Can't edit in Rapid from MapRoulette, this is the error I get.

```
Your connection isn't private
Attackers might be trying to steal your information from mapwith.ai (for example, passwords, messages or credit cards).
NET::ERR_CERT_DATE_INVALID
```

### Screenshots

![Recording 2023-11-05 181213](https://github.com/facebook/Rapid/assets/49738152/404d72d0-de16-4539-adb0-e51d89234d45)

### Version

2.1.1

### Steps to reproduce

Go to https://maproulette.org/ and pick a challenge
On the task page change Current Editor to Edit in RapiD
Click Edit
New window will open with the error message

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid#id=w905767344&comment=Fixed%20building%20%26%20highway%20intersections%20%23maproulette%20https://maproulette.org/browse/challenges/40063&source=&background=EsriWorldImagery&map=19/-35.305809787719824/149.10517662763598

**Comment by arch0345** [comment]
It looks like MapRoulette hasn't updated the URL for Rapid. I've opened a PR to fix this

**Comment by Bonkles** [comment]
This was due to a bad site cert- since the cert expired, our redirect to rapideditor.org wasn't working. Should be fixed now!
