### ISSUE TITLE
Disable matchers that run on PRs and raise warnings about unchanged files

### ISSUE THREAD

**Issue by bhousel** [facebook/Rapid#1208]
The "Files Changed" tab on every GitHub PR is now showing eslint warnings about files _not_ changed, and this is annoying.

There are quite a lot of TODOs and this this distracts from being able to see only what the PR changed.

<img width="500" alt="Screenshot 2023-11-08 at 10 34 16 AM" src="https://github.com/facebook/Rapid/assets/38784/d5c5c7eb-53b5-4b52-88b9-477c4586e210">

**Comment by Bonkles** [comment]
Gosh yes- this bit is super infuriating.

**Comment by bhousel** [comment]
I think I might have disabled the eslint matchers by using the trick here:
https://dev.to/sibiraj/disable-annotations-in-github-actions-2ih2
