### ISSUE TITLE
Cursor not changing to pointer when hovering on rapideditor.org social icons

### ISSUE THREAD

**Issue by Kiran1689** [facebook/Rapid#1215]
### Description

I observed that the cursor doesn't change to a pointer when hovering over the Twitter and Facebook icons in the footer of the [Rapid Editor website](https://rapideditor.org/). The GitHub icon behaves as expected.

### Version

2.1

### What browser are you seeing the problem on? What version are you running?

Chrome v119

### The OS you're using

Win10

### Steps to reproduce

1. Visit the [Rapid Editor website](https://rapideditor.org/)
2. Scroll down to bottom of the page.
3. Attempt to hover on the Twitter and Facebook icons.

### The browser URL at the time you encountered the bug

https://rapideditor.org/

**Comment by pravee42** [comment]
Can i fix this issue @bhousel

**Comment by Kiran1689** [comment]
Hey @pravee42 
The https://rapideditor.org/ page is not on GitHub.

**Comment by pravee42** [comment]
> Hey @pravee42 The https://rapideditor.org/ page is not on GitHub.

Fine, I thought of  fixing this issue

**Comment by Bonkles** [comment]
Fixed as of right.... now.
