### ISSUE TITLE
Cursor image not found 

### ISSUE THREAD

**Issue by tannerwuster** [facebook/Rapid#1225]
### Description

I added cursor hover styling from Rapid V1 to V2 and the console is showing that the cursor images cannot be found (404). The cursor styling doesn't change as well.

### Screenshots

![Screenshot 2023-11-17 at 11 43 03](https://github.com/facebook/Rapid/assets/49957271/b5325757-aca2-4d70-904a-6a63f5cfd32b)

### Version

2.2

### What browser are you seeing the problem on? What version are you running?

Chrome v119

### Steps to reproduce

Hover over a map feature and the cursor no long changes and the console logs a 404 (Not Found) 

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid-test#background=Bing&datasets=fbRoads,msBuildings,rapid_intro_graph&disable_features=boundaries&map=20.00/39.06525/-108.50385

**Comment by bhousel** [comment]
This wouldn't work on `rapideditor.org` yet?

**Comment by tannerwuster** [comment]
> This wouldn't work on `rapideditor.org` yet? or at least it would need to be under a path like `/rapid` or `/rapid-test` or something

Sorry I put the wrong URL in but it's updated. It should be `/rapid-test`

**Comment by bhousel** [comment]
cool I'll check the deploy scripts, maybe we are missing the assets
