### ISSUE TITLE
Walkthrough Split Way zooms to different part of map

### ISSUE THREAD

**Issue by tannerwuster** [facebook/Rapid#1226]
### Description

When going through the Walkthrough on the `Lines` section when you go to split a way and it zooms to a different part of the map. I then have to zoom out and pan over to the way it's asking me to split

### Screenshots

![Screenshot 2023-11-17 at 12 05 35](https://github.com/facebook/Rapid/assets/49957271/619cee2a-cb54-45b1-a7e2-d10fbc34fdc8)

### Version

2.2

### What browser are you seeing the problem on? What version are you running?

Chrome v119

### The OS you're using

MacOS 14.1.1

### Steps to reproduce

1. Start the Walkthrough in the help menu
2. Click `Lines` at the bottom 
3. Go through steps until it tells you to `split` a way

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid-test#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=2.00/0.5/6.4

**Comment by bhousel** [comment]
Thanks @tannerwuster can you check this again in https://rapideditor.org/canary ?
I'm not able to get it to happen now, and I was able to make it all the way through the walkthrough without issue, but I did fix a handful of other walkthrough issues that might have caused something like this.

**Comment by tannerwuster** [comment]
> Thanks @tannerwuster can you check this again in https://rapideditor.org/canary ? I'm not able to get it to happen now, and I was able to make it all the way through the walkthrough without issue, but I did fix a handful of other walkthrough issues that might have caused something like this.

Just went through the walkthrough and everything seems to be working properly! I will close this issue
