### ISSUE TITLE
Stamen Terrain basemaps broken

### ISSUE THREAD

**Issue by ianthetechie** [facebook/Rapid#1241]
### Description

Title says it all.  Per the [announcement from Stamen](https://maps.stamen.com/stadia-partnership/), the old Fastly CDN URLs have been shut off for a bit. We have a [migration guide](https://docs.stadiamaps.com/guides/migrating-from-stamen-map-tiles/) that covers the necessary steps to get this back up and running.

TL;DR steps:
1. Change the URL pattern to something like `https://tiles.stadiamaps.com/tiles/stamen_terrain_background/{z}/{x}/{y}{r}.png` (note that these tiles have ben updated and support retina/hidpi now!)
2. Update attribution / license information as noted (Stamen, Stadia Maps, and OpenMapTiles need attribution + links now).

As this is an OSM community public service project, **we can sponsor the usage**. No need for anyone at Meta to create an account; we'll get the rapideditor.org domain  into our system sometime next week.

I am also happy to open a PR to do the implementation if you'd like.

### Screenshots

<img width="3076" alt="image" src="https://github.com/facebook/Rapid/assets/2140440/7b6eea80-6302-49fa-9c8d-74c4ba35fdda">

### Version

2.1.1

### What browser are you seeing the problem on? What version are you running?

Brave 1.60.118

### The OS you're using

macOS 14.1.1

### Steps to reproduce

1. Open the editor
2. Select "Stamen Terrain" from the background tab

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=stamen-terrain-background&datasets=fbRoads,msBuildings&disable_features=boundaries&map=19.00/37.56595/126.97522

**Comment by Bonkles** [comment]
Hey @ianthetechie - we use the editor-layer-index project to build our imagery sources- so instead of making the change here in Rapid, you can make it there and we'll pick the change up whenever the index gets rebuilt.

I believe the file in question is https://raw.githubusercontent.com/osmlab/editor-layer-index/e66a8077d3ace8a6dcdbd9060db4f5199d74e95f/sources/world/StamenTerrainBackground.geojson - unsure if there are others that need modifying

**Comment by bhousel** [comment]
Thanks @ianthetechie for the heads up!  🙌 
I fixed the Stamen Terrain Background layer by adding these lines to `manual_imagery.json` - this overrides the imagery that we are pulling from Editor Layer Index with the updated URL and Attribution.

https://github.com/facebook/Rapid/blob/f6b58ab998805a560eea343acd2c53fb34936aeb/data/manual_imagery.json#L50-L63
