### ISSUE TITLE
Change color of Custom Uploaded Data

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#1262]
### Description

Currently all Custom Uploaded data is depicted in Light Blue Color, which is an existing color in the map (Waterways) Please change that color to another color NOT NATURAL for mapped or existing elements.

There is plenty of colors for that, in ID is Magenta, perhaps another, but any that AVOID confusion with existing standard ones.

**Comment by bhousel** [comment]
dup of #1082 / #1172
