### ISSUE TITLE
Twitter logo needs to be updated

### ISSUE THREAD

**Issue by amanr-dev** [facebook/Rapid#1263]
The logo of Twitter on the website's footer needs to be updated.

**Comment by bhousel** [comment]
Agree , this should go with #1215 whenever we update the rapideditor.org site

**Comment by amanr-dev** [comment]
Can i work on it

**Comment by amanr-dev** [comment]
Ok

**Comment by bhousel** [comment]
Hey @Bonkles can you update the Framer site?  I don't know how to do it.
There are a handful of issues tagged with <sub> <sub> [![rapideditor.org](https://labl.es/svg?text=rapideditor.org&bgcolor=cc11aa)]( https://github.com/facebook/Rapid/issues?q=is%3Aopen+is%3Aissue+label%3Arapideditor.org) </sub> </sub> that could be closed pretty quickly I think.

**Comment by Bonkles** [comment]
Boy oh boy we waited a while for the Phosphor icon bundle to update but it still hasn't. I just made a custom logo and replaced it manually- seems to work/look okay.
