### ISSUE TITLE
No surface tag option for  unmarked crossings

### ISSUE THREAD

**Issue by SeanWhitcomb** [facebook/Rapid#1269]
### Description

Previous releases allowed users to choose a surface type from a dropdown when editing `crossing=unmarked`. That option is gone now, so surfaces have to be added manually

### Screenshots

![image](https://github.com/facebook/Rapid/assets/91229709/0f8ecc00-9812-43d4-84d2-70a3eb710b9b)

### Version

2.2.1

### What browser are you seeing the problem on? What version are you running?

Firefox v121.0

### The OS you're using

win

### Steps to reproduce

Add or edit an unmarked crossing. Look at the "Edit feature" panel.

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit?#background=Mapbox&datasets=fbRoads,msBuildings&disable_features=boundaries&gpx=https://mwai-tasking-manager-production-api.mapwith.ai/api/v2/projects/157/tasks/queries/gpx/%3Ftasks%3D328&id=w-7&map=20.85/33.40111/-111.93467

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0

**Comment by bhousel** [comment]
I could add this back if people really want it.. 

In the v2.2.x update I moved it to the "Add field" menu because usually the `surface` at the crossing wouldn't be tagged any differently from the parent road (especially for unmarked crossings, like displayed in the screenshot), so it seems kind of redundant to display a main field for it.

**Comment by SeanWhitcomb** [comment]
I see why you did that now. But in this case, the crossing is a way that connects sidewalks, not just a node, like you see here. To me, it makes sense to tag the surface of this kind crossing ways since only the node in the center of the way is directly connected to the road. I don't know if this is the right way to think about this situation, but it makes conceptual sense to me. 
![image](https://github.com/facebook/Rapid/assets/91229709/22858b9c-9139-40b1-a87d-d19bee404b1f)

**Comment by bhousel** [comment]
> But in this case, the crossing is a way that connects sidewalks, not just a node, like you see here. To me, it makes sense to tag the surface of crossing ways... 

Ah yeah this makes sense to me - If the sidewalk ways have a surface field, the crossing ways probably should too. 👍
