### ISSUE TITLE
AI suggested data disappear, once an adjacent but not connected AI data is selected.

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#1287]
### Description

If you have a suggested road and you choose that to become residential road, adjacent AI suggested data not selected also disappear once the first becomes editable data.

https://rapideditor.org/rapid#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=16.36/-16.98111/-65.35974&poweruser=true

### Screenshots

![Screenshot (143)](https://github.com/facebook/Rapid/assets/22849578/a173b8b0-96d0-4f3b-8cc8-3a8f38797c24)
![Screenshot (142)](https://github.com/facebook/Rapid/assets/22849578/f6060c3c-b28d-46e6-95ed-2db55284d984)
![Screenshot (141)](https://github.com/facebook/Rapid/assets/22849578/294892a9-096a-43e9-84cb-aa58a9a056bd)

### Version

2.2.2.

### What browser are you seeing the problem on? What version are you running?

EDGE Version 120.0.2210.91 (Official build) (64-bit)

### The OS you're using

Win10

### Steps to reproduce

Choose any given Road suggested data and the adjacent one disappear once the AI data becomes editable. Refer to the screenshots attached.

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=16.36/-16.98111/-65.35974&poweruser=true

**Comment by bhousel** [comment]
Thansks @jjiglesiasg for reporting - it looks like this issue and #1288 were added within minutes of each other, and are duplicates.. I'll keep #1288 because it occurs in a part of the map with more way splits, and its untouched so it is a lot easier to reproduce the issue around there.
