### ISSUE TITLE
Twitter link on homepage 404

### ISSUE THREAD

**Issue by jidanni** [facebook/Rapid#1293]
On https://rapideditor.org/#footer there is a link to
https://twitter.com/MapWithAI
but that destination doesn't exist.

**Comment by bhousel** [comment]
Thanks for flagging - we should fix this along with #1263

**Comment by jidanni** [comment]
You are welcome.
Note I do not get notified of your responses due to https://github.com/orgs/community/discussions/81772 .

**Comment by Bonkles** [comment]
Fixed! Link now redirects back to https://x.com/MapWithRapid
