### ISSUE TITLE
All Water Bodies: BLUE not GREY

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#1296]
### Description

It is an Standard De Facto since hundreds of years that water bodies (all kind) in the maps are represented by BLUE color, whatsoever they are permanent or intermittent. Now areas of water are being represented in GREY color, this color in some cases DO NOT allow to properly distinguish some water bodies like basins, or river areas.
Please change the color to Blue (Different shades or patterns if you may wish)

Thanks

**Comment by bhousel** [comment]
Can you share a screenshot and map location of where you are seeing this? 

Grey is sometimes used if Rapid doesn’t recognize the OSM tags on the feature.

**Comment by jjiglesiasg** [comment]
![Screenshot (147)](https://github.com/facebook/Rapid/assets/22849578/442e340a-6bfc-4ae8-9f3e-ef393aa26691)
  In this screenshot there are 7 water bodies, just 1 is evident.

**Comment by jjiglesiasg** [comment]
![Screenshot (148)](https://github.com/facebook/Rapid/assets/22849578/bf69cf49-1957-44c2-a703-0e40464de179)
 Try to guess how many water bodies are in this image, apart of the 4 notorious ones?

**Comment by jjiglesiasg** [comment]
Tags: natural=water + water=basin + intermittent=yes are standard tagging in OSM
![Screenshot (149)](https://github.com/facebook/Rapid/assets/22849578/13e81905-5f91-4fbf-ae64-99c9aca45162)
Same place in ID

**Comment by bhousel** [comment]
I agree - those basins are the wrong color.  The `intermittent` tag is throwing off the style matching somehow.

https://rapideditor.org/canary#background=Bing&map=18.27/-18.22472/-65.17398&poweruser=true

**Comment by jjiglesiasg** [comment]
Thanks
