### ISSUE TITLE
Does Rapid's .map() trigger moveend events?

### ISSUE THREAD

**Issue by Zaczero** [facebook/Rapid#1297]
### Description

Currently I use "move.embed" alongside a throttle method to capture map position updates as user pans around the map. However, for simplicity and consistency I would like to use event like "moveend.embed" to receive updates only on panning end. Is there such an event available? I tried to search the code for various keywords with no luck.

```js
    const ctx = context
        .embed(true)
        .assetPath(`static/${version}/`)
        .locale(primaryLanguage)
        .containerNode(idContainer)
        .init()

    const map = ctx.map()

    // On map move, send the new state to the parent
    // TODO: isn't there moveend event?
    map.addEventListener(
        "move.embed",
        throttle(() => {
            // Skip if in intro
            if (ctx.inIntro()) return

            const [lon, lat] = map.center()
            const zoom = Math.floor(map.zoom())
            parent.postMessage({ type: "mapState", state: { lon, lat, zoom } }, "*")
        }, 250),
    )
```

**Comment by Zaczero** [comment]
A big, big thank you. I couldn't dream of a better response :star_struck:.

**Comment by bhousel** [comment]
> A big, big thank you. I couldn't dream of a better response

You're welcome!  I'm also happy to help out.  If I get some time freed up, I might just send a PR to https://github.com/Zaczero/openstreetmap-ng if that helps.

**Comment by Zaczero** [comment]
I appreciate that! It will be best to do so after I prepare contributor documentation and finalize the base code. I will note to send you a nudge when that happens. I want to have a running project before other people can contribute to it. A test server will also be launched for the public access. A few things must happen before that:

- Finish JavaScript migration, so code left [here](https://github.com/Zaczero/openstreetmap-ng/tree/main/app/static/js/old) (not that much!)
- Migrate enough HTML templates to make the website usable
- Prepare the contributor documentation: a GitHub-hosted wiki
