### ISSUE TITLE
Country request: North Korea (DPRK)

### ISSUE THREAD

**Issue by MRVDH** [facebook/RapiD#130]
I would like to use RapiD for my project: https://github.com/MRVDH/mapping-north-korea (https://mappingnorthkorea.com)

I'm aware of issue #58 with Iran, but I doubt this also applies to North Korea, since they have different sanctions. If it does apply then this issue can be kept for tracking.

**Comment by jeffdefacto** [comment]
Yeah unfortunately, the same sorts of restrictions apply with North Korea, but we can definitely keep this open for tracking.

If it's ever possible to support the country we certainly will.

**Comment by fnordson** [comment]
After the collaboration between Facebook and ESRI, RapiD seems to work in NK now: 

https://mapwith.ai/rapid-esri#background=Maxar-Premium&disable_features=boundaries&map=16.34/36.60490/128.28171

**Comment by Artoria2e5** [comment]
In the absence of Facebook data, I recommended looking at alternative tools for tracing imagery.

The MIT has a CNN-based tool from 2018, and you might be able to run it: https://roadmaps.csail.mit.edu/roadtracer/. You will of course than need your own server storing the predicted roads, and your own fork of RapiD to fetch that data. (Hmm, checking on https://roadmaps.csail.mit.edu/ they seem to have their own version of iD too.)
