### ISSUE TITLE
Bing Streetside data not showing

### ISSUE THREAD

**Issue by elevenchars** [facebook/Rapid#1305]
### Description

Streetside bubbles are not showing in Rapid.

### Screenshots

![image](https://github.com/facebook/Rapid/assets/11055681/a3a9856e-c8bf-4c94-9a33-28ded728622b)

### Version

2.2.4

### What browser are you seeing the problem on? What version are you running?

Firefox 121.0.1

### The OS you're using

Fedora 39 Linux

### Steps to reproduce

1. Open Rapid in an area where Streetside data should be visible
2. Enable "Bing Streetside" in map data tab
3. Observe that nothing loads

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=17.88/30.30711/-97.68157&photo_overlay=streetside

**Comment by elevenchars** [comment]
See https://github.com/openstreetmap/iD/issues/10074

**Comment by dankarran** [comment]
I'm seeing the same issue (with Safari on Mac), with 401 errors being reported in the console when trying to enable the Streetside layer.

**Comment by bhousel** [comment]
Thanks @dankarran !
I saw your PR here https://github.com/openstreetmap/iD/pull/10100 and tried it out and looks like it's working great.
I pulled it into Rapid just now, and I'll release a patch that includes the fix  👍 

It's great to see the Bing Streetside working again!
 
<img width="1111" alt="Screenshot 2024-02-09 at 3 37 58 PM" src="https://github.com/facebook/Rapid/assets/38784/91489cb6-642b-4f89-b999-b32bb3e189eb">

**Comment by dankarran** [comment]
Glad to help, and hopefully it's the right fix! I did also email osm@microsoft.com today so they were aware of this issue.

I don't suppose you have commit privileges on the main iD editor as well, do you? Not having reliable access to Streetside is surprisingly frustrating.

**Comment by bhousel** [comment]
> I don't suppose you have commit privileges on the main iD editor as well, do you?

I'm not sure!  My maintainer access to iD was taken away in 2020.  If you have issues with the iD project you'll need to raise them with the OSMF, it's their project now.  🤷‍♂️

**Comment by dankarran** [comment]
> I'm not sure! My maintainer access to iD was taken away in 2020. If you have issues with the iD project you'll need to raise them with the OSMF, it's their project now. 🤷‍♂️

Ok no worries, I’ll see if the PR gets any traction there. 

Microsoft replied to say they were root-causing the issue, so maybe they’ll fix the issue at their end in the meantime.
