### ISSUE TITLE
One-way ways don't draw directional arrows on the whole way

### ISSUE THREAD

**Issue by mxxcon** [facebook/Rapid#1310]
### Description

I've been noticing this for a while now that randomly some `oneway=yes` ways don't have directional arrows on the whole ways, only part of them.
However, if I zoom out a bit, they appear. Zoom back in, they disappear.

### Screenshots

![image](https://github.com/facebook/Rapid/assets/847140/197bc1be-4d58-4196-bdc3-ac5d2c49fed1)
![image](https://github.com/facebook/Rapid/assets/847140/82f3bd4b-4153-4470-ad00-fae25bdbc4d2)
![image](https://github.com/facebook/Rapid/assets/847140/2aa66ee9-9a78-4ddb-8788-34bd2ae2545f)

### Version

2.2.4

### What browser are you seeing the problem on? What version are you running?

Chrome v122.0

### The OS you're using

win

### Steps to reproduce

Just look at one-way street and zoom in/out.

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit?#background=EsriWorldImagery&datasets=fbRoads,msBuildings&disable_features=buildings,boundaries&gpx=https://mwai-tasking-manager-production-api.mapwith.ai/api/v2/projects/149/tasks/queries/gpx/%3Ftasks%3D200&map=20.73/40.59938/-73.97088

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

**Comment by bhousel** [comment]
oh , I think this is #544 
The issue there is that for high zooms / long ways, it can result in a mathematically ridiculous number of arrows, so we added a temporary hack to limit them.  

We can fix the issue by splitting apart the code that calculates where they belong (this part is relatively fast math and can even be done in spare time) from the code that actually adds them to the scene only if they are visible (this part is what will fix the performance issue).
