### ISSUE TITLE
When highlighting a relation, apply the highlighting to its members

### ISSUE THREAD

**Issue by emersonveenstra** [facebook/Rapid#1314]
### Description

When editing an object that is part of a relation, in iD you can hover over the relation box in the side panel and it will highlight the visible members of the relation. In Rapid hovering over it doesn't do anything. I know you can click the zoom button to zoom out and see the whole relation, and edit the relation directly to see all the members, but that isn't really helpful on relations that span entire states.

iD:

https://github.com/facebook/Rapid/assets/5402360/69d6fc93-2aa6-4e13-b058-ec3974750b99

vs Rapid:

https://github.com/facebook/Rapid/assets/5402360/6e518cb3-2dec-4dfd-be2c-ef77c7f81d09

(https://www.openstreetmap.org/node/158191774 is the one in the videos)

**Comment by bhousel** [comment]
Thanks, I agree we should restore this 👍
