### ISSUE TITLE
Overzoom system generates unnecessary tile requests

### ISSUE THREAD

**Issue by emersonveenstra** [facebook/Rapid#1321]
### Description

When determining the zoom level in https://github.com/facebook/Rapid/blob/main/modules/pixi/PixiLayerBackgroundTiles.js#L160-L170, because `overzoom` is `true` by default, [`source.validZoom`](https://github.com/facebook/Rapid/blob/main/modules/core/lib/ImagerySource.js#L79) will always return `true` even if the max zoomExtent is lower than the requested level. This leads to Rapid always attempting to retrieve tiles at its current zoom level, even if the imagery provider does not provide tiles at that zoom (as specified with `zoomExtent`)

I know this isn't the biggest deal, but it just seems unnecessary to send tile requests for tiles that it knows doesn't exist. Adding ` || source.zoomExtent[1] < tryZoom` to the if statement on https://github.com/facebook/Rapid/blob/main/modules/pixi/PixiLayerBackgroundTiles.js#L169 fixes it for me.

### Version

2.2.4

### Steps to reproduce

1. Note that the zoomExtent for The National Map Topo is `[2,16]`
2. Go to https://rapideditor.org/edit#background=USGS-The-National-Map-Topo&datasets=fbRoads,msBuildings&disable_features=boundaries&map=20.38/40.98121/-85.02043
3. Open Devtools
4. See several 404 errors for tiles with zoom levels 20 through 17

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=USGS-The-National-Map-Topo&datasets=fbRoads,msBuildings&disable_features=boundaries&map=20.38/40.98121/-85.02043

**Comment by bhousel** [comment]
Thanks @emersonveenstra !  I can look into it..
I kind of thought that the `source.validZoom(z)` would already take the max zoom into account?

https://github.com/facebook/Rapid/blob/71aea3080c6ca7d52fa39618104e98428755e679/modules/core/lib/ImagerySource.js#L78-L80

I wonder if maybe `overzoom` is not being considered properly.

**Comment by bhousel** [comment]
Thanks again @emersonveenstra , I ended up just removing `overzoom` completely, since we weren't really using it and we shouldn't be trying to fetch tiles that don't exist.
