### ISSUE TITLE
Check new user user experience: onboarding flow, splash screen, first edit

### ISSUE THREAD

**Issue by bhousel** [facebook/Rapid#1325]
Since the rapid v2 release, we've been using the splash screen to highlight the new features in each minor release. 

This is ok, but it interrupts the "classic" new user flow where they are offered a better welcome screen and a chance to take the walkthrough tutorial.  We should make sure that first time users are still offered the old flow.

There's also another screen that needs a refresh:  the one where a not-logged-in user tries adding a Rapid feature, and is offered the choice of logging into OSM or clicking "I'm just exploring".

**Comment by HermanBide** [comment]
Can i contribute to this issue ?

**Comment by bhousel** [comment]
> Can i contribute to this issue ?

Maybe - our UI code is pretty unusual as it's evolved over a long time.  If you have familiarity with D3.js, that would be really helpful to understanding it.   Best path would be to get Rapid set up and running locally, and use it to edit OpenStreetMap a bit, then try to reproduce some of the the issues on our GitHub and step through the code and understand it.
