### ISSUE TITLE
SEC_ERROR_EXPIRED_CERTIFICATE

### ISSUE THREAD

**Issue by misibacsi** [facebook/Rapid#1333]
### Description

"Sorry, your browser is not currently supported."

Which means that today the rapideditor.org site certificate is expired.
Valid for one year.
Please update it. 
2024-02-14

### Version

2.2.5

### What browser are you seeing the problem on? What version are you running?

Firefox v122.0

### The OS you're using

win

### Steps to reproduce

Open a browser window.

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=FOMI_2007_2010&datasets=fbRoads,msBuildings&disable_features=landuse,pistes,aerialways,power,past_future&map=15.93/48.1845/20.2102

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0

**Comment by bhousel** [comment]
ugh #1202 again 😡

**Comment by bhousel** [comment]
Looks like the certs have been updated - if you are still seeing the cert error, please refresh your browser, thanks!
Also, thanks @Bonkles for the quick fix 👍

**Comment by Bonkles** [comment]
You're welcome for the quick fix, but it was my own inattention to some internal tasks that caused this to happen. We'll have a retrospective to see if we can't fix the problem so that this doesn't happen in the future.
