### ISSUE TITLE
Mapillary viewer link to viewed image

### ISSUE THREAD

**Issue by eneerhut** [facebook/Rapid#1337]
### Description

Mapillary's image viewer in Rapid used to have a link that would take you directly to the image on mapillary.com/app/. Now it takes you to Mapillary.com which is not really helpful. 

1. We should be able to show the username now as we completed a LAMA to allow this.
2. Can we have the link go directly to the viewed image?

Oscar has provided links to the relevant attribution code in the viewer.
> Here is a reference of how the MJS attribution works out of the box for reference https://mapillary.github.io/mapillary-js/examples/component-pointer

> There is a cutoff at 640px viewer width where we show the compact attribution.
> The attribution has two links: 
> Logo -> mapillary.com
> "images by ..." text -> mapillary.com/app?...<image_id>

![image](https://github.com/facebook/Rapid/assets/11349863/2a5e95c9-500c-42b7-9b7f-9249f59a5c90)

**Comment by 1ec5** [comment]
As a temporary workaround, you can copy the photo ID from the URL. For example, if the URL has `&photo=mapillary/790125865041194` in the hash, then https://www.mapillary.com/app/?pKey=790125865041194 takes me to the photo in Mapillary.
