### ISSUE TITLE
Rapid unresponsive after loading on Mac Safari

### ISSUE THREAD

**Issue by bos** [facebook/Rapid#1347]
### Description

I can't tell if this is due to underlying OSM API flakiness, but since yesterday, Rapid on macOS has been unresponsive after I load it about 4 times out of 5. It all renders, but doesn't respond to any inputs.

### Version

2.2.5

### What browser are you seeing the problem on? What version are you running?

Safari v17.3

### The OS you're using

mac

### Steps to reproduce

Simply loading the page leaves it stuck.

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=EsriWorldImagery&datasets=fbRoads,msBuildings&disable_features=landuse,boundaries,water,power,others&map=16.00/35.0815/-115.6305

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3 Safari/605.1.15

**Comment by tannerwuster** [comment]
Thanks for the report, @bos! I've been trying to reproduce this issue without any luck. Is this still happening on your end? I'm also on Safari Version 17.3.1

**Comment by eneerhut** [comment]
@bos I am also unable to reproduce and Rapid has been updated since you encountered this. Let's close for now, but feel free to re-open if you're still seeing issues.
