### ISSUE TITLE
No warning where sidewalk crosses service road without node

### ISSUE THREAD

**Issue by cbeddow** [facebook/Rapid#1349]
### Description

I drew a new sidewalk and it crosses a service road, but no warning was generated to suggest I should connect them with a node

### Version

2.2.5

### What browser are you seeing the problem on? What version are you running?

Chrome v122.0

### The OS you're using

win

### Steps to reproduce

Draw a new sidewalk on the map that crosses highway=service then check warnings

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit?#background=Mapbox&datasets=fbRoads,msBuildings&disable_features=buildings,boundaries,points&gpx=https://mwai-tasking-manager-production-api.mapwith.ai/api/v2/projects/166/tasks/queries/gpx/%3Ftasks%3D10&id=w1262951059&map=20.68/34.07665/-118.25879

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

**Comment by bhousel** [comment]
Hey @cbeddow  I just took a look..
That sidewalk is tagged with `layer=-1` , that's why it doesn't generate a warning.

<img width="368" alt="Screenshot 2024-04-17 at 4 07 28 PM" src="https://github.com/facebook/Rapid/assets/38784/9c61498a-5caa-40e4-b53b-b030af9451e9">
