### ISSUE TITLE
2 finger pinch/expand to zoom doesn't work in iOS Safari

### ISSUE THREAD

**Issue by emersonveenstra** [facebook/Rapid#1353]
### Description

On iPads, trying to zoom with 2 fingers pans the map instead of zooming. iD correctly zooms the map

### Version

2.2.5

### What browser are you seeing the problem on? What version are you running?

Safari 17.1

### The OS you're using

iPad OS 17.1

### Steps to reproduce

1. Go to Rapid
2. Pinch or expand with 2 fingers
3. Map pans instead of zooming

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=19.00/42.71980/-85.91276

**Comment by bhousel** [comment]
This is probably the same as #893 , but we can keep them both open until we've restore the better touch event behaviors and tested across different mobile browsers.
