### ISSUE TITLE
Unreachable Field in Rapid Editor Walkthrough

### ISSUE THREAD

**Issue by chinweibegbu** [facebook/Rapid#1364]
### Description

In the "Areas" section of the Rapid Editor walkthrough, a field the dialog box was pointing to was not within view on the screen

When the dialog box is visible during the walkthrough (see the first screenshot), the application cannot be interacted with. Because of this UI/UX state, the scroll bar in the Feature Editor cannot be used to reach the field being pointed to. The field could eventually be seen by zooming out to 75% in the browser (see the second screenshot). 

Laptop specifications: Dell XPS 13 9310 2-in-1 ([link-to-specification](https://www.dell.com/support/manuals/en-us/xps-13-9310-2-in-1-laptop/xps-13-9310-2-in-1-setup-and-specifications/processor?guid=guid-e25f3992-595c-44fd-83a2-3be669a094c1&lang=en-us))
| Dimension 	| Measurement (mm)	| Measurement (in)	|
|:--------------:	|:----------------------:	| :-------------------:	|
| Height       	| 180							| 7.09						|
| Width			| 288							| 11.34						|
| Diagonal		| 339.90						| 13.37						|

### Screenshots

![walkthrough-100-percent](https://github.com/facebook/Rapid/assets/56834523/127cc806-0972-4def-b44f-5377c3592672)
_Fig. 1: Walkthrough Screen at 100% Zoom_

![walkthrough-75-percent](https://github.com/facebook/Rapid/assets/56834523/1310d50a-957b-4f8c-88e2-1df3c8cc6359)
_Fig. 2: Walkthrough Screen at 75% Zoom_

### Version

2.2.5

### What browser are you seeing the problem on? What version are you running?

Chrome v123

### The OS you're using

Windows 11 Pro

### Steps to reproduce

1. Go to [https://rapideditor.org/](https://rapideditor.org/)
2. Click on "Start Mapping"
3. Click on the "Help" icon in the map panes on the right side of the screen
4. Click on "Start the Walkthrough"
5. Go through the walkthrough until you reach the **Open the Add Field list** step of the **Areas** section

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=2.00/0.0/0.0

**Comment by bhousel** [comment]
Thanks for reporting - It looks like the [id-tagging-schema](https://github.com/openstreetmap/id-tagging-schema) project has added more fields to the playground preset, pushing the target field off the screen.  I can probably add a workaround in Rapid to avoid showing these extra fields.
