### ISSUE TITLE
Log in to osm dev instance does not seem to work

### ISSUE THREAD

**Issue by mmd-osm** [facebook/Rapid#1370]
Rapid has this toggle in the lower right toolbar section where you can switch from "live" to "dev" mode. Once in dev mode, I tried to log on to the osm dev instance, and got the error message below. It seems the  OAuth 2 config does not list the Rapid landing page as one of the permitted callback urls yet. I used the public instance on https://rapideditor.org for testing. Thanks for looking into this!

An error has occurred

The requested redirect uri is malformed or doesn't match client redirect URI.

![image](https://github.com/facebook/Rapid/assets/5842757/3b75c07f-3c16-4735-8162-37f9c743fdca)

**Comment by bhousel** [comment]
Thanks @mmd-osm for testing this out ..
I ended up creating a new OAuth2 application on `https://api06.dev.openstreetmap.org` for testing, and I can confirm it is working now with the new client key and secret.

**Comment by mmd-osm** [comment]
Thanks! After cloning the repo and running the app on http://127.0.0.1:8080/ I could upload some changes to https://api06.dev.openstreetmap.org/changeset/355233 ... works all fine.
