### ISSUE TITLE
geoscribble notes support

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#1372]
### Description

As per this issue submitted by @Zverik: https://github.com/openstreetmap/iD/issues/10204 We will take a crack at adding this Layer to Rapid as part of the existing 'QA' layer- readonly, on top of everything else, single-color monochrome treatment so that scribbles are available. 

#### See also
* https://wiki.openstreetmap.org/wiki/GeoScribble
* https://geoscribble.osmz.ru/docs
* https://github.com/Zverik/geoscribble

**Comment by bhousel** [comment]
This is great!  It looks like all of the styling options they offer can be mapped into properties in our styling system.

Regarding the UI, it does look like they are expecting the renderer to have some kind of on-map popup capability - we dont have this exactly, but we could probably build it using the the `overlay` div for this - this is where we stick the edit menu.

**Comment by Bonkles** [comment]
All righty! I have removed the interactivity from the layer and 🥪 the geoscribbles layer  between the imagery / OSM Data layers as suggested:

Uploading Screen Recording 2024-04-17 at 12.27.15 PM.mov…

**Comment by Zverik** [comment]
Huh, I now have no idea in which thread to reply :) Regarding aging, I must point out that there's a third data type that the backend could return: a box. That's a geohash rectangle with the single value: minimum age of scribbles inside it. Useful for finding new drawings on lower zooms. Up to you whether you want to support it. On the WMS layer, I [color these](https://github.com/Zverik/geoscribble/blob/main/web/wms.py#L110) by age.
