### ISSUE TITLE
Wayback imagery: Unclear interaction between image layer and feature

### ISSUE THREAD

**Issue by tordans** [facebook/Rapid#1379]
### Description

Video (at the end):

https://github.com/facebook/Rapid/assets/111561/d2613fdb-e347-435f-9399-036841b45a6d

1. I activate the wayback images => the regular image layers get deselected, which is great
2. I activate a regular image layer again => the wayback images checkbox is still seletected
3. ==> the only way to re-pick the wayback images is to unselect and reselect those. I think the checkbox needs to unselect once I switch back to a regular image layer

### Version

canary

### Steps to reproduce

.

### The browser URL at the time you encountered the bug

https://rapideditor.org/canary#map=17.85/52.70497/13.88678&background=EsriWorldImagery&datasets=fbRoads,msBuildings&disable_features=boundaries

**Comment by bhousel** [comment]
I've been thinking about how I want to improve this issue, and I'm leaning towards just making another item in the main radio button list called "Esri Wayback" that sits next to "Esri World Imagery".  

Technically the latest "Esri Wayback" should be identical to the current "Esri World Imagery", but I can imagine that people will want to lock in an older date on the wayback imagery, then compare and switch between the different sources, this is why it would be beneficial to have them as 2 separate list items, and it would eliminate a lot of the confusion that comes from having a radio choice up top and a checkbox further below, and having no coordination between these two elements.
