### ISSUE TITLE
Support arbitrary WKT Polygons in a new URL Param

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#1386]
https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry

### Description

While creating many of our maproulette issues to drive changes across the globe, we try to call attention to a lot of missing features. This means we don't actually have any way of just drawing a shape around an *empty* bit of map. (Though, we can highlight existing entities by supplying their id to the url params like `&id=n12345678`). 

This functionality would be as follows: Support a new 'wktPoly' string param that would allow for either POLYGON or MULTIPOLYGON wkt format, so that tasks/etc. could make Rapid draw some borders around areas of interest. 

i.e. 
polys: 
```http://127.0.0.1:8080/#map=13.36/12.3540/-1.5080&background=Bing&wktPoly=POLYGON ((-1.53 12.37, -1.53 12.36, -1.52 12.36, -1.52 12.37, -1.53 12.37))```
![image](https://github.com/facebook/Rapid/assets/1887955/ecb2a242-773a-4fac-b667-5272708d5937)

or for multipolys:
```http://127.0.0.1:8080/#map=13.36/12.3540/-1.5080&background=Bing&wktPoly=MULTIPOLYGON (((-1.5215 12.3591, -1.5317 12.3432, -1.5017 12.3406, -1.4997 12.3649, -1.5215 12.3591)),((-1.5186 12.3765, -1.5339 12.3580, -1.5464 12.3792, -1.5520 12.3319, -1.4906 12.3235, -1.4740 12.3681, -1.5186 12.3765)))```

![image](https://github.com/facebook/Rapid/assets/1887955/546576b9-472e-45bf-910b-19a1f00b03a7)

**Comment by tordans** [comment]
@Bonkles 
> While creating many of our maproulette issues to drive changes across the globe, we try to call attention to a lot of missing features. This means we don't actually have any way of just drawing a shape around an empty bit of map.

My take would be to add a Polygon as the task to MapRoulette. I recently learned one can even add multiple Features per MapRoulette Task which is (miss?)used in https://maproulette.org/challenge/36475/task/142587488 to draw the triangle on the map ([corresponding GeoJSON](https://maproulette.org/api/v2/task/142587488?mapillary=false)).

I don't quite understand this ticket…, just wanted to point out that there might be a way to use MR directly for this.

**Comment by bhousel** [comment]
> I don't quite understand this ticket…, just wanted to point out that there might be a way to use MR directly for this.

Sure!  For context, the reason for the request is because we sometimes want to show an area of interest, and while historically we've used `.gpx` or `.geojson` files to do this, there is some extra burden in generating these files and hosting them someplace with CORS set up correctly, so our mapping teams want to be able to just pass the geometry through the url.

**Comment by tordans** [comment]
Thanks! Sounds great!
