### ISSUE TITLE
Features remain visible/selectable when zoomed out

### ISSUE THREAD

**Issue by sicknacco** [facebook/Rapid#1391]
### Description

When zooming out all features still render and are still selectable, rather than seeing the typical "+ Zoom in to edit". Since these features render when zooming out, it causes a lot of lag when zooming/panning the map. Both screenshots were taken at 3500 ft.

### Screenshots

![good](https://github.com/facebook/Rapid/assets/118150778/ad38b55e-53e8-4714-9e7e-9b0a07ec7ed2)
![bad](https://github.com/facebook/Rapid/assets/118150778/655db4c5-f596-435d-870e-729855a8a584)

### Version

2.3.0-pre.0

### What browser are you seeing the problem on? What version are you running?

Chrome v124.0

### The OS you're using

mac

### Steps to reproduce

1. Go to any densely populated area like New York City
2. Zoom in to a specific building or area
3. Zoom out and see that more and more features render, rather than less

### The browser URL at the time you encountered the bug

https://rapideditor.org/canary#map=13.72/40.6712/-73.9557/338.7&background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

**Comment by bhousel** [comment]
Thanks for reporting - I agree that we need to do a better job of simplifying the scene at lower zoom levels.  We want to give the user ability to do some editing at low zooms, but we need to remove some of the features so that they aren't all rendered.  This is covered in tickets #557 , #697 already .
