### ISSUE TITLE
Zooming issue when use scroll wheel

### ISSUE THREAD

**Issue by mandal1977** [facebook/Rapid#1392]
### Description

When do scrolling with a mouse wheel , instead of zooming, map went up and down 

### Screenshots

![8DB01E63-2484-4F31-B617-C6F52DCFDEC6_1_206_a](https://github.com/facebook/Rapid/assets/168457538/03463789-ab1a-4495-be09-022a2f263fcd)

### Version

2.3.0-pre.0

### What browser are you seeing the problem on? What version are you running?

Edge v124.0

### The OS you're using

mac

### Steps to reproduce

1. Open the main page.
2. when you use scrolling wheel instead of zooming, map page going up and down.

### The browser URL at the time you encountered the bug

https://rapideditor.org/canary#map=3.00/53.70/23.87&background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0

**Comment by bhousel** [comment]
Hey @mandal1977 thanks for reporting.. Different OS and browser combos can make it difficult to detect what the user is doing with the wheel.  

We ended up adding this user preference to control this in #680, see below.
Does adjusting that setting resolve the issue?

<img width="683" alt="Screenshot 2024-04-29 at 3 34 26 PM" src="https://github.com/facebook/Rapid/assets/38784/29b95af9-a3a0-44da-8a72-639600f69a61">

**Comment by mandal1977** [comment]
Thanks Bryan
Yes, adjusting that setting resolve the issue.
