### ISSUE TITLE
Test Rapid embed in iframe

### ISSUE THREAD

**Issue by bhousel** [facebook/Rapid#1404]
We have a handful of situations where partners are starting to embed Rapid in an `<iframe>` within a containing site and running into various issues.  

We haven't specifically tested this situation, but it will be necessary to make this work well for wider Rapid adoption, so I'm going to make a dedicated test page like `/dist/embed.html`, both to serve as an example implementation and to test that Rapid works seamlessly in this configuration.

**Comment by tordans** [comment]
Just in case: Do the use cases of those partners include linking to this page directly like with OSM org? If so, it might be good to show case how the URL state is shared. I mention it, because the solution we have on OSM org is quite lacking IMO. I tried improving it a while back in https://github.com/openstreetmap/openstreetmap-website/pull/3033 but that did not go anywhere, yet.

**Comment by bhousel** [comment]
> I mention it, because the solution we have on OSM org is quite lacking IMO. I tried improving it a while back in [openstreetmap/openstreetmap-website#3033](https://github.com/openstreetmap/openstreetmap-website/pull/3033) but that did not go anywhere, yet.

We're currently mostly interested in embedding it in Maproulette and our internal task manager, but we do want this to work on OSM org also.   I agree that it should sync all the hash parameters if possible.

Thanks for the pointer to 3033 - I hadn't seen it!  From a quick scan of [javascripts/edit/id](https://github.com/openstreetmap/openstreetmap-website/blob/master/app/assets/javascripts/edit/id.js.erb) it looks like these params on osm org might only be synced at iD's startup time, which is not idel - I think that was the intent behind 3033? .  Rapid's code now has a dedicated URLHash system that will emit events whenever the url hash changes, so I think we can make this integration a lot cleaner.
