### ISSUE TITLE
Url with only id doesn't zoom to feature

### ISSUE THREAD

**Issue by atiannicelli** [facebook/Rapid#1406]
### Description

When I type in https://rapideditor.org/rapid?id=r1257794 it does not zoom to that feature. Sometimes I can make it zoom to the feature if I add other parameters like background but it doesn't always zoom. Is there a secret?

### Screenshots

when I typed in https://rapideditor.org/rapid?id=r1257794
the url ended up being 
https://rapideditor.org/rapid?id=r1257794#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=2.00/0.0/0.0
![Screenshot 2024-05-03 at 11 46 58 AM](https://github.com/facebook/Rapid/assets/5851115/4666970e-21b4-4555-af4d-ebf09109c6b4)

### Version

2.2.5

### What browser are you seeing the problem on? What version are you running?

Chrome v124.0

### The OS you're using

mac

### Steps to reproduce

in a browser type https://rapideditor.org/rapid?id=r1257794
observe that it doesn't zoom to the feature

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid?fbclid=IwAR3ibWCncP40PJ7HByIpcFnu113GOihwATdL_3yPslzxpjAuyIhKb0gEP1U#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=r1257794&map=12.89/28.4533/-81.4965

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

**Comment by bhousel** [comment]
Thanks , I'll check this!  I agree it should work

**Comment by Bonkles** [comment]
![image](https://github.com/facebook/Rapid/assets/1887955/50a990d6-1fd9-42f2-8ea2-427a68f89303)
