### ISSUE TITLE
Walkthrough bug- intersection during 'lines' step not clickable/hidden by the curtain

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#1408]
### Description

In the lines step, we're suggesting that the user click on an intersection to 'split' it and disconnect the way from the road network. However, our highlighting is full of fail: 

This effectively prevents the user from clicking through the walkthrough in its entirety.  

### Screenshots

![image](https://github.com/facebook/Rapid/assets/1887955/9095f278-48b0-415e-ad47-6eca61037767)

### Version

2.3.0-pre.0

### What browser are you seeing the problem on? What version are you running?

Chrome v124.0

### The OS you're using

mac

### Steps to reproduce

Enter the walkthrough. 
Proceed to the 'lines' step. 

Get through the 'draw a way' and 'fix a way' step to 'disconnecting a way'. 

Observe the screenshot behavior 

### The browser URL at the time you encountered the bug

N/a (walkthrough bug) 

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

**Comment by bhousel** [comment]
Same issue as #1527  - we were caching a bunch of `getBoundingClientRect` rectangles (container, map, sidebar) and so these Extent rectangles could be off when certain things happen:
- browser window resizes
- sidebar resizes or expand/contract
- map rotations
