### ISSUE TITLE
MapRoulette integration seems to be storming challenge-fetches

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#1409]
### Description

While testing for the 2.3 release we came upon a showstopper: Chrome literally ran out of resources while the MR integration was running. 
[127.0.0.1-1715031385843.log](https://github.com/facebook/Rapid/files/15226881/127.0.0.1-1715031385843.log)

![image](https://github.com/facebook/Rapid/assets/1887955/6e109d6b-deb4-4cc8-9923-5e2a96235088)

### Screenshots

see above. 

### Version

2.3.0-pre.0

### What browser are you seeing the problem on? What version are you running?

Chrome v124

### The OS you're using

MacOS 14.4.1

### Steps to reproduce

Click the MapRoulette integration on. 

Pan around a bit, then use the geocoder to find a completely new place to go and head there (Not sure if this is necessary)? 

Observe the console log after you navigate away- there will be TONS of fetches being complained about. 

### The browser URL at the time you encountered the bug

http://127.0.0.1:8080/#map=17.00/42.37817/-71.11120&background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries

(this is from after navigating away from Seattle, where MR tasks weren't showing up)

**Comment by bhousel** [comment]
#1410 fixed this right?

**Comment by Bonkles** [comment]
Right you are, closing.
