### ISSUE TITLE
Create heads-up display for esri data (webgl exploration)

### ISSUE THREAD

**Issue by Bonkles** [facebook/RapiD#141]
Currently the users have to click on the RapiD button to see which colors they've assigned to a given dataset. A heads-up style mini-legend displayed as a map overlay would help this.

**Comment by bhousel** [comment]
Closing this too as stale - we've done a lot of work on webgl in the past year.. I'm not sure whether this was added before the sidebar was changed, but it's pretty easy now to hover over features and see what dataset they belong to, with the color in the sidebar consistent with the on-map rendering.

I think most parts of the UI are fair game for a redesign, so maybe we'll rethink how this all works anyway!
