### ISSUE TITLE
Significant performance issues with 2.3 - Likely MapRoulette Tasks data layer

### ISSUE THREAD

**Issue by eneerhut** [facebook/Rapid#1412]
### Description

I am testing out v2.3 and am seeing significant sluggishness that makes it unusable. I noticed a number of OSM API timeouts in the developer tools console, but they eventually went away when I zoomed further in. I am not sure whether the MapRoulette plugin caused this sluggishness or something else is going on, but it's so slow that I cannot interact with Rapid in any useful way.

### Screenshots

<img width="596" alt="image" src="https://github.com/facebook/Rapid/assets/11349863/9c8b6e78-6d76-4701-8af8-b088c87b6768">

### Version

2.3.0

### What browser are you seeing the problem on? What version are you running?

Chrome v124.0

### The OS you're using

mac

### Steps to reproduce

1. Opened version 2.3.0.
2. Opened Map Data menu at a low zoom and enabled MapRoulette selected challenge number `41502` in San Francisco.
3. Zoomed into San Francisco.
4. Disabled MapRoulette, but still experiencing extremely slow performance.

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#map=15.39/37.7766/-122.4197&background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

**Comment by eneerhut** [comment]
https://github.com/facebook/Rapid/assets/11349863/f33c57e8-8d9c-496c-9fa8-df7c1badf17b

Here is a video to show you what I mean.

**Comment by bhousel** [comment]
hey @eneerhut 
can you check https://github.com/facebook/Rapid/issues/1145#issuecomment-2063993679 and see whether switching the ANGLE graphics backend is causing some of your performance issue?  (it seems to especially affect the Meta folks)

**Comment by eneerhut** [comment]
I set OpenGL as the default. Not sure if it's placebo, but I am noticing somewhat faster rendering in dense areas such as SF. 
I was able to load at least some of the MR tasks too which is progress. Will keep OpenGL as the default and see how I go over the next few weeks.

Thanks!

**Comment by eneerhut** [comment]
Confirming that your latest fixes seem to address this @bhousel. Nice work!
There are some performance issues for San Francisco at low zoom levels, but otherwise it's working nicely.
