### ISSUE TITLE
New MapRoulette tasks are AWESOME but not all there.

### ISSUE THREAD

**Issue by atiannicelli** [facebook/Rapid#1413]
### Description

When I enable maproulette tasks I don't see all of them. 

### Screenshots

You can see what I see on Rapid... Just one task for the 43338 challenge
![Screenshot 2024-05-08 at 4 44 01 PM](https://github.com/facebook/Rapid/assets/5851115/2e778a75-a060-4550-9e6b-f7b2089d9914)
But if I look on MapRoulette I see more.
![Screenshot 2024-05-08 at 4 44 22 PM](https://github.com/facebook/Rapid/assets/5851115/5808dec7-cb9b-4174-a915-e20c390efc6d)

### Version

2.3.0

### What browser are you seeing the problem on? What version are you running?

Chrome v124.0

### The OS you're using

mac

### Steps to reproduce

Go to https://rapideditor.org/rapid#map=19.82/42.33761/-71.04648
and enable MapRoulette Tasks. (I also added the challenge id 43338 but you don't need to to see the issue)
Observe that only one tasks is loaded and there should be a hand full in that area.

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid#map=19.82/42.33761/-71.04648&background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

**Comment by Bonkles** [comment]
So one of the things we try to do is only show tasks if their parent challenge is still active. Is it possible that the other tasks that MapRoulette is showing you in that UI are actually part of inactive challenges? 

Related bug (which you opened, lololol): https://github.com/maproulette/maproulette3/issues/2211

**Comment by jjiglesiasg** [comment]
Why the Hashtag #Maproulette shows up by defect, if the user is NOT DOING at all a maproulette challenge?

This is creating a FALSE hashtag count in every changeset.

**Comment by Bonkles** [comment]
@atiannicelli found the issue- we attempt to only show non-deleted challenge tasks. But in our zealousness to only display those, we accidentally only display the *FIRST* task we discover for a given challenge. All the other tasks that belong to that challenge end up on the floor. 

Thanks for the report!

**Comment by Bonkles** [comment]
> Why the Hashtag #Maproulette shows up by defect in the Changeset, if the user is NOT DOING at all a maproulette challenge?

@jjiglesiasg this shouldn't be happening, I'll create a separate bug to track that.
