### ISSUE TITLE
Preserve MapRoulette task settings in the URL

### ISSUE THREAD

**Issue by eneerhut** [facebook/Rapid#1422]
### Description

Coordinated mapping efforts would be enhanced if we can preserve MapRoulette in the URL. If the challenge ID is preserved, we can easily encourage people to participate in a challenge by sharing a Rapid link.

Maybe something like `&MapRoulette=41502` which would automatically enable MR while preserving the other settings.

**Comment by bhousel** [comment]
Sounds good - we can prioritize this.
Another good idea by @geocruizer, allow a comma-separated list here instead of a single challenge id.

**Comment by eneerhut** [comment]
+1 that's a great idea.

In the Walkabout meeting we talked about clustering too. This is a bigger effort, but I can see [leaflet style clustering](https://github.com/Leaflet/Leaflet.markercluster) serving multiple applications within Rapid. For example, it could help to highlight which parts of the map have ML buildings and roads when the user is at a low zoom level.

**Comment by bhousel** [comment]
Hey @eneerhut,  @Geocruizer, @atiannicelli
 
I just added support for enabling the MapRoulette via the url parameter.. The supported value can either be `true` or a comma-separated list of challenge IDs to filter by.  If you get a chance, try it out in the canary build, and let me know how it goes!  

(Like before, if challenge IDs are specified, Rapid will display the tasks even if that challenge is set to be hidden.  If no challenge IDs are specified, Rapid just shows all the visible challenges in the map region).

Examples:  

`&maproulette=true` 
https://rapideditor.org/canary#map=17.00/42.33214/-71.04076/359.0&maproulette=true
-or- 

`&maproulette=<challengeIDs>`
https://rapideditor.org/canary#map=17.00/42.33214/-71.04076/359.0&maproulette=41509,43946

**Comment by eneerhut** [comment]
Working well for me so far @bhousel. Great implementation.
[SF Untagged Crossing Ways.](https://rapideditor.org/canary#map=15.75/37.7883/-122.4164&maproulette=41502&background=EsriWayback_2024-08-15&datasets=fbRoads,msBuildings&disable_features=boundaries)

**Comment by atiannicelli** [comment]
I haven't tried it out but the functionality sounds great! I will probably give it a whirl on Monday.
