### ISSUE TITLE
Cannot upload Changesets with Firefox

### ISSUE THREAD

**Issue by misibacsi** [facebook/Rapid#1425]
### Description

I cannot upload my changeset with Firefox. 
It started maybe one or two month ago.
Upload "starts" but it only waits...
I switched to Opera browser and it can upload changeset with the same user credentials.
I cleared the Firefox cache without positive results.

### Version

2.3.1

### What browser are you seeing the problem on? What version are you running?

Firefox v125.0

### The OS you're using

win

### Steps to reproduce

1. modify map
2. try to upload to OSM
3. wait...

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#map=18.35/47.79694/19.76731&background=custom:https://orto1.tile.openstreetmap.hu/fomi2011-2014/{z}/{x}/{y}.webp&datasets=fbRoads,msBuildings&disable_features=indoor,landuse,boundaries,pistes,aerialways,power,past_future,others

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0

**Comment by bhousel** [comment]
Thanks for reporting @misibacsi  - Is this the Editing Conflicts screen , like seen on #1361  ?
There are some situations where uploads get stuck here in a conflict check loop.

**Comment by misibacsi** [comment]
There is no "edit conflict" message. 
I am confident it cannot be "edit conflict", as no one else edits the same territory as me.
With different browser (Opera) upload works - same territory, same edits, same credentials.
Maybe it is a problem within Firefox settings, but I do not know which one causes this.

**Comment by bhousel** [comment]
Interesting - I just tried editing around there with Firefox and I was able to [save a change](https://www.openstreetmap.org/changeset/151315056) with no issues.  

Can you perform these steps to help us investigate the issue?
- Press <kbd>F12</kbd> to open the Firefox developer tools before you attempt to save
- Then try your save as usual, and let me know if there are messages that appear in the "Console" tag of the developer tools.

Thanks 👍

**Comment by misibacsi** [comment]
I figured out with your help in this Firefox console info, that it was probably a **CORS-related problem**.
(There were warnings that something would not work)

I switched to another CORS software (it is now: "CORS Everywhere").

Test: I added buildings to the map, and could upload changesets 2x.

Thanks!

**Comment by bhousel** [comment]
Great! Glad things are working again 👍
