### ISSUE TITLE
Roads being added that are not visible in prediction

### ISSUE THREAD

**Issue by bradlewt** [facebook/Rapid#1426]
### Description

The predicted road shows a certain line segment, but when one "accepts" the road segment, it adds additional, erroneous roads 

### Screenshots

https://github.com/facebook/Rapid/assets/24398638/0ae2ffdc-69f8-4789-9b14-8e189dc39f4b

### Version

2.3.1

### What browser are you seeing the problem on? What version are you running?

Chrome v124.0

### The OS you're using

win

### Steps to reproduce

Go to: https://rapideditor.org/edit#map=16.60/11.02714/-0.76480&background=EsriWayback_2024-03-28&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w-1185400465156696

Click on road

Accept road

Watch new thing appear

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#map=16.60/11.02714/-0.76480&background=EsriWayback_2024-03-28&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w-1185400465156696

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

**Comment by bhousel** [comment]
Thanks - looks like #1313 is still an issue 😢
