### ISSUE TITLE
Allow togging rapid features in map data panel

### ISSUE THREAD

**Issue by tordans** [facebook/Rapid#1434]
I was looking for the toggle to hide the pink building datasets in the map data panel but could not find it.
One can toggle it from the rapid button.
I wonder if this should be duplicated to the map data panel so all data toggles are in the same place 

<img width="773" alt="image" src="https://github.com/facebook/Rapid/assets/111561/5752c88f-7aac-4806-9663-b7c51f9e61d9">

**Comment by bhousel** [comment]
Makes sense!  Yes I've also found it frustrating that the Rapid layer isn't shown with the other data layers.
