### ISSUE TITLE
MapRoulette: Allow working on a specific hidden challenge

### ISSUE THREAD

**Issue by tordans** [facebook/Rapid#1436]
### Description

I tend to set MapRoulette Challenges to "invisible" whenever I want to test them but also when I only want to work on them with a specific group of people. 

However, it looks like there is no way to access a non-public challenge in Rapid.
(Right now, 45242 is public again, to allow testing it.)

<img width="356" alt="image" src="https://github.com/facebook/Rapid/assets/111561/c93a26f8-848e-4852-b06a-bea153f97d6e">

I was hoping for something like …
- When no challenge ID is given, show all public challenges
- When a specific challenge ID is given, show that one regardless of it's public state

**Comment by Bonkles** [comment]
I've asked the MapRoulette devs what they think of allowing this little override, I'm in favor.
