### ISSUE TITLE
Loading waybackconfig blocks loading the editor

### ISSUE THREAD

**Issue by deevroman** [facebook/Rapid#1445]
### Description

In Russia and Iran domain s3-us-west-2.amazonaws.com it is blocked and no data is downloaded from it.
https://check-host.net/check-report/19b77be3k341

When opened, Rapid tries to download the file https://s3-us-west-2.amazonaws.com/config.maptiles.arcgis.com/waybackconfig.json

However, the request hangs, which is why the editor waits for tens of seconds until the browser returns a timeout-related error.

If you block access to this address so that any access to it returns an error, Rapid will be open immediately.

### Screenshots

https://github.com/facebook/Rapid/assets/25708359/fd18810d-cdbc-4bb3-bc69-1e062f836ed5

### Version

2.3.1

### What browser are you seeing the problem on? What version are you running?

Firefox 127

### The OS you're using

macOS 14.5

### Steps to reproduce

1. Open Rapid URL

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid#map=17.20/44.26064/135.05102&background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries

**Comment by bhousel** [comment]
Thanks for letting us know!  We definitely don't want Rapid to hang for 10 seconds .. I'll think of ways that we can either just fail quickly or mirror that file in a way that you can fetch it from anywhere.

**Comment by Glebzilla** [comment]
I will add that I wait a little over 10 seconds, 2-3 minutes for the site to load.

**Comment by bhousel** [comment]
I added a workaround today so that Rapid shouldn't be blocked on fetching this file from AWS anymore.. If you're experiencing this issue, can you test on  https://rapideditor.org/canary  and let me know if you see more reasonable startup time?

**Comment by deevroman** [comment]
Yes, Rapid loads fast now (and shows available archived ESRI satellite images)
