### ISSUE TITLE
CTRL+Z Undo Shortcut Does Not Work While Drawing Areas

### ISSUE THREAD

**Issue by dmich9** [facebook/Rapid#1450]
Exactly what the title says. CTRL+Z works under most circumstances, however, when in the process of drawing an area, it does not. This would be useful to fix because if you mess up while drawing an area, it takes longer to restart the shape or fix it after, rather than undoing the previous node drawn (Like the regular ID editor).

**Comment by bhousel** [comment]
@dmich9 what browser/os are you using? 

I'm having trouble reproing this issue - Undo and redo are working for me while drawing an area (I'm testing on a Mac in Chrome)

https://github.com/facebook/Rapid/assets/38784/4cee7e59-057f-4ecf-b8fb-b56d47967c1a

**Comment by dmich9** [comment]
I have no idea how, but it's magically working for me now a few days later (I didn't even refresh the page). I remember being so frustrated as I spammed ctrl+z and nothing was happening (I know I wasn't hallucinating haha). Anyway, thanks. Sorry for the waste of time.

**Comment by bhousel** [comment]
It’s ok! I wonder if maybe you got something else on the site to have focus, like a input field 🤔
