### ISSUE TITLE
Features continue to render after zooming out

### ISSUE THREAD

**Issue by sicknacco** [facebook/Rapid#1453]
### Description

As I zoom out, instead of seeing less and less features rendering, I see more.
Because of this, the UI becomes very lagged and I hit OSM API limits quickly. Making it impossible to use

### Screenshots

![Screenshot 2024-05-29 at 9 58 58 AM](https://github.com/facebook/Rapid/assets/118150778/07565570-4407-4549-acc3-656364f5d7e8)

### Version

2.3.1

### What browser are you seeing the problem on? What version are you running?

Chrome v125.0

### The OS you're using

mac

### Steps to reproduce

Open any area, zoom out.
You should see all features plus more continue to render, rather than seeing the "zoom in to edit" prompt.

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid#map=16.43/39.77022/30.51041&background=EsriWorldImagery&datasets=fbRoads,msBuildings&disable_features=boundaries&photo_overlay=streetside

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36

**Comment by bhousel** [comment]
Thanks for reporting!  We're tracking this on #557 
There are lots of different causes of slowness at play here, but I agree that Rapid should be able to manage the data loading better, and render the scene more efficiently so that whatever zoom you are at shows something appropriate.
