### ISSUE TITLE
Task feature not selected when opening a Map Roulette task

### ISSUE THREAD

**Issue by sicknacco** [facebook/Rapid#1467]
### Description

Sometimes when opening a Map Roulette task in Rapid, the feature is not selected

### Screenshots

![Screenshot 2024-06-18 at 11 00 35 AM](https://github.com/facebook/Rapid/assets/118150778/9ae3d9a7-076e-427a-add1-977e8966d0ae)

### Version

2.3.1

### What browser are you seeing the problem on? What version are you running?

Chrome v126.0

### The OS you're using

mac

### Steps to reproduce

1) Go to Map Roulette
2) Open task in Rapid

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#map=17.03/42.25330/-71.11579&background=MassGIS_2021_Aerial&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w1288580811

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

**Comment by tordans** [comment]
This way  https://www.openstreetmap.org/way/1288580811 is deleted.

**Comment by sicknacco** [comment]
Thanks tordans. I see that now. It just so happened to occur on a few tasks in a row oddly enough. Thanks for looking into it. I'll close the issue
