### ISSUE TITLE
Better conflation for address datasets against buildings that already have the same address

### ISSUE THREAD

**Issue by wcedmisten** [facebook/Rapid#1470]
### Description

It would be great if the conflation system recognized ways with the same field and not just points.

![image](https://github.com/facebook/Rapid/assets/4565200/3491e005-c401-4923-8556-e561ad08b769)
![image](https://github.com/facebook/Rapid/assets/4565200/a53e70e3-5919-4f29-8032-4680d417ec16)
![image](https://github.com/facebook/Rapid/assets/4565200/c6f59a5b-ace2-4e2d-8933-5209d24912c8)

**Comment by bhousel** [comment]
I agree!  this is also #1454
