### ISSUE TITLE
Translate Rapid logo too?

### ISSUE THREAD

**Issue by bhousel** [facebook/Rapid#1488]
While working through #206  I realized that we might want to translate the Rapid logo to other languages - or not?  
It's not a thing I had thought about before.

What we do currently in most places is display the logo as an SVG which has the logo on the left and the wordmark on the right.  
I don't know what font the wordmark is in, but it's not something we can replicate with a free font, so probably we'd need to loop in our design resources at Meta to change this.

Anyway here are some examples of what we currently display.
This might look weird in languages that don't use a Latin script, or ones that go right-to-left, I don't know:

### Locale `en-US`
<img width="368" alt="Screenshot 2024-07-11 at 10 22 32 AM" src="https://github.com/facebook/Rapid/assets/38784/f9f88326-4b0a-4906-b11f-7fb4408b46bc">

### Locale `zh-CN`
<img width="339" alt="Screenshot 2024-07-11 at 10 01 50 AM" src="https://github.com/facebook/Rapid/assets/38784/ba4f22e0-ab1d-4fd1-a4e4-5f497db8ec8e">

### Locale `ar`
<img width="341" alt="Screenshot 2024-07-11 at 10 02 21 AM" src="https://github.com/facebook/Rapid/assets/38784/ba0b95ac-f673-4a28-948c-a0910842fc18">

**Comment by eneerhut** [comment]
It's much stronger if a brand is consistent and I think it rare for brands to translate their logo for different languages. I do not think we should do this.
I would be surprised if [any of the brands on this list](https://www.forbes.com/powerful-brands/list/) translate the logo itself.

**Comment by eneerhut** [comment]
Awesome @bhousel, good find. This is really interesting. TIL and agree it looks better for right to left languages!
