### ISSUE TITLE
Problem with behavior of Rapid users deleting content mapped by local mappers to add AI generated content faster

### ISSUE THREAD

**Issue by fititnt** [facebook/Rapid#1491]
### Description

I will use an example, between this changeset https://www.openstreetmap.org/changeset/153859591 and https://www.openstreetmap.org/changeset/153859629, timestamps 2024-07-12T14:52:22Z vs 2024-07-12T14:53:41Z, the user had less than 1min29s.

This already was complained about in the past, as can be seen here https://x.com/thughes/status/1631035151173005312 (response to a mapwithrapid X account encouraged users to delete content).
Armchair mappers deleting content from local mappers is not welcomed. This is even worse because sometimes the deleted buildings by airmchair organized editing already have other metadata (not only building type, but amenity) however compared to other software editors for OpenStreetMap, this encouragement for delete content is very, very harmful (even worse than the argument "what about JSOM mapwithai")

### Version

lastest

### Steps to reproduce

1. Check OSMCha for deleted content submited by rapid editor
2. Order by deletetions
3. Get one or more of these changesets, which user deleted smaller sections (sometimes user will also add or edit some to not raise obvious mass deletion from OSMCha)
4. Go to that area on OpenStreetMap with an editor, and look for added buildings on the region
5. Compare both deleted buildings and added buildings, made by different chancesets, and note that same user is (as suggested on https://x.com/mapwithrapid/status/1631014105992642560) will use it

### The browser URL at the time you encountered the bug

https://www.openstreetmap.org/changeset/153859591

**Comment by bhousel** [comment]
Hey @fititnt it sounds like you just have an issue with one user's style of mapping, or maybe with the instructions on hotosm-project-17084 ?  I'd encourage you to reach out to the user directly, or the organizers of that mapping project.  This isn't an issue with the Rapid tool.  
(Any editing tool for OSM allows users to delete and redraw things that are wrong - Rapid is no different in this way).

**Comment by fititnt** [comment]
> Hey @fititnt it sounds like you just have an issue with one user's style of mapping, or maybe with the instructions on hotosm-project-17084 ? I'd encourage you to reach out to the user directly, or the organizers of that mapping project. 

The instructions to delete actually are a recommendation from https://x.com/mapwithrapid/status/1631014105992642560, which is would be applied to far more than this project

![you-can-delete-then](https://github.com/user-attachments/assets/e0f1a2a3-2f64-4b1e-9cf8-85d3498b230a)

>  This isn't an issue with the Rapid tool.
> (Any editing tool for OSM allows users to delete and redraw things that are wrong - Rapid is no different in this way).

Then the question is: **could someone please point any editing tool for OSM which **delete objects** as part of functionality?** If does not exist, then please (instead of remove the delete functionality) any place from developers of @mapwithrapid (at least this twitter announcement) needs to be edited or removed

**Comment by bhousel** [comment]
Sorry I don't have access to the account that tweeted that thing over a year ago that you are mad about - but I will reach out to the team and ask them to take it down.  From reading the thread, everyone seemed pretty clear that this workflow is only for situations where the existing buildings are not worth keeping.

Issues  #802 / #290 cover allowing the user to see multiple data sources together and to add a replace geometry feature similar to what Lalonde mentioned.

**Comment by fititnt** [comment]
Oh, yes, "replace geometry" feature mentioned as early as 2021 on this repo for sure would be the perfect solution. However, I suppose it's not trivial to implement, so might take a long time to be available to the general public (which may be overusing the delete-then-upload to allow they to use AI-generated suggestions, which today they cant even see in advance to know if would be good or not).

Also (a logic that applies to any tool, not only Rapid) the higher the tendency of users overuse delete-then-create, the more likely the delete step will erase local knowledge (like more specific building types than building=yes or even amenity= using same closed-way of building= done by mappers without squaring the edges) or old imports with high level of details (like building height) with an offset. This kind of extra metadata (without user check the tagging) may not even display differently

> Sorry I don't have access to the account that tweeted that thing over a year ago that you are mad about - but I will reach out to the team and ask them to take it down.

Thank you!
