### ISSUE TITLE
When selecting multiple features, need to show 'multiple values' if a tag is only set on one feature

### ISSUE THREAD

**Issue by atiannicelli** [facebook/Rapid#1493]
### Description

When I select two buildings (actually a building and a building part) I see where there are collisions in the tags, but if one of the features doesn't have a tag at all it doesn't indicate that. If I click on that tag then it silently transfers that tag to the feature that didn't have it. I would have expected it to say that there are multiple values for the tag; something and 'unset' or NULL). You can see that in my attached video that:
1) the order of selecting a building part first vs building first has different behavior.
2) All the values from the first selected feature are listed as though they are shared between the two feature even though they are not. If one is clicked then that tag is silently attached to the other.

### Screenshots

https://github.com/user-attachments/assets/92b7db9a-2e7d-4691-98cb-6bc203600d80

### Version

2.3.1

### What browser are you seeing the problem on? What version are you running?

Chrome v126.0

### The OS you're using

mac

### Steps to reproduce

1. Select a building that has a bunch of tags like w261256050
2. Then select a building part that doesn't have many parts like w1302028017
3. observe that any of the tags assigned to the building that are not on the part do not indicate a tag collision.
4. observe that clicking on one of those tags assigns it to the part.

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#map=21.19/37.78908/-122.41919&background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w1043338399&photo_overlay=streetside

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

**Comment by atiannicelli** [comment]
Just wondering if this is clear. It could potentially cause incorrect tags to be added to features.

**Comment by bhousel** [comment]
> Just wondering if this is clear. It could potentially cause incorrect tags to be added to features.

I think so - I can see how the tags presented to the user can be confusing.. 
If one feature has the tag set, and the other feature has it not set, that should be considered "Multiple Values".
