### ISSUE TITLE
Features: Improved QoL for pedestrian mappers part II

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#1501]
### Description

This omnibus issue will capture all the pedestrian mapping improvements we want to make for H2.  For now this will be ideas that the team will review. 

(This is a follow-on to #1140 which was completed at the end of 2023). 
- [ ] #1113
- [ ] #1114
- Validations
- [x] #1143 
- [x] #1460 
 - [x] #1578 

MapRoulette: 
- [x] #1419
- [x] #1423
- [ ] Combine Tasking Manager task box with MR challenges
  - [ ] Counter for remaining tasks
  - [x] #1613
  - [ ] Positive signal that there are 'no more' challenges /features in view and that the user is done mapping 
  - [ ] Constrain loaded challenges to those within the supplied task box (don't show anything outside)
- [x] #1422

**Comment by eneerhut** [comment]
The Strava heatmap mentioned in #1462  could actually be a really interesting addition to assist the pedestrian mapping efforts.

**Comment by bhousel** [comment]
Going to close this for now as we're ready to code-freeze for v2.5.  We got a lot of it done!
