### ISSUE TITLE
Mapillary Integration loads all segmentations without color

### ISSUE THREAD

**Issue by sturksever** [facebook/Rapid#1502]
### Description

Mapillary photo overlay renders all segments with no colors when you have turned on the traffic signs layer. It seems like we are just loading all the raw segmentations and rendering them without any color coding. Please see below image on Rapid
![451883487_1213702420064588_6196728164382349491_n](https://github.com/user-attachments/assets/c4915966-3534-4599-b9d3-772b39d23b02)

Here is a screenshot from iD, when you click on a map feature or traffic sign we show it on the image in MJS.
![451884405_1710570286462595_7122601775891744779_n](https://github.com/user-attachments/assets/298c6caa-b575-4df7-a925-b586e2a36cec)

### Version

2.3.2

### Steps to reproduce

- Go to Rapid and enable Mapillary Imagery layer
- Enable traffic sign layer 
- View the imagery 

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid#map=20.12/30.63361/104.07387&background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w485149342&photo=mapillary/188334986520037&photo_overlay=mapillary,mapillary-signs

**Comment by bhousel** [comment]
Thanks for reporting @sturksever , I haven't tried this feature out, but I agree it should display the segmentation better.

**Comment by bhousel** [comment]
Looks like I commented it out a while ago.  I'll revisit and find a way to make this code safe to be called async.
(The concern is probably - highlighting the wrong thing if the user switches to another image during the time it takes to load the detections)

https://github.com/facebook/Rapid/blob/695d7f2fa93aaea4b98a2139157922956699fd8b/modules/behaviors/SelectBehavior.js#L401-L409
