### ISSUE TITLE
cycleway fields are not shown

### ISSUE THREAD

**Issue by tordans** [facebook/Rapid#1506]
### Description

When a highway has a `cycleway=*` tag, the field of the highway presets that allows users to see and change the data does not show in the sidebar.

This field does show up in iD.

Example

* [Rapid](https://rapideditor.org/canary#map=16.91/52.39203/13.28344&background=Berlin-2023&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w5200919)
* [iD](https://ideditor.netlify.app/#background=Berlin-2023&disable_features=boundaries&id=w5200919&map=16.95/52.39203/13.28344)

I am assuming that this is due to a change in the tagging-schema which change the hard coded directional field `cycleway` to `directionalCombo` a while back.

AFAIK this change was not migrated to Rapid, yet.

I always assumed that Rapid would fall back to the `cycleway` directional field and only ignore the newer `directionalCombo` fields like the `parking`-fields.

However it looks like that this is not the case.

**Comment by bhousel** [comment]
Yes, I think this is #1338 ?

**Comment by tordans** [comment]
Yes, it is, sorry.
