### ISSUE TITLE
Interacting with the page and then trying to close results in the beforeUnload popup even if there's nothing unsaved

### ISSUE THREAD

**Issue by emersonveenstra** [facebook/Rapid#1507]
### Description

With https://github.com/facebook/Rapid/commit/18e9e4984e5fa37d0119879feb34c083a228d1a3, every time I close the page after any interaction (even non-editing interactions like zooming, panning, changing the background layer) i get the beforeUnload popup.

This is confusing because now there's no way to tell if there's actually unsaved changes or not since it always fires, even after successfully uploading a changeset.

### Version

canary

### Steps to reproduce

1. go to https://rapideditor.org/canary#map=17.00/42.98753/-85.68950&background=Bing&datasets=&disable_features=boundaries&poweruser=true
2. Change the background to Esri
3. Try to close the tab

### The browser URL at the time you encountered the bug

https://rapideditor.org/canary#map=17.00/42.98753/-85.68950&background=Bing&datasets=&disable_features=boundaries&poweruser=true

**Comment by bhousel** [comment]
Sorry, I thought this would be better, but maybe I'm wrong.  
I can put it back to the previous behavior.
