### ISSUE TITLE
Unable to rotate map with shift + arrow keys

### ISSUE THREAD

**Issue by marklit** [facebook/Rapid#1520]
### Description

Unable to rotate map with shift + arrow keys

### Version

2.3.2

### What browser are you seeing the problem on? What version are you running?

Brave Version 1.68.141 Chromium: 127.0.6533.120 (Official Build) (64-bit)

### The OS you're using

Windows 11

### Steps to reproduce

Open the map. Hold down shift and press up or down arrows and nothing happens.

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid#map=18.80/59.50473/24.82727&background=EsriWorldImagery&datasets=fbRoads,msBuildings&disable_features=boundaries

**Comment by bhousel** [comment]
> Open the map. Hold down shift and press up or down arrows and nothing happens.

The shortcut is to hold shift and press left-right arrows (works the same as on MapLibre, or Mapbox).

<img width="221" alt="Screenshot 2024-08-21 at 8 25 01 AM" src="https://github.com/user-attachments/assets/1f4712d1-72b6-42f3-9549-1d90923b0277">
