### ISSUE TITLE
Kartaview not panning across entire photo

### ISSUE THREAD

**Issue by brian-luff** [facebook/Rapid#1535]
### Description

Kartaview is not able to pan across the entirety of a 360 degree photo.

### Screenshots

![image](https://github.com/user-attachments/assets/f115cc08-16c0-4b24-ab08-884e381cbcb7)

### Version

2.4.0-pre.0

### What browser are you seeing the problem on? What version are you running?

Firefox v130.0

### The OS you're using

mac

### Steps to reproduce

1. Go to https://rapideditor.org/canary#map=19.00/41.91031/12.50307&background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&photo=kartaview/1391643985&photo_overlay=kartaview&poweruser=true
2. Try to pan photo that pops up

### The browser URL at the time you encountered the bug

https://rapideditor.org/canary#map=19.00/41.91031/12.50307&background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&photo=kartaview/1391643985&photo_overlay=kartaview&poweruser=true

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0

**Comment by bhousel** [comment]
Yep, this is expected - switching to the Pannellum viewer is the remaining part of #1510
