### ISSUE TITLE
Kartaview partially fixed

### ISSUE THREAD

**Issue by brian-luff** [facebook/Rapid#1537]
### Description

When enabling Kartaview, it used to report a bad 400 report instead of loading the frame. Now it loads the frame but as a still instead of a 360 photo.

### Screenshots

![image](https://github.com/user-attachments/assets/2e27ab6f-424b-4726-9d85-120ba1f32016)

### Version

2.4.0-pre.0

### What browser are you seeing the problem on? What version are you running?

Firefox v130.0

### The OS you're using

mac

### Steps to reproduce

1. Load 
![image](https://github.com/user-attachments/assets/00d3efe2-ad16-489f-88ba-355a4da554ca)
2. Try to pan 360 photo.

### The browser URL at the time you encountered the bug

https://rapideditor.org/canary#map=19.00/41.91031/12.50307&background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&photo=kartaview/1391643985&photo_overlay=kartaview&poweruser=true

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0

**Comment by bhousel** [comment]
Yes, switching the viewer code so it can pan around in 360° is #1510
