### ISSUE TITLE
Traffic Signs and Detected Objects Overlapping

### ISSUE THREAD

**Issue by JessHed** [facebook/Rapid#1538]
### Description

While Traffic Sign icons overlapping other sign icons appear to have been resolved, Traffic Signs and Detected Objects are still overlapping each other. 

### Screenshots

![Screenshot 2024-09-06 at 2 54 31 PM](https://github.com/user-attachments/assets/edb55a60-7dc1-47f3-90e0-f01c6bad6a7a)
![Screenshot 2024-09-06 at 2 54 46 PM](https://github.com/user-attachments/assets/f95d04d9-3789-4c22-8adf-f0e6d1901934)
![Screenshot 2024-09-06 at 2 32 52 PM](https://github.com/user-attachments/assets/b5205988-c6ac-4f27-8510-e25d43af259a)
![Screenshot 2024-09-06 at 2 33 02 PM](https://github.com/user-attachments/assets/010e97a5-ecac-4e0d-a8dc-10a831d66941)

### Version

2.4.0-pre.0

### What browser are you seeing the problem on? What version are you running?

Edge v128.0

### The OS you're using

mac

### Steps to reproduce

1. Go to 29.7384582, -95.3718545
2. Enable detected Objects and Traffic signs in Photo Overlay
3. Overlap will be visible

### The browser URL at the time you encountered the bug

https://rapideditor.org/canary#map=22.36/29.73842/-95.37183&background=Bing&datasets=fbRoads,msBuildings&detection=mapillary-signs/619431892349191&disable_features=boundaries&photo=mapillary/494443661857961&photo_overlay=mapillary,mapillary-signs

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0

**Comment by bhousel** [comment]
Good catch, the detected objects and signs are in 2 different spatial indexes.. I'll check it, we should probably not allow a sign and an object to be in exactly the same place.

**Comment by bhousel** [comment]
In 74758b6  I made it so that 'traffic_signs' and 'detections' are now both stored in the 'detections' cache.

This will allow the code that prevents coincident detections (#1516) to keep them from overlapping.
