### ISSUE TITLE
Overlap between traffic signs and detected objects

### ISSUE THREAD

**Issue by bsidhuFB** [facebook/Rapid#1541]
### Description

Mapillary detected objects overlap with detected objects

### Screenshots

<img width="1136" alt="Screenshot 2024-09-06 at 3 56 33 PM" src="https://github.com/user-attachments/assets/846245a4-49c7-494f-a200-9fb849f012f2">
<img width="1243" alt="Screenshot 2024-09-06 at 3 56 43 PM" src="https://github.com/user-attachments/assets/650d3174-2e94-4c9b-95fb-119bb25c2bdc">

### Version

2.4.0-pre.0

### What browser are you seeing the problem on? What version are you running?

Chrome v128.0

### The OS you're using

mac

### Steps to reproduce

1. go to 37.578070, -122.047300
2. turn on both detected objects and traffic signs
3. toggle traffic signs

### The browser URL at the time you encountered the bug

https://rapideditor.org/canary#map=21.45/37.57804/-122.04730&background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&photo_overlay=mapillary,mapillary-signs

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

**Comment by bhousel** [comment]
thanks!  yes this is also #1538
