### ISSUE TITLE
ImproveOSM features remain though they are stated to have been removed

### ISSUE THREAD

**Issue by brian-luff** [facebook/Rapid#1543]
### Description

"ImproveOSM issues" remains as a button in Map Data tab. Button should be removed.

### Screenshots

![image](https://github.com/user-attachments/assets/ad394ea4-cdb2-42a2-9c0a-9d66460a1c46)

### Version

2.3.2

### What browser are you seeing the problem on? What version are you running?

Firefox v130.0

### The OS you're using

mac

### Steps to reproduce

1. Go to editable page in Rapid
2. Open Menu
3. Go to Map Data tab

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#map=17.13/39.07537/-108.50415&background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&overlays=osm-gps,US-TIGER-Roads-2020

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0

**Comment by bhousel** [comment]
Please test on Canary:
https://rapideditor.org/canary
