### ISSUE TITLE
Allow Rapid to work in Sandbox

### ISSUE THREAD

**Issue by brian-luff** [facebook/Rapid#1545]
### Description

Issue 1482 says it has resolved the issue, but no button in the menu was found to toggle Sandbox mode.

### Screenshots

No button available

### Version

2.3.2

### What browser are you seeing the problem on? What version are you running?

Firefox v130.0

### The OS you're using

mac

### Steps to reproduce

1. Go to menu
2. Button is missing from UI

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#map=2.00/7.7/29.9&background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0

**Comment by bhousel** [comment]
That's not what #1482 is about.  There's no button.
