### ISSUE TITLE
Add zoom level display as part of UI

### ISSUE THREAD

**Issue by brian-luff** [facebook/Rapid#1546]
### Description

This is a request for some kind of display for the zoom level on the UI. 

### Screenshots

Somewhere in this region is where I would suggest.

![image](https://github.com/user-attachments/assets/722d54e8-0462-4491-967f-5083d2252efd)

### Version

2.3.2

### What browser are you seeing the problem on? What version are you running?

Firefox v130.0

### The OS you're using

mac

### Steps to reproduce

1. No view of display available.

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#map=2.00/0.0/0.0&background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0

**Comment by bhousel** [comment]
The URL shows the zoom level.

**Comment by VLD280** [comment]
While the zoom level is visible in the URL, it would be a real quality of life improvement to have it integrated into the UI with the ability to manually set a custom zoom level. I think there are plenty of reason an editor would want more manual control over their zoom, and having to tinker with the URL is just not a pleasant user experience. Just today, I have accidentally mangled or deleted the page URL several times while trying to set custom zoom levels.
