### ISSUE TITLE
Move tool not functioning

### ISSUE THREAD

**Issue by vld165** [facebook/Rapid#1549]
### Description

When attempting to move a feature, the move tool is unresponsive

### Version

2.4.0-pre.0

### What browser are you seeing the problem on? What version are you running?

Chrome v128.0

### The OS you're using

mac

### Steps to reproduce

Right click on feature
select move tool
Tool unresponsive

### The browser URL at the time you encountered the bug

https://rapideditor.org/canary#map=20.27/41.76192/-71.35177&background=EsriWayback_2014-02-20&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w1314676610

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

**Comment by bhousel** [comment]
Closing, as this seems to be working in latest canary..
