### ISSUE TITLE
Rapid assist obscuring imagery

### ISSUE THREAD

**Issue by VLD280** [facebook/Rapid#1553]
### Description

Rapid Assist features begin rendering at zoom 14.65. This zoom level is much too low to reasonably edit most features so they just obscure the imagery and other map data. Once RA features have loaded, they are visible and selectable until you zoom lower than 11.7. Even if you are actively using Rapid assist, having the features appear on top of imagery and map data at these lower zoom level just clutters the map. This issue seems similar to what was documented in issue #1391 [https://github.com/facebook/Rapid/issues/1391#issue-2269249042](url). 

### Screenshots

![Screenshot 2024-09-10 at 3 19 42 PM](https://github.com/user-attachments/assets/040051a4-a22d-488c-aa31-a4454184471f)
![Screenshot 2024-09-10 at 4 11 53 PM](https://github.com/user-attachments/assets/cc6fd457-c4ee-432a-a857-f37cc8bb6a5d)

### Version

2.4.0-pre.0

### What browser are you seeing the problem on? What version are you running?

Firefox v130.0

### The OS you're using

mac

### Steps to reproduce

1. Zoom in past Z14.65 to trigger RA feature rendering
2. Zoom out as far as Z11.7
3. RA feaures are still present and selectable 

### The browser URL at the time you encountered the bug

https://rapideditor.org/canary#map=14.63/39.1679/-108.6574&background=MCGIS-County-Valleywide-Imagery-2024&datasets=fbRoads,msBuildings&disable_features=boundaries

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0

**Comment by bhousel** [comment]
Thanks for reporting, I agree that like with #1391, these issues are already covered in other open issues that we're aware of.
