### ISSUE TITLE
Inspect button is gone.

### ISSUE THREAD

**Issue by VLD280** [facebook/Rapid#1555]
### Description

I am submitting this report because my testing documentation explicitly indicates that the "Inspect" button should be present. The left hand menu for searching and editing can still be minimized and maximized by clicking the thin bar on the right-hand edge, but the inspect button that is present in the current public version of Rapid  does not appear to be in this test version.

### Screenshots

https://github.com/user-attachments/assets/33be0868-9fde-464f-8120-26969b1b38ca

### Version

2.4.0-pre.0

### What browser are you seeing the problem on? What version are you running?

Firefox v130.0

### The OS you're using

mac

### Steps to reproduce

1. Open Rapid in firefox
2. click the thin bar at the right edge of the left-hand menu to close it.
3. click the thin bar on the left hand edge of the window to re-open the left-hand menu

### The browser URL at the time you encountered the bug

https://rapideditor.org/canary#map=19.54/39.07594/-108.48493&background=MCGIS-County-Valleywide-Imagery-2024&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w-4

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0

**Comment by bhousel** [comment]
Yep, we removed that button in #1497, since uses can now click on the resizer to accomplish the same thing.
