### ISSUE TITLE
9/10/24 testing conclusion

### ISSUE THREAD

**Issue by VLD280** [facebook/Rapid#1556]
### Description

This report is to document that overall Rapid in the Firefox browser felt like it performed below what I expected mainly in terms of responsiveness. I found that even at zoom levels as high as 18+, panning and zooming felt very laggy and difficult to use. At Z17, the experience was significantly worse. Just trying to move from one part of Grand Junction to the another is very difficult and slow. Out at Z16, which is a level I might use to assess  large scale features and road networks, I can't pan the map at all and zoom has a significant delay. At this level, even other part of the UI, like the menus, start lagging.

### Version

2.4.0-pre.0

### What browser are you seeing the problem on? What version are you running?

Firefox v130.0

### The OS you're using

mac

### Steps to reproduce

1. Go to Grand Junction Colorado
2. start at zoom level 19
3. zoom out
4. at various levels, attempt to pan  and perform other actions on the map
5. observe how quickly performance drops off

### The browser URL at the time you encountered the bug

https://rapideditor.org/canary#map=18.19/39.06967/-108.56208&background=MCGIS-County-Valleywide-Imagery-2024&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w497023531

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0

**Comment by bhousel** [comment]
Thanks for your feedback, we're aware that we have a bunch of work to do still to improve the performance of busy scenes.
