### ISSUE TITLE
Adding Notes

### ISSUE THREAD

**Issue by tomidire** [facebook/Rapid#1558]
### Description

Great feature - pointing out a small observation:
"To add a new note, press the  Note button on the toolbar above the map, or press the shortcut key N"

The Note button is not automatically available in the menu button on the toolbar above the map for Google Chrome/Windows. Is it supposed to be automatically available at the top? I can only enabled it using 'shift + N'. 'CapsLock + N' or just 'n' will not enable it. 

### Screenshots

![image](https://github.com/user-attachments/assets/96fc156d-4f3e-486b-b307-355eb9ddc382)

### Version

2.4.0-pre.0

### What browser are you seeing the problem on? What version are you running?

Chrome v128.0

### The OS you're using

win

### Steps to reproduce

1. Select shift + N to start a new note which is slightly different from instructions

### The browser URL at the time you encountered the bug

https://rapideditor.org/canary#map=19.00/33.76099/-84.38890&background=EsriWayback_2024-08-15&datasets=fbRoads,msBuildings&disable_features=boundaries

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

**Comment by bhousel** [comment]
Yes good catch - we should probably update the docs here.

**Comment by bhousel** [comment]
Looks like this now:

<img width="356" alt="Screenshot 2024-09-11 at 3 55 12 PM" src="https://github.com/user-attachments/assets/6b9cea78-a61c-494e-9b0d-27d75ca68bc2">
