### ISSUE TITLE
Rapid 2.4 exceeds 150MB; JSDelivr refuses to serve package, breaking `latest` example and MapRoulette integration

### ISSUE THREAD

**Issue by jake-low** [facebook/Rapid#1561]
### Description

The URL https://cdn.jsdelivr.net/npm/@rapideditor/rapid@2.4/dist/rapid.js returns a 403 error with the following message:

```
Package size exceeded the configured limit of 150 MB.
```

Rapid 2.3's `dist/rapid.js` was only ~5MB, so perhaps this large increase is the result of a packaging error? For example dev dependencies getting included in the build by accident, or some large static asset being unintentionally inlined into the JS code?

In any case, since rapid@2 (`https://cdn.jsdelivr.net/npm/@rapideditor/rapid@2/dist/rapid.js`) now returns this error, the [`latest` example](https://rapideditor.org/canary/examples/latest/latest.html) is broken, as is the embedded Rapid editor in MapRoulette. You can see the latter problem by visiting a challenge page such as [this one](https://maproulette.org/challenge/49104/task/248076436) and toggling "Edit Mode" on, or by visiting https://maproulette.org/static/rapid-editor.html which is the HTML page that we serve in the embedded iframe.

### Version

2.4.0

### What browser are you seeing the problem on? What version are you running?

Firefox 130, Safari 17.6, Chrome 128

### The OS you're using

MacOS 14.6.1

### Steps to reproduce

1. Run `curl -i https://cdn.jsdelivr.net/npm/@rapideditor/rapid@2/dist/rapid.js`
2. Observe 403 error and message "Package size exceeded the configured limit of 150 MB."

### The browser URL at the time you encountered the bug

- https://maproulette.org/challenge/49104/task/248076436
- https://rapideditor.org/canary/examples/latest/latest.html

**Comment by bhousel** [comment]
Thanks for letting me know - I didn't realize that there was a limit, but now I see it also on JSDelivr's documentation page here:  https://www.jsdelivr.com/documentation#id-restrictions

With #1482, we started including everything in the `/dist` folder that anyone might need to run Rapid even without a CDN.  This is what made the package so much larger this time..  The actual `rapid.js` file hasn't changed much, but our package now includes things like Mapillary and MapLibre under `/dist/data/modules/` :

```sh
~/Projects/rapid/dist % ls -lh
903K    esbuild.json
2.5K    index.html
307B    land.html
158K    rapid.css
4.8M    rapid.js
9.5M    rapid.js.map
4.9M    rapid.legacy.js
9.5M    rapid.legacy.js.map
2.5M    rapid.legacy.min.js
9.6M    rapid.legacy.min.js.map
2.4M    rapid.min.js
9.5M    rapid.min.js.map

~/Projects/rapid/dist %  du -h
108K	./img/pattern
 11M	./img
 32K	./examples/iframe
4.0K	./examples/latest
 44K	./examples
 44M	./data/l10n
 12K	./data/modules/wmf-sitematrix
448K	./data/modules/id-tagging-schema
136K	./data/modules/pannellum
 18M	./data/modules/maplibre-gl
 15M	./data/modules/name-suggestion-index/presets
 25M	./data/modules/name-suggestion-index
384K	./data/modules/osm-community-index
 23M	./data/modules/mapillary-js
 67M	./data/modules
123M	./data
187M	.
```

So I will think of a way to publish this differently - the situation where people need theses dependencies for a no-CDN sandbox is special (maybe I can remove all the sourcemaps and extra files from here, that's what takes up most of the space).

**Comment by jake-low** [comment]
Thanks for the explanation. Makes sense that for some use cases you'd would want all of the dependencies in `dist/` if you were serving them from your own infrastructure rather than a CDN. It's too bad that JSDelivr restricts the total package size and not just the file size (since I see now that `dist/rapid.js` is still a modest 5MB), but understandable as they're offering a free service after all.

I think in the short term we will pin MapRoulette to use Rapid 2.3, since that version still works on JSDelivr. Happy to help brainstorm a better solution next week.

**Comment by bhousel** [comment]
> I think in the short term we will pin MapRoulette to use Rapid 2.3, since that version still works on JSDelivr. Happy to help brainstorm a better solution next week.

I actually realized I can just publish the `dist/` folder and it should be ok for the sorts of uses people will use the package for.  It won't include tests or svg files, etc.

`npm publish --dry-run` tells me it will be  43.3 MB
I'm going to publish a 2.4.1 in a few minutes, and that should fix the issue  🤞

**Comment by bhousel** [comment]
hmmm. 2.4.1 is much smaller but still showing up as over the limit - maybe they are going by the unpacked size 🤔 

```
npm notice package size: 43.3 MB
npm notice unpacked size: 194.8 MB
```

**Comment by bhousel** [comment]
> I think in the short term we will pin MapRoulette to use Rapid 2.3, since that version still works on JSDelivr. Happy to help brainstorm a better solution next week.

This sounds like a good idea for now , thanks for understanding! 😄

**Comment by bhousel** [comment]
Hey @jake-low , I just trimmed down out package a bit more , published a v2.4.2, and the CDN is happy again.
I tested it with the [latest example](https://rapideditor.org/canary/examples/latest/latest.html) ...

I'll keep this issue open and work on publishing a separate package that includes all the extra stuff needed for #1482

**Comment by jake-low** [comment]
Thanks @bhousel! I will deploy an update to un-pin the Rapid version in MapRoulette soon. Looking forward to using the new street level imagery features 🙂

**Comment by bhousel** [comment]
I ended up doing this:
- Removed the code to copy these dependencies into `dist/data/modules`
- Added some instructions to our release checklist to check the package size before publishing
- Made a new project https://github.com/rapideditor/rapid-standalone for anyone who needs to run Rapid this way.
