### ISSUE TITLE
The "G" hotkey, that is supposed to highlight unsaved features, does not work.

### ISSUE THREAD

**Issue by brian-luff** [facebook/Rapid#1565]
### Description

The "G" hotkey is listed in the hotkeys in the menu that appears after you press "?". It appears to have no functionality when pressed.

### Screenshots

![image](https://github.com/user-attachments/assets/0be83720-67c5-4282-b0c6-e6b891610901)

This is after I've pressed the "G" button and there is no change. 

### Version

2.4.0

### What browser are you seeing the problem on? What version are you running?

Chrome v128.0

### The OS you're using

mac

### Steps to reproduce

1. Have data on the screen.
2. Modify data
3. Press "G"
4. It should be highlighted but isn't

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#map=19.00/39.49795/-0.38705&background=PNOA-Spain-TMS&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w1315417795

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

**Comment by bhousel** [comment]
Thanks for reporting, this is also tracked on #509
