### ISSUE TITLE
Search feature disappeared when you open the Rapid App 

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#1566]
### Description

Since the change in format, several features in the app seems to work "weird", but the main one is that the SEARCH feature disappeared when you open the app

### Screenshots

![Screenshot (267)](https://github.com/user-attachments/assets/6b6b7089-f9cd-402f-8e2e-0c93e328bbda)

### Version

2.4.0

### What browser are you seeing the problem on? What version are you running?

Edge Version 128.0.2739.79 (Official build) (64-bit)

### The OS you're using

Windows 

### Steps to reproduce

Just open the Rapid app

### The browser URL at the time you encountered the bug

No browser link visible from the app version

**Comment by bhousel** [comment]
Thanks for reporting, this probably also regressed in #1497.
