### ISSUE TITLE
Search bar is missing

### ISSUE THREAD

**Issue by tomidire** [facebook/Rapid#1571]
### Description

It looks like the 'search features' tool in the left-hand pane is missing when you initially open Rapid. The tool is available after you click a feature, but not when you first open Rapid. 

### Screenshots

![image](https://github.com/user-attachments/assets/76cdbc7c-86d8-4f85-92a4-654f6fddaad5)
![image](https://github.com/user-attachments/assets/d974bec7-bd1a-439e-819e-cd352ff8e457)

### Version

2.4.0

### What browser are you seeing the problem on? What version are you running?

Chrome v129.0

### The OS you're using

win

### Steps to reproduce

1. Open Rapid
2. If you want to use the search feature tool to view New York City, select a random feature in Rapid
3. Then search feature tool become available

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#map=4.00/35.47/-85.34&background=EsriWayback_2024-08-15&datasets=fbRoads,msBuildings&disable_features=boundaries

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

**Comment by bhousel** [comment]
Thanks for reporting, this is #1566
