### ISSUE TITLE
Rapid stopped working

### ISSUE THREAD

**Issue by misibacsi** [facebook/Rapid#1576]
### Description

I use Rapid every day. Yesterday it worked, today it stopped working.

### Screenshots

![2024-10-04 Rapid stopped working](https://github.com/user-attachments/assets/1da61f25-3f0b-4969-8169-756fa91607f8)

### Version

2.4.0

### What browser are you seeing the problem on? What version are you running?

Firefox v131.0, Opera 113.0.5230.142, Chrome 129.0.6668.90

### The OS you're using

win11

### Steps to reproduce

Go to a settlement, where not all buildings and roads exist in OSM.

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#map=17.70/47.74723/22.11672&background=FOMI_2011_2014&datasets=fbRoads,msBuildings&disable_features=points,building_parts,indoor,landuse,pistes,aerialways,power,past_future,others&id=r1447714

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0

**Comment by jjiglesiasg** [comment]
I report the same issue from #Bolivia, since 3 or 4 hours all Rapid AI data disappeared and editing is quite slow and even erratic.

**Comment by misibacsi** [comment]
yes, thx!

**Comment by jjiglesiasg** [comment]
I raise again the issue because the AI suggested Road Data has disappeared completely. Just Buildings are working 2024-10-17
