### ISSUE TITLE
Add SpectorJS WebGL debugging tool

### ISSUE THREAD

**Issue by bhousel** [facebook/Rapid#1581]
This issue is just to flag that @Bonkles and I added the [SpectorJS](https://github.com/BabylonJS/Spector.jshttps://github.com/BabylonJS/Spector.js) WebGL debugging tool as part of #1495. 

For now this tool is only available in dev builds of Rapid and needs to be enabled manually via the browser dev console. 
The default capturing UI is a bit messy, but we can improve it later - this is a first step towards getting a better understanding of how our code is using the GPU, and will help us a lot in solving [rendering performance issues](https://github.com/facebook/Rapid/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-performance).

### How it works

1. Run this command in the browser dev console to enable the SpectorJS Capture UI:

```js
> context.systems.ui.spector.toggle()
```

2. You'll see this popup that allows Spector to record a trace.  The red circle is the "record" button.

<img width="1325" alt="Screenshot 2024-10-08 at 9 31 39 AM" src="https://github.com/user-attachments/assets/b3a08cdc-b3a5-4c41-9b45-849e54272120">

3. Press the record button, then mouse over the map to trigger a redraw.  After recording is finished (usually around 10 seconds), you'll see the Result UI:

<img width="1654" alt="Screenshot 2024-10-08 at 9 27 47 AM" src="https://github.com/user-attachments/assets/f85bc277-ff2c-4016-86f9-6c44dc59db59">

This allows us to inspect every WebGL command that is sent to the GPU and see all kinds of details about the WebGL environment.

**Comment by eneerhut** [comment]
@bhousel my dev console doesn't like it. Am I doing this wrong?
<img width="603" alt="image" src="https://github.com/user-attachments/assets/af6117c7-5b49-4340-9295-f2b6489ffeb8">

**Comment by bhousel** [comment]
> my dev console doesn't like it. Am I doing this wrong?

This won't work in canary yet, but we can try it again once #1495 merges (today hopefully!)

**Comment by eneerhut** [comment]
Thanks! I need to remember branches.

**Comment by bhousel** [comment]
I just merged the pixi v8 work and this does work in canary now! 👍
