### ISSUE TITLE
Mapillary image positions -> Corrected or original

### ISSUE THREAD

**Issue by eneerhut** [facebook/Rapid#1582]
### Description

There is [some user feedback](https://forum.mapillary.com/t/wrong-position-of-images-after-mapillary-calculation/8417/2) here that we might want to use the original GPS positions rather than Mapillary's computed positions. It seems we are using the latter now. Just filing this for consideration. We need a better sense of which positions are more accurate on average and use that as the image location.

![image](https://github.com/user-attachments/assets/44ec0c60-62a7-49fd-8ef9-fac9a375a4d9)
Original

![image](https://github.com/user-attachments/assets/6ff77c22-3f98-4a31-9bb6-72623b780bb9)
Corrected

**Comment by tsmock** [comment]
What I do in the JOSM Mapillary plugin is look at the delta between the computed and reported location; if the delta is too big (>6m), I just use the reported location. This only happens after I download the sequence though -- AFAIK, the computed location vector tiles don't have the non-computed location.

This fixes issues like this: https://rapideditor.org/edit#map=19.04/39.10021/-108.34914&background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries , but only after the user clicks on the sequence.

**Comment by gchapbbhn** [comment]
Hello,
I'm not sure I understand how you do it?
I loaded images into Mapillary (with an RTK position), but after the recalculated position is totally wrong and it's a problem for me...
Here is the description of my problem:
https://forum.mapillary.com/t/wrong-position-of-images-after-mapillary-calculation/8417

**Comment by eneerhut** [comment]
I have seen a few examples recently where the computed positions saved the day for both the compass angle and the image location. I'm don't think a switch to original positions would be a net benefit. Here are two examples:
1. [Example 1.](https://www.mapillary.com/app/user/bruno360?lat=59.20352351333301&lng=17.797899740000048&z=18.549110350044277&focus=map&pKey=1092484215383234&fbclid=IwZXh0bgNhZW0CMTEAAR11ETUmTZkek424wAy-JTGVoybJf5TCD3Mj3QV6l6ePNqdlFcMV7hMvJy8_aem_I-oSeLM5bHxtMqQm6C2PCA)
2. [Example 2.](https://www.mapillary.com/app/?lat=42.39468927032976&lng=-71.14361629896456&z=18.404632452783087&pKey=566348845730867&focus=map&fbclid=IwZXh0bgNhZW0CMTEAAR1r1vrVvXQQim8L08iLdAmCUdlH_0P24LiHVE_0MMiB3iy5ll-shgV1Axc_aem_WaN8G4rlKbBNguGKbl0MBA)

@gchapbbhn it sounds like the best course of action here is to figure out why Mapillary is struggling to compute from the imagery, despite or perhaps because of RTK positioning.

**Comment by bhousel** [comment]
Hey all, sorry I forgot to comment on this issue before.
I switched from the original positions to the computed positions in 224ed834 because I was doing a lot of testing with the Mapillary detections (objects and signs) and the computed positions and camera angles seemed to better match up with the detections.  My thinking is that, while all the viewcone camera angles are approximate, we want to avoid showing the user viewcones that are really pointing in the wrong direction.

I don't have an opinion about which is better, but I see these as the options for us:
* use original positions
* use computed positions
* some mix of the two approaches (original positions + computed camera angles?)
* do nothing and hope the computed positions improve

In any case 224ed834 is pretty simple and contains the code pointers for what we would need to change.

**Comment by bhousel** [comment]
Followup on this - I switched the code back to using the original positions in c8fde605, but left plenty of comments in the code in case we decide to switch to the computed values once the accuracy of the computations improve.

**Comment by eneerhut** [comment]
@bhousel to make sure I am following, was this the flow? original -> computed (https://github.com/facebook/Rapid/commit/224ed8347eeda8c489ef10b2dda9ca6e39c08f21) -> original (https://github.com/facebook/Rapid/commit/c8fde605a583186bd2ff0b732f73c6559e0b8b37)?

It seems to depend on the area we're looking at, so we can collate feedback in this issue and see if an obvious winner emerges.

**Comment by bhousel** [comment]
> @bhousel to make sure I am following, was this the flow? original -> computed ([224ed83](https://github.com/facebook/Rapid/commit/224ed8347eeda8c489ef10b2dda9ca6e39c08f21)) -> original ([c8fde60](https://github.com/facebook/Rapid/commit/c8fde605a583186bd2ff0b732f73c6559e0b8b37))?

Yes 👍  These are pretty minor changes, so we can always switch it back to computed later if we decide to.

**Comment by eneerhut** [comment]
Great. Will keep an eye on feedback then.
