### ISSUE TITLE
Rapid Stop Working for AI suggested Roads

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#1587]
### Description

The AI suggested road data are not showing, just the building data

### Screenshots

![Screenshot (297)](https://github.com/user-attachments/assets/25e4373a-1e82-43fe-ad78-827ba94300e7)

### Version

2.4.0

### What browser are you seeing the problem on? What version are you running?

Version 129.0.2792.89 (Official build) (64-bit)

### The OS you're using

Win10

### Steps to reproduce

Open Rapid in the URL area and you will see no road suggested data anywhere.

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid#map=16.36/-15.40573/-67.98964&background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&poweruser=true

**Comment by bhousel** [comment]
Thanks for flagging @jjiglesiasg  - this is also reported on #1584, we're working on restoring them, but I don't have any other information right now - please check on that issue for any updates.
