### ISSUE TITLE
Roads Dataset Not Loading?

### ISSUE THREAD

**Issue by jwtrull** [facebook/Rapid#1590]
### Description

The roads dataset has recently stopped loading for me. Seeing plenty of the buildings dataset, but none of the roads.

### Version

2.4.0

### What browser are you seeing the problem on? What version are you running?

Chrome v129.0

### The OS you're using

win

### Steps to reproduce

I've tried toggling on/off all rapid features and the individual roads dataset. I've tried restarting instance, as well as logging in/out of OSM

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#map=15.04/47.5352/-113.6879&background=EsriWorldImageryClarity&datasets=fbRoads,msBuildings&disable_features=boundaries&overlays=StravaHeatmapAll,osm-gps&poweruser=true

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

**Comment by bhousel** [comment]
Thanks for reporting @jwtrull , this is actually being tracked on #1584
(I've updated the issue title to make it more clear that it's about the roads dataset)
