### ISSUE TITLE
Don't allow side panes to cover info panels

### ISSUE THREAD

**Issue by bhousel** [facebook/Rapid#1593]
We got some feedback about this on Discord yesterday - it's a thing I wasn't aware was causing issues for some of our users.

Currently when you expand a pane, such as Background or Issues, it can cover up other elements floating over the map.

![cover panel](https://github.com/user-attachments/assets/8bb97815-2308-46ff-9389-126fe33ae894)

**Comment by bhousel** [comment]
I changed it so that the info cards now float over the side panes.
I also added a bit of extra margin at the bottom of the pane content, so that you can always scroll down to the end and interact the pane, even if an info card is floating above it.

![info panel2](https://github.com/user-attachments/assets/195a7fde-9f86-492d-b117-56377eee0a32)

**Comment by boothym** [comment]
Thanks for sorting it, though a bit strange to have different functionality to iD when (I assume) you were the one who added it there 😝
