### ISSUE TITLE
Search feature does not appear on the left tool bar

### ISSUE THREAD

**Issue by sturksever** [facebook/Rapid#1596]
### Description

Search feature does not appear on the left tool bar after loading rapideditor.org/edit

### Screenshots

![Screenshot 2024-10-28 at 13 13 50](https://github.com/user-attachments/assets/734cab31-9015-4d1b-a6cd-618a7648ec2d)

### Version

2.4.0

### What browser are you seeing the problem on? What version are you running?

Chrome 

### The OS you're using

MacOS 14.6.1 (23G93)

### Steps to reproduce

1. Go to Rapideditor.org/edit
2. Load the page 
3. Search feature is not available 

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#map=2.00/0.0/0.0&background=EsriWorldImagery&datasets=fbRoads,msBuildings&disable_features=boundaries

**Comment by bhousel** [comment]
Hey @sturksever this was actually fixed already, #1568 and #1571
I can release a 2.4.1 patch that includes the fix, since it is affecting a bunch of users.
