### ISSUE TITLE
Offer different suggestions for road type

### ISSUE THREAD

**Issue by Spanholz** [facebook/Rapid#16]
Currently all "Used features" are added as Residential roads with the tag `highway=residential`. It would be better to have a choice between the other kinds of `highway=*`-tags. 

Other kinds of roads that are often not mapped but identified by the AI are:
- `highway=track` for forest and agriculture roads
- `highway=service` for service roads for example in industrial areas
-  `highway=unclassified` for rural roads that are not residential roads

**Comment by gaoxm** [comment]
Thanks for sharing the feedback @Spanholz ! We also use AI-based methods for detecting road types, and "residential" is actually not the only tag we generate - e.g. some of the AI roads at [this location](https://mapwith.ai/rapid#background=Maxar-FB&disable_features=boundaries&map=17.00/3.69094/103.33490) are auto-tagged with "track".

However tagging is a much harder problem to solve than road identification, and as you suggested the auto-generated tags are sometimes wrong. So mappers may need to change the suggested tag upon adding the RapiD road. We are actively working on making the AI predictions better, and will keep updating the AI roads dynamically as more progress is made.

**Comment by Spanholz** [comment]
Thanks for the clarification that the road type is also part of the AI detection. I only saw residential roads for now. Maybe present the AI result first and show some other road types to choose from as alternatives. That way it's faster to add the correct road type.

**Comment by gaoxm** [comment]
Thanks for the suggestion! In slightly longer term, we do plan to show a list of possible types for users to choose from, ordered by prediction confidence.

One useful thing for now is that you can use the ["Shift + C" hotkey](https://github.com/facebookmicrosites/Open-Mapping-At-Facebook/wiki#hot-keys) to quickly rotate through several common types ;)

**Comment by bhousel** [comment]
It seems ok to close this - the <kbd>Shift</kbd>+<kbd>C</kbd> hotkey to cycle tags works pretty well when adding an AI detected road and you want to adjust its type.
