### ISSUE TITLE
AI suggested data reappears even after being accepted and uploaded already  

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#1605]
### Description

These buildings data was already accepted and uploaded and days after is being shown again for no reason

### Screenshots

![Screenshot (305)](https://github.com/user-attachments/assets/dc88b358-8136-4cb6-8ca0-afbf25251f56)

### Version

2.4.3

### What browser are you seeing the problem on? What version are you running?

edge

### The OS you're using

Win10

### Steps to reproduce

1. Go to areas that data was accepted and uploaded (For Buildings)
2. You will find all data as not uploaded and suggested again
3. If you accept any of such data it will show you two buildings overlapping warnings

### The browser URL at the time you encountered the bug

No URL from the app, but the location is -17.1253509, -64.3456647

**Comment by bhousel** [comment]
Thanks for reporting, I'm seeing this too a lot lately, this is being tracked on #1295
