### ISSUE TITLE
Rendering freeze in RapiD Canary after clicking prompt to add kerb nodes to new crossing

### ISSUE THREAD

**Issue by nickrsan** [facebook/Rapid#1627]
### Description

If I go to add a new crossing with the lines preset, then click the prompt to connect it to the street, everything works normally. Then, I see the prompts to add kerb nodes (which I love), and when I click to add lowered kerb nodes, parts of the UI freeze while others remain responsive. The kerb nodes don't appear to be added, but the blue prompt box on the left freezes. Nothing further renders in the map, as you can see in the recording, but if I *click* on the map, the sidebar correctly registers what I've clicked on and shows the details, as you can also see.

The location/imagery, etc, I'm editing in the video is https://rapideditor.org/canary#map=21.42/38.52511/-121.51790&background=EsriWorldImagery&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w774903612

https://github.com/user-attachments/assets/d8a7009a-5d51-4011-a038-e65cb2b577ec

### Version

canary

### What browser are you seeing the problem on? What version are you running?

Firefox 133.0

### The OS you're using

Win 11

### Steps to reproduce

1. Go to https://rapideditor.org/canary#map=21.42/38.52511/-121.51790&background=EsriWorldImagery&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w774903612
2. Add a line in a crosswalk
3. Choose the marked crossing (lines) preset
4. Click the prompt to join the crossing to Seamas Ave
5. Click to add lowered kerb nodes in the prompt

### The browser URL at the time you encountered the bug

https://rapideditor.org/canary#map=21.42/38.52511/-121.51790&background=EsriWorldImagery&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w774903612

**Comment by bhousel** [comment]
Thanks for reporting @nickrsan  it should be fixed in canary shortly.
This was a quick fix - when the crossing is connected to a sidewalk things were ok, but when the crossing was connected to nothing, the code should just modify the end nodes instead of looking for a connected sidewalk.

**Comment by nickrsan** [comment]
Awesome. I'll keep testing in canary when I edit next then. Thanks Bryan!
