### ISSUE TITLE
Add URL parameter for OSM notes

### ISSUE THREAD

**Issue by emersonveenstra** [facebook/Rapid#1630]
### Description

When editing a note from OSM.org, iD checks for `note=` in the query parameter, and will load the note in the sidebar, zoom to the note location, and turn on the OSM notes data layer on initial load. Would be nice for Rapid to do the same.

**Comment by bhousel** [comment]
Thanks @emersonveenstra  I agree we should have this - I really thought we had added support already  😆

**Comment by bhousel** [comment]
I added this today.. I made this work like the `maproulette` parameter from #1422

`&note=val`, where `val` can be `true` to enable the layer or can be a specific `noteID` to select it

Examples:  

`&note=true` - enable notes layer
https://rapideditor.org/canary#map=19.00/40.72943/-73.99722&note=true

-or- 

`&note=<noteID>` - enable notes layer and select this specific note
https://rapideditor.org/canary#map=19.00/40.72943/-73.99722&note=3473754

**Comment by emersonveenstra** [comment]
Awesome, thanks!
