### ISSUE TITLE
Background / other panels hidden behind settings pane

### ISSUE THREAD

**Issue by boothym** [facebook/Rapid#1633]
### Description

In iD, if you open the background settings pane (B) and then click Show Background Panel or Ctrl + Shift + B - the panel is shown to the left of the settings pane. Same goes for history, measurement etc.

However in Rapid, if you do the same then the background panel is hidden behind the settings pane (until you show history etc and it moves to the left and half is shown).

### Version

2.4.3

### Steps to reproduce

See above

### The browser URL at the time you encountered the bug

n/a

**Comment by bhousel** [comment]
Thanks for reporting, this is also #1593.  We allow these panels to float above the other content now so they aren't hidden - this fix will be in the upcoming 2.5 release, but you can try it out in our dev canary build:  https://rapideditor.org/canary
