### ISSUE TITLE
Some areas don't have suggested homes

### ISSUE THREAD

**Issue by leftger** [facebook/Rapid#1639]
### Description

When browsing Cypress, TX there's some areas where there should be suggested building footprints (residential homes) but nothing shows up.

### Screenshots

<img width="737" alt="Screenshot 2024-12-06 at 1 44 25 AM" src="https://github.com/user-attachments/assets/2692a870-a5fb-4273-814e-1d02a2d97220">

### Version

2.5.0-pre.0

### What browser are you seeing the problem on? What version are you running?

Safari v18.1

### The OS you're using

mac

### Steps to reproduce

Go to Cypress, TX, USA on rapideditor.org and look around Cypress Trace Dr.

### The browser URL at the time you encountered the bug

https://rapideditor.org/canary#map=18.00/29.98170/-95.67452&background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15

**Comment by bhousel** [comment]
Thanks for reporting - we did some digging today and it looks like Microsoft just doesn't have any buildings at this location.
You might be able to report the issue on their issue tracker here:
https://github.com/microsoft/GlobalMLBuildingFootprints

Here's a test query that returns an empty result in this part of the map:
https://buildingfootprintsapi.azurewebsites.net/api/BuildingFootprints?searchAreaWkt=POLYGON((-95.67672246969406%2029.980094038492073,%20-95.67672246969406%2029.982706238871366,%20-95.67184431755925%2029.982706238871366,%20-95.67184431755925%2029.980094038492073,%20-95.67672246969406%2029.980094038492073))

(re: #960 which contained some debugging steps for this issue and thanks @Bonkles for the pointers!)
