### ISSUE TITLE
Background Imagery Offset input inner rectangle click-and-drag text selection edits offset value

### ISSUE THREAD

**Issue by UW-Amy-Bordenave** [facebook/Rapid#1643]
### Description

Issue: In the Background > Imagery Offset section, click-and-drag to select the direct text entry input field (inner rectangle) acts as click-and-drag input to move the imagery (outer rectangle)

Expected Behavior: Click-and-drag in inner rectangle does not adjust offset value.

### Screenshots

![Rapid Issue 1 A](https://github.com/user-attachments/assets/c9044b7d-b26c-4762-a41a-6d729433fd62)
![Rapid Issue 1 B](https://github.com/user-attachments/assets/5b242a50-8819-42dc-b8e5-3aeea0b7b531)

### Version

2.4.3

### What browser are you seeing the problem on? What version are you running?

Firefox v133

### The OS you're using

Windows 10

### Steps to reproduce

1. Go to "Background Settings" > "Imagery Offset"
2. Click-and-drag within inner rectangle to select the text

An offset value is input when it should remain set to its existing value.

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#map=12.14/47.6076/-122.3421&background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&offset=-90.77,10.24

**Comment by bhousel** [comment]
Thanks for reporting!
I added a fix so that dragging in the `input` field won't adjust the offset anymore  👍

![drag offset](https://github.com/user-attachments/assets/3ebdedce-a2e1-4563-b6a7-439e27b7604b)
