### ISSUE TITLE
NAD dataset doesn't show up in canary

### ISSUE THREAD

**Issue by emersonveenstra** [facebook/Rapid#1653]
### Description

Enabling the NAD dataset doesn't display any of the dataset points, even though it does in 2.4.3.

### Version

canary

### Steps to reproduce

1. Go to https://rapideditor.org/edit#map=18.33/43.02353/-108.38127&background=Bing&datasets=e75b56f13b404d7d8b47ef8be1c619ec,fbRoads,msBuildings&disable_features=boundaries
2. Observe the NAD dataset points
3. Go to https://rapideditor.org/canary#map=18.33/43.02353/-108.38127&background=Bing&datasets=e75b56f13b404d7d8b47ef8be1c619ec,fbRoads,msBuildings&disable_features=boundaries
4. Observe the lack of NAD points

### The browser URL at the time you encountered the bug

https://rapideditor.org/canary#map=18.33/43.02353/-108.38127&background=Bing&datasets=e75b56f13b404d7d8b47ef8be1c619ec,fbRoads,msBuildings&disable_features=boundaries

**Comment by bhousel** [comment]
Thanks for catching @emersonveenstra  - I realize this regressed in #1642 
There is an extra step that we need to run for the Esri datasets where we fetch the dataset's schema from a different url.  This previously happened in the UI code, but now the responsibility for doing that step needs to move to the EsriService code.
