### ISSUE TITLE
Documentation for releases should be added to RELEASING.md

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#284]

**Comment by bhousel** [comment]
Just came across this issue - @Bonkles can you elaborate?
RELEASING.md is mostly just the sequence of commands to run on the repository to publish a release.  
Then I have a separate document for the internal steps needed to promote a release to a url like `/rapid`.

**Comment by Bonkles** [comment]
Given that I didn't explain myself AT. ALL in this bug, I'mma close it. I honestly don't know what the original issue was, but I think that the release process is working perfectly well now (esp since MR and TM are able to build with v2).
