### ISSUE TITLE
Using different imagery (Ortofotomozaika SR)

### ISSUE THREAD

**Issue by zdila** [facebook/Rapid#408]
Hello,

Is it possible to use different imagery or are you bound to Mapbox? In Slovakia we have imagery "Ortofotomozaika SR" which is  much more up to date, with much higher resolution and properly aligned. It is also allowed for OSM mapping and is already available in iD and JOSM.

If you can use it then I would like to have data for Slovakia. I can answer you any technical questions.

BTW Esri imagery uses the same images but they are of slightly lower resolution so maybe this could also be used.

And/or is the AI software available to run locally and generate the data on our own?

Thanks

**Comment by bhousel** [comment]
Sorry this issue has been open for so long..
To answer the questions..

We refresh the background imagery list whenever we release a new version of Rapid.
(lately this has been: patch release as needed, significant release once per quarter).

We have issue #270 open to allow users to adjust the alignment of the data layers separately from the imagery layers.  We haven't forgotten!

We can't support running the AI detections against different imagery right now or run locally - I actually don't know too much about how this process works, so I can't really offer guidance, sorry!
