### ISSUE TITLE
All Rapid Facebook Roads suggestions dissapeared

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/RapiD#434]
In the last few days all areas that I tryed to map there is NO faceboolk roads, just the microsoft buildings are suggested, I have tryed to toggle the features but not change

**Comment by bhousel** [comment]
Hey @jjiglesiasg .. I just checked and I am still seeing the Facebook Road suggestions (at least in Northern New Jersey).
Can you share the location of where you are mapping that you're not seeing any suggestions?

**Comment by jjiglesiasg** [comment]
Hi Bryan

 

Mostly of #Bolivia in South America

**Comment by bhousel** [comment]
Thanks for raising the issue @jjiglesiasg .. 

Just wanted to follow up - we found that the road data in Bolivia did not get added after a recent round of processing, and we're investigating the reason and will re-run the processing.

**Comment by jjiglesiasg** [comment]
Thanks Bryan, all road data has been missing at least 3 weeks, just in the very west of the country there are buildings suggestions otherwise nothing...

**Comment by jjiglesiasg** [comment]
Hi Brian, you menctioned that the missing data process for Bolivia will be re-run. When you expect that to happen? we have alredy more than a month without any data suggestion from Rapid. Thanks

**Comment by bhousel** [comment]
Sorry for the delay @jjiglesiasg.. 
I checked with the team that runs these, and they have a fix for the issue that is under review now.  Hopefully the roads will be back soon!

**Comment by jjiglesiasg** [comment]
Thanks Brian. The sooner the better

**Comment by jjiglesiasg** [comment]
24-May-2022: Still no road data suggestions on RapID for #Bolivia, the problem arise around 15 or March, still no solution? Please!!!

**Comment by Bonkles** [comment]
Hi @jjiglesiasg - We have partially unblocked the road predictions in bolivia and you should start seeing roads appear there (like this area near La Paz: https://mapwith.ai/rapid#background=Maxar-Premium&datasets=fbRoads&disable_features=boundaries&map=16.17/-16.61685/-68.21693). 

We'll continue to take a look to see if there are further gaps in coverage. Can you send me some URLs from RapiD of areas where you would expect to see road predictions? I can take a look specifically in those areas to see if there's something more going on.

**Comment by jjiglesiasg** [comment]
Hi Ben

 

Thanks I reviewed the area in the link that you share, and is working ok. Will let you know if anything Arise

 

Thanks and Best Regards

 

JJ

**Comment by jjiglesiasg** [comment]
Hi Ben and Bryan

The whole Center and East of #Bolivia seems to have no road suggestions at all.  Just in the West of the country nearby Peru

![Screenshot 2022-05-28 17 08 41](https://user-images.githubusercontent.com/22849578/170842948-33134fe3-9b0f-4ce0-9340-fc9ed5e6be7f.png)

**Comment by jjiglesiasg** [comment]
This area before this situation started,used to have Dozens of road suggestions. Now nothing

https://mapwith.ai/rapid#background=Maxar-Premium&datasets=fbRoads,msBuildings&map=16.25/-17.65303/-61.77664&photo_overlay=mapillary

However to the Very North of that area, miles away, yes there is some road  suggestions:

https://mapwith.ai/rapid#background=Maxar-Premium&datasets=fbRoads,msBuildings&map=16.50/-16.92910/-62.60418

**Comment by jjiglesiasg** [comment]
To the east of that city, nothing again:

https://mapwith.ai/rapid#background=Maxar-Premium&datasets=fbRoads,msBuildings&id=w985870109&map=14.75/-17.4013/-60.6312

**Comment by cbeddow** [comment]
@jjiglesiasg how does it look by now to you? I see here many roads (using the alpha link) https://mapwith.ai/rapid-v2-alpha#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=boundaries,past_future,others&id=w985870109&map=16.15/-17.41720/-60.64346

**Comment by bhousel** [comment]
closing here - we think this was fixed last year.
