### ISSUE TITLE
v2: Mapillary (…) styling + interaction

### ISSUE THREAD

**Issue by tordans** [facebook/RapiD#472]
The styling is not the same, yet, as on https://www.openstreetmap.org/edit#map=19/52.47348/13.44813.

And the interaction does not work, yet.

It also looks like not all features from iD are in Rapid; The UI looks different in iD ([Screenshot](https://user-images.githubusercontent.com/111561/167303169-ec12b36b-41da-4129-8481-8ae3ae6e8ca6.png)).

PS: Maybe also relevant: https://github.com/openstreetmap/iD/issues/9100

https://mapwith.ai/rapid-sotm-2022#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=boundaries&id=n3411198264&map=18.96/52.47342/13.44849

<img width="884" alt="image" src="https://user-images.githubusercontent.com/111561/167303100-918f041b-1aa8-41d0-ac8a-3f9352f6e758.png">

**Comment by Bonkles** [comment]
We're still working on getting this ready for a public alpha- interactivity is much improved and styling has also improved. 

We have fixed the imagery selector boxes to have the proper indenting, but we still don't have 360 degree viewfields and need to work on that. I have opened #539 for that.

**Comment by bhousel** [comment]
Closing here, but tracking on #539  - we do intend to bring the streetview layers up to parity with Rapid v1 over the course of the beta program.
