### ISSUE TITLE
Mobile: Selection Support

### ISSUE THREAD

**Issue by Bonkles** [facebook/RapiD#498]
Recently our mobile support has devolved a bit and items on the map are no longer selectable.

**Comment by Bonkles** [comment]
Commited in  764eb3384.  

Screenshot of selected road with tons of tagging info: 



![Image](https://user-images.githubusercontent.com/1887955/180235722-5b53d430-4f53-4cdc-bd5d-805979364544.png)

**Comment by bhousel** [comment]
Closing here as a dup of #749 
@Bonkles is working on improving mobile support now!
