### ISSUE TITLE
style for ephemeral features (abandoned, proposed, construction, intermittent, etc)

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#535]
The v1 version of RapiD / iD has a number of style choices for rendering certain ephemeral features on the map. Here are just a few: 

![ephemeral-features](https://user-images.githubusercontent.com/1887955/198117820-e23980e7-5344-434c-8d44-6b374a033e51.gif)

We should restore this same (or similar) functionality in v2.

**Comment by bhousel** [comment]
The old code is still hanging around in here:
https://github.com/facebook/Rapid/blob/main/modules/svg/tag_classes.js

What it would do is look at the OSM tags and set CSS classes for these things.  We can't use the CSS classes anymore, but everything else about the old code can be repurposed.
