### ISSUE TITLE
Style 360 imagery points in photo layers correctly (circles, not directional pins)

### ISSUE THREAD

**Issue by Bonkles** [facebook/RapiD#539]

**Comment by bhousel** [comment]
<img width="697" alt="Screenshot 2023-01-25 at 5 25 38 PM" src="https://user-images.githubusercontent.com/38784/214706648-f9354110-f6f3-4f50-8253-7ee91c743bfd.png">

**Comment by Bonkles** [comment]
Fixed in `fe0ca709faa122621cb939302f7a4ed48725890e`.
