### ISSUE TITLE
Selecting an entity with the sidebar minimized doesn't unfold the sidebar

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#540]

**Comment by bhousel** [comment]
It didn't before either - If I'm understanding what you mean..
I'm not a huge fan of how the sidebar expand/contract happens currently, so maybe we could come up with a better solution that 
- allows the sidebar to get in/out of the way and resize to desired width with a handle
- doesn't use a button in the top bar
- shrinks the sidebar very small but maybe leaves a minimal bit of feedback feedback on select/hover
- works ok on mobile

**Comment by bhousel** [comment]
This is kind of old, but I think #1497 and #1562 covers it.
