### ISSUE TITLE
Disable adjacent tile loading when viewing HOT task areas

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#549]
As @zlavergne points out- a bunch of extra, unnecessary OSM data is being loaded outside of HOT tasking manager.  We should investigate slowdowns that this may be causing, and only load the data required for the task at hand. 

Upon further inspection, Bryan found that we are also loading WAY too many tiles worth of data if we happen to zoom at just the wrong time. because we were using requestIdleCallback

**Comment by Bonkles** [comment]
Fix for the 'loading tons of tiles of OSM data' went in in commit `cbfde996d`.

**Comment by bhousel** [comment]
I forgot this was still open!  I ended up removing the margin tile fetching from the OSM service in b261edf1b so this can be closed.

(Fetching extra margin tiles is useful in situations where we need to stitch features together - this isn't the case for OSM  data, where ways always arrive complete with all their nodes, even if they extend far away).
