### ISSUE TITLE
Bing Streetside shows white box

### ISSUE THREAD

**Issue by boothym** [facebook/RapiD#567]
### Description

See https://github.com/openstreetmap/iD/issues/9230

Noticed this in iD and I wondered if this issue also existed in Rapid - it does.

### Version

1.1.9

### What browser are you seeing the problem on? What version are you running?

Chrome / Win 10

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=20.57/51.50158/-0.12402&photo_overlay=streetside

**Comment by bhousel** [comment]
This is also https://github.com/openstreetmap/iD/issues/9230
