### ISSUE TITLE
I tried to add a point but it would not remain selected

### ISSUE THREAD

**Issue by wilfredwaters** [facebook/RapiD#570]
### Description

I tried to add a point but it would not remain selected. Same happened when I selected other things in the view. It showed the details for a second or two, then got bored and went blank

### Version

2.0-alpha

### What browser are you seeing the problem on? What version are you running?

Chrome v104.0

### Steps to reproduce

select a feature on the map and attributes appear on the right
wait 2 seconds, don't click anything extra
attributes disappear, despite your having not clicked anything else/unselected

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=boundaries&map=20.60/51.49355/-0.04435

**Comment by bhousel** [comment]
I believe this seems fixed now in the latest v2 beta, but can't pinpoint what the issue was or when we fixed it..
