### ISSUE TITLE
Country request: Iran

### ISSUE THREAD

**Issue by imanmoghimiq30** [facebook/RapiD#58]
Please process aerial images in Iran for buildings (It's important for us because We had earthquake and flood recently in the west of Iran) and roads.
Thanks for your attention

**Comment by n1arash** [comment]
+++++++++++++++

**Comment by Ahmadhosseinbor** [comment]
👍

**Comment by MohamadKh75** [comment]
+1

**Comment by jeffdefacto** [comment]
Thanks for the request @imanmoghimiq30 and everyone else!

I'll add it to our country request list for roads. Microsoft produces the buildings so no promises on them.

**Comment by imanmoghimiq30** [comment]
@jeffdefacto appreciate

**Comment by justinelliotmeyers** [comment]
@jeffdefacto will Iran be in the next batch release?  Thanks!!

**Comment by jeffdefacto** [comment]
Bad news unfortunately.

After internal legal review, it has been determined that current US law prevents us from releasing Iran road data.

This could change in the future and this issue will remain open for tracking purposes.

**Comment by justinelliotmeyers** [comment]
Is there a specific agency I can reach out to and ask more about this? Or is this an agreement between Maxar/ us govt (DoD/ NSA/ etc)? Thanks for updating issue.

**Comment by jeffdefacto** [comment]
It's due to the ongoing sanctions.

I'm not a lawyer, so I can't provide much more information on the subject unfortunately.

**Comment by cbeddow** [comment]
@justinelliotmeyers it looks like no data in Iran still, so I would count on this not happening via Meta or Microsoft open data as US-based companies affected by sanctions. Going to close the issue.
