### ISSUE TITLE
IRAN

### ISSUE THREAD

**Issue by Alj96** [facebook/RapiD#590]
Iran's roads are in a not so bad state, but there are tens of thousands buildings not mapped

**Comment by Bonkles** [comment]
Hi @Alj96 - are you asking us to add building predictions for Iran? I'm not quite sure what it is you are asking for.

**Comment by cbeddow** [comment]
Closing, since we can't influence new Iran data coming in, and the map editing depends on the community. You can contact the OSM Iran community here: https://t.co/7CnJ5UyM9F
