### ISSUE TITLE
Black window

### ISSUE THREAD

**Issue by leclercprof** [facebook/Rapid#603]
### Description

After uploading 8 changes, the map windows became completely black (no background image, no geographical object

### Version

2.0-alpha

### What browser are you seeing the problem on? What version are you running?

Chrome v106.0

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=boundaries&map=16.00/NaN/NaN

**Comment by Bonkles** [comment]
Thanks for the bug report! If you still happen to have that browser window around on your desktop, could you please check to see if there are any debug log traces in it? 

Select the three-dot menu in the upper right, then more tools -> Developer Tools, then click the 'Console' tab and copy/paste what you find there. 


![image](https://user-images.githubusercontent.com/1887955/192837865-f17d1f64-48e0-4a88-b9e3-2b02811a515f.png)

**Comment by Bonkles** [comment]
There's no good way to copy from the console, I just have to select things manually with the mouse: 

![image](https://user-images.githubusercontent.com/1887955/192838430-2baf7714-96d8-4d47-8395-c28bbf4a8917.png)

**Comment by bhousel** [comment]
closing as stale
