### ISSUE TITLE
RapiD incorrectly treats name:etymology tags as part of Multilingual Name

### ISSUE THREAD

**Issue by mxxcon** [facebook/RapiD#610]
### Description

A feature has tags:
```
name=Marsha P. Johnson State Park
name:etymology=Marsha P. Johnson
name:etymology:wikidata=Q6773400
name:etymology:wikipedia=en:Marsha P. Johnson
```
RapiD 1.1.9 parses it as:
![image](https://user-images.githubusercontent.com/847140/194184991-b91dcf88-87ee-40af-9f39-73146ad96864.png)

For comparison iD 2.22.0 doesn't consider it as part of multilingual name.

### Version

1.1.9

### What browser are you seeing the problem on? What version are you running?

Chrome v106

### Steps to reproduce

Open way 33819583 in RapiD

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w33819583&map=17.97/40.72159/-73.96207

**Comment by bhousel** [comment]
oh this was also closed in 3cd2acb88 yesterday 👍
