### ISSUE TITLE
Some Rendering Icons for Node elements are not depicted in Rapid as in ID

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/RapiD#666]
### Description

Several Icons for Nodes are not depicted in RAPID as in ID

barrier=toll_both, natural=hot_spring, and others; are depicted as a blank node (white) over a way or as a stand alone node

### Version

1.1.9.

### What browser are you seeing the problem on? What version are you running?

Chrome Version 105.0.5195.127 (Official Build) (64-bit)

### Steps to reproduce

Just place any of those elements in Rapid.

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=boundaries&id=n9024343581&map=17.00/-22.53423/-67.64812&overlays=osm-gps

**Comment by bhousel** [comment]
This is updated for the Rapid v2 beta and it looks ok with the newer version.  For now we are using the id presets from the [id-tagging-schema](https://github.com/openstreetmap/id-tagging-schema) project, and we'll try to link to stable versions of that.
#474 has some other info about why the icons from that project might disappear sometimes.

<img width="494" alt="Screenshot 2023-01-20 at 10 31 02 AM" src="https://user-images.githubusercontent.com/38784/213737294-822319fd-c2ce-49e7-86fe-8ccbf9deb009.png">
