### ISSUE TITLE
Lint check: mark warning if name is in all caps

### ISSUE THREAD

**Issue by cbeddow** [facebook/Rapid#667]
### Description

For some place names, the user writes in all caps. This is often wrong.

We should have a warning that detects it and asks user "are you sure the name is in all caps?" If not, then fix my lower-casing all except the first letter of words in the name field

![image](https://user-images.githubusercontent.com/10554922/203789228-4b3bf0f0-1d42-4eb4-9ea4-92888e4d7099.png)

example area: https://mapwith.ai/rapid#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries,past_future,others&map=18.88/4.87806/-72.89812

**Comment by Bonkles** [comment]
BUT CHRIS WHAT IF PEOPLE JUST WANT TO YELL AT OPENSTREETMAP

**Comment by bhousel** [comment]
This is kind of a hard problem - the convention in some places really is to use all caps when writing western words.
see https://github.com/osmlab/name-suggestion-index/pull/7663 as one example, but I know it's pretty common around Japan.

Even many western brands like "IKEA" , "HSBC", "CVS", "UPS" are spelled out in all capitals.

**Comment by LaoshuBaby** [comment]
It seems that the meaning of capitalization for emphasis is more common in countries that use the Latin alphabet in their languages?

And even in Western countries you may found a "KFC" or "IKEA", so will this capitalization lint conflict with NSI preset? (after all, there are many editors who do not read the text carefully and apply all suggested edits directly I‘ve seen)

So at least you can use NSI presets to determine which case is OK, and apply this detector depends on the country or region those elements located for elements not matched by NSI? (However, even so, according to [JA:Naming_sample](https://wiki.openstreetmap.org/wiki/JA:Naming_sample), full uppercase string mainly used in `brand`)

**Comment by Lonerat** [comment]
I am negative on this as I do not think this is practical.

As the other two mentioned, and at least in Japan, there are many brands whose official names are only capitalized, and from small stores to even large facilities (especially logo designs).
Often they are also used in various varieties, such as all uppercase, first letter only uppercase, all lowercase, etc.

If it is a brand, it could be checked by a database like NSI, but if it is a single store, facility and so on, it would be impractical to detect exceptions.

**Comment by bhousel** [comment]
Going to close this for now - I think there are enough counterexamples provided for why trying to make a validator for capital letters in the names would lead to too many false positives.

BTW, speaking of funny names.. did I ever show you  𝑪𝒂𝒏𝒅𝒚 𝑳𝒂𝒔𝒉𝒆𝒔 ?  👀 
They are using the extended unicode up in plane 1 that contains the bold mathy letters.
You can see how people do funny stuff with names!

<img width="625" alt="Screenshot 2023-08-09 at 4 40 53 PM" src="https://github.com/facebook/Rapid/assets/38784/c8912b11-0027-4eab-bb31-88384437f0d6">
