### ISSUE TITLE
Mouse wheel scroll pans map

### ISSUE THREAD

**Issue by cbeddow** [facebook/RapiD#680]
Chrome browser, on Windows, with wireless mouse with hardware scroll wheel

I intend to zoom in and out on the map when I use the scroll wheel, but it seems to pan the map when zoomed in. Zoomed out completely, it seems to be vertical scrolling the map container and makes a red bar appear at bottom 5% or less of the map container.

**Comment by bhousel** [comment]
Ah yeah this one might be tricky.   I rewrote all the map interaction code a few months ago, but this is one of those areas where different browser/os/mouse combinations can do different things.  Simplest fix might be to just add a toggle in the user preferences pane to let the user override what our wheel event handler does.

**Comment by boothym** [comment]
Same here, though if you scroll the mouse wheel enough times it seems to pan the map up and then zoom in, and so on.

**Comment by nickrsan** [comment]
Also encountering this issue in the V2 Beta on Firefox 109.0.1 on Windows 10.

**Comment by 1ec5** [comment]
> Simplest fix might be to just add a toggle in the user preferences pane to let the user override what our wheel event handler does.

This would also be a suitable workaround for openstreetmap/iD#8649 on Firefox on the Mac (which also affects RapiD).

**Comment by k-yle** [comment]
Edge v110 on Windows 11:
- swiping left/right with two fingers: ✓ works
- swiping up/down with two fingers: ✗ zooms instead of panning
- mouse scrollwheel: ✗ pans instead of zooming

**Comment by Bonkles** [comment]
Thanks so much for all the reports and corroborating information everybody! I'm taking a look at this today. Fortunately I can reproduce this on my home PC, unfortunately, it does NOT reproduce on my development machine, a macbook Pro (which is how this one slipped through the cracks).

**Comment by tyrasd** [comment]
I'm also experiencing the issue on Linux (Ubuntu). FYI: I do have a mouse with a secondary _"horizontal"_ mouse wheel (Logitech MX Master 3), and the secondary wheel pans the map horizontally while the main scroll wheel pans it vertically.

**Comment by 1ec5** [comment]
I think the original design was that an input device that’s capable of scrolling in two directions would get the panning behavior, while an input device that’s only capable of scrolling vertically would get the zooming behavior. But that’s difficult to map to the DOM events that come through, especially across browsers.

Regardless of the input device, some users also prefer one behavior over the other. For some users, panning any other way would induce RSI. Other users happen to specialize in a kind of mapping that requires more zooming than panning, such as reviewing buildings or participating in MapRoulette challenges built around point features. A preference would better accommodate these different use cases while offering an escape hatch when (Rap)iD doesn’t choose the most ergonomic default for the user’s environment.

**Comment by mxxcon** [comment]
> I think the original design was that an input device that’s capable of scrolling in two directions would get the panning behavior, while an input device that’s only capable of scrolling vertically would get the zooming behavior. But that’s difficult to map to the DOM events that come through, especially across browsers.
> 
> Regardless of the input device, some users also prefer one behavior over the other. For some users, panning any other way would induce RSI. Other users happen to specialize in a kind of mapping that requires more zooming than panning, such as reviewing buildings or participating in MapRoulette challenges built around point features. A preference would better accommodate these different use cases while offering an escape hatch when (Rap)iD doesn’t choose the most ergonomic default for the user’s environment.

I'd say majority of consumer users(ie coming from google maps) would expect wheel to zoom... It is also the default behavior on osm.org, iD and RapiD up to this point..

**Comment by 1ec5** [comment]
Yes, I’m generalizing a bit. If you have a conventional wheel, you expect zooming. If you have a multitouch-capable mouse or trackpad, it isn’t quite as clear-cut, because it depends whether you associate (Rap)iD with a graphics editor or a browseable map.

**Comment by aronkvh** [comment]
Same with Linux and Firefox 110

**Comment by bhousel** [comment]
I ended up making this behavior configurable on the preferences pane.  
We might further tweak the "automatic" option to work better on non-Mac devices.

<img width="300" alt="Screenshot 2023-02-24 at 3 17 34 PM" src="https://user-images.githubusercontent.com/38784/221282897-4a31834e-e8fa-4635-83a0-99439dd0ffb5.png">

I added tooltips to explain what these options mean:

```yaml
auto:
  title: Automatic
  tooltip: Best for trackpad users.  With 2 fingers, swipe gestures will pan the map, and pinch gestures will zoom and unzoom the map.  Holding down Shift will zoom and unzoom the map.
zoom:
  title: Zoom the Map
  tooltip: Scrolling with the wheel will always zoom and unzoom the map.
pan:
  title: Pan the Map
  tooltip: Scrolling with the wheel will pan the map.  Holding down Shift will zoom and unzoom the map.
```
