### ISSUE TITLE
Cannot see building nodes when editing building

### ISSUE THREAD

**Issue by cbeddow** [facebook/Rapid#681]
When I edit a building and have it selected in yellow, I cannot see the individual nodes and drag them to new locations. Even if I kno2 where they are on the vertices, I cannot click and drag them blindly either.

**Comment by Bonkles** [comment]
Taking a look at this- it seems we only draw 'interesting' vertices while the user is creating/editing shapes. We need to make sure that we draw 'all' vertices whenever the user draws a thing. 

The reason we draw endpoints for the way drawing gesture is... we consider way endpoints to be 'interesting' in the Pixi rendering code. :)

**Comment by Bonkles** [comment]
Fixed in `04365af38`. 

Nodes in a particular area should now be clickable, allowing you to close the area by either double clicking the first or last node in the area. 

![Image](https://user-images.githubusercontent.com/1887955/206013592-5119b0a7-ec4a-4aff-b4c4-2e48288ca691.gif)
