### ISSUE TITLE
Mapillary Green is slightly off.

### ISSUE THREAD

**Issue by Bonkles** [facebook/RapiD#685]
### Description

Code now has `MAPILLARY_GREEN` LISTED AS `0X55FF22`, but this should be changed to `0x05cb63`. 

### Version

2.00-alpha.3

### What browser are you seeing the problem on? What version are you running?

Chrome v107.0

### Steps to reproduce

Just enable the mapillary map points and check the difference in color. It's subtle! 

![image](https://user-images.githubusercontent.com/1887955/205102963-a45fdbd6-e696-4de8-a8e4-ef730f1901ff.png)

(rapid on left, mapillary web site on right) 

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha3#background=EsriWorldImageryClarity&datasets=fbRoads,msBuildings&disable_features=past_future,others&id=r1933745&map=21.15/42.37467/-71.11420&photo=mapillary/5839352752741830&photo_overlay=mapillary

**Comment by Bonkles** [comment]
Update: Spoke with @bhousel- reason for this color divergence is that he picked a slightly more contrasting green to pair with the Kartaview Blue and Bing Streetside Teal. 

That said, here is a before (left) and after (right) comparison using the correct Mapillary color: 

![image](https://user-images.githubusercontent.com/1887955/205108535-d17eef33-490d-4cc1-b6b7-f60f51e41944.png)

**Comment by cbeddow** [comment]
The contrast looks nice I would say... But checking the Mapillary website, the colors of buttons and such are actually `#0bcb63` which might be a good choice then. 

See this color too:
![mapillary_logo_green_1plate@2x](https://user-images.githubusercontent.com/10554922/205391016-9bbf3fc8-7e51-4ec6-a7db-bd3de57bb357.png)

**Comment by cbeddow** [comment]
Same `#0bcb63` here too... so let's give that a go? 
![image](https://user-images.githubusercontent.com/10554922/205391687-698768f4-7f3a-4a60-9434-4f9e23c12e25.png)

**Comment by Bonkles** [comment]
Fixed in `60bd5db76` but I am open to color suggestions.
