### ISSUE TITLE
[alpha3] Can't move the map while drawing an area

### ISSUE THREAD

**Issue by mvexel** [facebook/RapiD#687]
### Description

In alpha3 on Firefox, I cannot drag the map while in area drawing mode. This makes it (almost) impossible to draw an area that extends beyond the map extent visible when starting to draw the area.

I found the only way to change the map extent while in area drawing mode is to use the arrow keys

### Version

2.00-alpha3

### What browser are you seeing the problem on? What version are you running?

Firefox 107 Mac

### Steps to reproduce

1. Press '3' to enter area drawing mode
2. Draw the first point of the area
3. Click and hold to draw the map or use the mouse wheel to change map extent
4. I am unable to change the map extent

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha3#background=EsriWorldImagery&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w-3&map=22.02/40.74012/-111.86164

**Comment by Bonkles** [comment]
Fixed in `b3d43980d`.
