### ISSUE TITLE
Pasting with Cmd-V does not work

### ISSUE THREAD

**Issue by mvexel** [facebook/RapiD#695]
### Description

I love to use copy / paste to quickly duplicate a feature with its tags. This works in iD with Cmd-C / Cmd-V (Mac).
In Rapid, Cmd-C works, but Cmd-V does not. I can still paste a feature using the right mouse button context menu.
There is a visual hint in the MacOS menu bar that a Copy / Paste was triggered when using the Cmd-C / Cmd-V key combos, however, whatever was on the clipboard previously was preserved, suggesting nothing was copied. 

### Version

2.00-alpha3

### What browser are you seeing the problem on? What version are you running?

Firefox 107 Mac

### Steps to reproduce

1. Select a feature
2. Press Cmd-C
3. Press Cmd-V

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha3#background=Bing&datasets=fbRoads,msBuildings&id=n-64&map=21.44/40.75112/-111.86612

**Comment by Bonkles** [comment]
fixed in `8a9a5cdab`
