### ISSUE TITLE
Preferences has reference to iD privacy policy

### ISSUE THREAD

**Issue by mvexel** [facebook/RapiD#699]
### Description

Does Rapid have its own privacy policy? If so, this link should be changed

![SCR-20221205-kgg](https://user-images.githubusercontent.com/120452/205748872-49d7c20a-1af1-47f8-8b45-bd6818089cc1.png)

### Version

2.00-alpha3

### What browser are you seeing the problem on? What version are you running?

Firefox 107 Mac

### Steps to reproduce

1. Open "Preferences"
2. There is no step 2

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha3#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=n6086155789&map=20.10/40.75066/-111.86557

**Comment by Bonkles** [comment]
Fixed in `4492d852e`.

**Comment by CorruptComputer** [comment]
@Bonkles Any chance that the PRIVACY.md file in the repo could get updated as well? The links and contact info in there are all for the main iD repo.
