### ISSUE TITLE
Split tool (button x) creates a duplicate area

### ISSUE THREAD

**Issue by VLD190** [facebook/RapiD#704]
### Description

This but is specific to areas only. Whether you are creating a new way or editing a pre-existing way in Rapid V2 Alpha3, the problem persists. Once you split a node and attempt to move it, the selected area is duplicated.

This does not occur with ways, only area. I hope I was able to express the bug clearly and how to replicate the issue. For any questions, please reach out to me.

### Version

2.00-alpha.3

### What browser are you seeing the problem on? What version are you running?

Chrome v108.0

### Steps to reproduce

To replicate the issue, select the node of an area, and press 'x.' Once this occurs, the node will change colors from white to grey, notifying you that the split has worked. The issue occurs once you attempt to move that same node or any node that is split on an area, because a duplicate area is created once the split node has been moved. 

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha3#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w404166367&map=17.35/33.90821/-116.54440

**Comment by Bonkles** [comment]
Looks like this one also got fixed as part of the fix for #682. Behavior seems identical to rapid v1 now when splitting an area.
