### ISSUE TITLE
Roads/buildings not updating after undoing node position

### ISSUE THREAD

**Issue by bsidhuFB** [facebook/RapiD#705]
### Description

Once a node, building, roadway has been moved via dragging or M hotkey and undone using cmd+Z the node position updates, but the geometry of the building and roadways do not update at the same time. They update after you move another node. 
![Screen Shot 2022-12-06 at 2 47 22 PM](https://user-images.githubusercontent.com/111467504/206040965-0ca19dad-cd38-4c72-9269-89214f027830.png)
![Screen Shot 2022-12-06 at 2 47 14 PM](https://user-images.githubusercontent.com/111467504/206040976-b17f831e-3617-4009-9b7d-70705ce35427.png)

### Version

2.00-alpha.3

### What browser are you seeing the problem on? What version are you running?

Chrome v108.0

### Steps to reproduce

1. move any node, roadway, building
2. undo using cmd+Z

https://user-images.githubusercontent.com/111467504/206043149-a306a334-3a1b-4fa4-a460-3d1fd7c65271.mov

https://user-images.githubusercontent.com/111467504/206043379-6b57f2eb-cdef-4f18-a373-513d382cee06.mov

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha3#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=21.47/37.57718/-122.02984

**Comment by Bonkles** [comment]
This is another bug that should be fixed as of rapid v2.0.0-alpha.3.2. Fix is same as the one for #682. 

Here's a vid showing these operations working in the exact same place on the map: 



https://user-images.githubusercontent.com/1887955/207379533-b650ce47-f478-4506-9128-d97ae8b2f980.mov
