### ISSUE TITLE
The nodes of an area that is moved does not move with the area

### ISSUE THREAD

**Issue by VLD190** [facebook/RapiD#706]
### Description

I recently attempted to move a building to better fit the imagery, but the nodes did not follow the building. The nodes followed the area of the building as soon as I moved an individual node to the correct position. once an individual node is moved, the rest of the nodes 'snap' to the correct location as the building's area. Another way to make the nodes follow the moved building is by selecting the building, pressing 'm' to move it again, and slightly moving it. Once the area has been slightly moved a second time, the nodes to move to correct location

### Version

2.00-alpha.3

### What browser are you seeing the problem on? What version are you running?

Chrome v108.0

### Steps to reproduce

select the outline of an area, press 'm' to move it, and slightly move the building. Once the area has been moved, you will see that the nodes do not follow the area.

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha3#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w404166367&map=17.45/33.90821/-116.54454

**Comment by Bonkles** [comment]
Fixed in Rapid alpha 2.00-alpha.3.2. See #682 for an explanation. Short vid showing this functionality working: 

https://user-images.githubusercontent.com/1887955/207367331-632a1858-b958-4fc2-9e4c-f270e9e76082.mov
