### ISSUE TITLE
Shortcut "A" to continue a line does not function

### ISSUE THREAD

**Issue by csm2023** [facebook/RapiD#708]
### Description

When attempting to continue a line using the keyboard shortcut "A", it does not work if an AI object has been selected/deselected before the attempt. On the bottom info bar it says that it continued a line, but on the map there is no visible change to the way. Instead, the AI polygon that was touched before will be added to the map. 

### Version

2.00-alpha.3

### What browser are you seeing the problem on? What version are you running?

Chrome v108.0

### Steps to reproduce

Select a nearby Ai polygon, then deselect it and select the end node of a way. Press "A". 
The expected behavior is to continue drawing the line from the endpoint. 

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha3#background=Bing&datasets=fbRoads,msBuildings&disable_features=points,indoor,landuse,boundaries,water,rail,pistes,aerialways,power,past_future,others&map=19.86/39.71208/-105.17518

**Comment by bhousel** [comment]
@Bonkles Maybe we can pick different keyboard shortcuts for the Rapid Accept/Ignore buttons?  
It's always bothered me that <kbd>A</kbd> does 2 things.

**Comment by Bonkles** [comment]
I think there's a strong case to be made for creating new shortcuts here, ideally both for the left hand, making it so the the user doesn't have to hunt for 'i' to ignore something.  We're just short on keys to use unless we start doing modifiers.

**Comment by Bonkles** [comment]
For now I have restored the same shortcut functionality- we simply weren't cleaning up the keybinding when leaving the select mode for Rapid features. Let's revisit.
