### ISSUE TITLE
Remove Nudge and Scaling shortcuts, as they are no longer honored.

### ISSUE THREAD

**Issue by csm2023** [facebook/RapiD#709]
### Description

When attempting to scale a feature using the keyboard shortcuts (both regular scaling and scale by a lot), the feature does not change size. Tested on building polygons, closed line shapes, and ways. 

### Version

2.00-alpha.3

### What browser are you seeing the problem on? What version are you running?

Chrome v108.0

### Steps to reproduce

Select a feature, hold shift and use +,- keys to attempt to resize it. 

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha3#background=Bing&datasets=fbRoads,msBuildings&disable_features=points,indoor,landuse,boundaries,water,rail,pistes,aerialways,power,past_future,others&map=20.09/39.69552/-105.14696

**Comment by Bonkles** [comment]
Fixed in `f4ef45f96`.
