### ISSUE TITLE
Issue Validator does not register self-crossing ways as a crossing ways issue

### ISSUE THREAD

**Issue by csm2023** [facebook/RapiD#713]
### Description

If a way is moved to cross over itself, the validator does not give a "crossing ways" warning. Also does not give a warning for polygons that cross over themselves. 
<img width="711" alt="Screen Shot 2022-12-09 at 2 56 19 PM" src="https://user-images.githubusercontent.com/119973649/206802279-2275c5ab-2cc0-4a7a-98ac-6bf45f9356a6.png">

### Version

2.00-alpha.3.2

### What browser are you seeing the problem on? What version are you running?

Chrome v108.0

### Steps to reproduce

Continue a way from its endpoint and draw it so that it loops around and crosses over itself (without adding an intersection point). In the issue validator, the expected behavior is for a yellow warning to pop up notifying the user that there are invalidly crossing ways. 

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha3#background=Bing&datasets=fbRoads,msBuildings&disable_features=points,indoor,landuse,rail,pistes,aerialways,power,past_future,others&map=18.88/39.67460/-105.12727

**Comment by bhousel** [comment]
Thanks!  This is also #690 
We'll restore the self-intersecting way checks at some point. The old code had these checks really embedded in with the drawing code, because it dated back to a time before we had built the validator.
