### ISSUE TITLE
Currently selected Mapillary image not visible in Alpha 3

### ISSUE THREAD

**Issue by eneerhut** [facebook/Rapid#740]
I enabled the Mapillary imagery layer in Alpha 3 and then navigated to an image. The UI does not indicate which image in the sequence is selected, making it harder to know where I am. Only the first image I selected remains highlighted in the UI.

<img width="1561" alt="image" src="https://user-images.githubusercontent.com/11349863/209726110-8b5c84a7-e73e-4fa7-be7e-ec20bbaa3883.png">

The OG Rapid highlighted the currently viewed Mapillary image clearly.
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/11349863/209726158-1a6877f4-76cf-4e05-92a5-c3de24a72274.png">

I have uploaded a [video demonstrating this here](https://drive.google.com/drive/folders/13c7MiI-OjEGKqnp-EWnyxmzFlyo-yuDz).

**Comment by bhousel** [comment]
Just linking this to #539, which is the other issue about styling the photos properly.

Each of the streetview layers have some code like this to style the markers..  It works by d3-selecting the markers and css classing them a certain way - this won't work going forward with the new renderer, so we need to do it a different way!

https://github.com/facebook/RapiD/blob/85fbac7949144423fdfd57e8f65f6684cd0ae439/modules/services/mapillary.js#L657-L671

**Comment by eneerhut** [comment]
[Uploaded a video here](https://drive.google.com/file/d/1A7JedSxKh1-tDMG_iLVYvSLUrjXl0AIm/view?usp=sharing) that demonstrates the UX issue where the currently selected imagery is not highlighted.

**Comment by tordans** [comment]
Just clicked on the RapID link from [Mapillary's website](https://www.mapillary.com/app/?z=17&lat=52.4221061&lng=13.5152014&panos=true&pKey=153371934206510&focus=photo&x=0.4056900323690077&y=0.5526097824289359&zoom=0) and notices this issue as well. So I guess this is just the long way to say +1 :).
