### ISSUE TITLE
Mobile pass: Ensure that mouse/touch events work correctly

### ISSUE THREAD

**Issue by Bonkles** [facebook/RapiD#749]
When using the v2 alpha 3 on mobile, the zoom factor gets set to NaN/NaN.  This apparently also happens from desktop chrome with a simulated pixel 5 selected. 

Finally, rendering a specific object fails to work too: https://mapwith.ai/rapid-v2-alpha3#id=w808726001

**Comment by jleedev** [comment]
Well, w808726001 has since been deleted. However, any large enough area seems to not render.

https://mapwith.ai/rapid-v2-alpha3#id=r188553 works.
https://mapwith.ai/rapid-v2-alpha3#id=r2563472 does not.

**Comment by Bonkles** [comment]
Okay, at long last- some progress. We've figured out that we were depending on `event.movementX/Y` to be present in our map 'pointermove' events, but that is only a thing when a mouse is available. Instead we will synthesize our own 'movementX/Y' coords by saving the last pointermove event, comparing the `clientX` and `clientY` coords. 

This worked in some initial testing I did with my pixel 3A XL.

**Comment by Bonkles** [comment]
Further updates: This seems to work on my iPad 9th gen. It will ship in the beta coming out very soon(tm).
