### ISSUE TITLE
Snapping too aggressively

### ISSUE THREAD

**Issue by mvexel** [facebook/RapiD#752]
### Description

When moving a node inside a smallish area (a common task when you want to move a POI inside the building it belongs to) Rapid will snap to the building nodes quite aggressively, making it hard to move the node to a location inside the building. Here's Rapid behavior:

https://user-images.githubusercontent.com/120452/212742285-e183313a-8f66-4233-94c7-844729d471b8.mov

vs iD behavior:

https://user-images.githubusercontent.com/120452/212742345-c07c9f6e-3d16-4219-8222-f4ab43d16084.mov

### Version

2.00-alpha.3.3

### What browser are you seeing the problem on? What version are you running?

Firefox v108.0

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha3#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=n358967063&map=18.94/32.57364/-86.59672

**Comment by bhousel** [comment]
yeah, this is also #719 - high priority for us to fix 👍
