### ISSUE TITLE
two point in ways are very close error when connecting a new way to end of existing ways

### ISSUE THREAD

**Issue by atiannicelli** [facebook/Rapid#753]
### Description

When I draw a line that ends at the node of another line and then click again to end this line it seems to create another node. Then I get an error that says "Two Points in sidewalk are very close together."

https://user-images.githubusercontent.com/5851115/212987732-67645ae5-34d2-4cb8-823f-c54212739d6f.mov

### Version

2.00-alpha.3.3

### What browser are you seeing the problem on? What version are you running?

Chrome v109.0

### Steps to reproduce

When I am creating sidewalks I like to create a new sidewalk for each block. So I create a line from one corner of the block to the other. I make that line into a sidewalk. Then I create another line from another corner that should connect to the line I just created. The light comes on when I hover over the endpoint so I think I am connecting them. Then I click again to end the line. When I click again it is making another node on top of the node I just created. See movie in description. 

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha3#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=20.06/44.08721/-103.20381

**Comment by Bonkles** [comment]
Yep, this has been fixed as part of #807 and will be pushed live soon! Thanks for the bug report...
