### ISSUE TITLE
Ortophography for Portugal is not well positioned.

### ISSUE THREAD

**Issue by ruilvo** [facebook/RapiD#756]
### Description

Preface: I didn't know where else to complain about this, so here it is.

----

So, I was using RapiD to do some quick building marking in my area. However I encountered a problem.

This is how it looks on RapiD:

![imagem](https://user-images.githubusercontent.com/8402646/213129230-6c18a843-9c49-4a07-b9e9-849c29f2b140.png)

However, this is the same region on regular iD:

![imagem](https://user-images.githubusercontent.com/8402646/213129567-5927ace5-e972-440c-a20f-939d0246831f.png)

Notice how some buildings are way off like these ones:

![imagem](https://user-images.githubusercontent.com/8402646/213129764-d3d5e324-d6b2-4b2b-8bfc-125b74d86819.png)
![imagem](https://user-images.githubusercontent.com/8402646/213129730-e0a345f4-5f2b-471d-af28-0d5810262bfe.png)

Is this a problem with the positioning/scaling of the photographies? 

Thank you

### Version

1.1.9

### What browser are you seeing the problem on? What version are you running?

Firefox 108

### Steps to reproduce

Compare RapiD with regular iD on the Northern Portugal region. 

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=boundaries&map=19.60/41.07776/-8.30996

**Comment by bhousel** [comment]
> My problem is that I feel I can't use RapiD because the buildings will not be right when viewing on OSM. And many buildings will collide with roads and etc drawn from OSM if accepted on RapiD, like the one in the centre of the screenshot (which is wrong anyway, but you get the point).

Yes this makes sense.. We do have issue #270 which would allow users to adjust the alignment of the data layers, maybe that would be an acceptable solution?

**Comment by ruilvo** [comment]
Well, any way to adjust the layer with the AI "proposals" relative to the data layer would sort the problem out. 

I'll close as a duplicate then.

Duplicates #270.
