### ISSUE TITLE
snapping while drawing issues

### ISSUE THREAD

**Issue by mvexel** [facebook/RapiD#758]
### Description

When you start drawing a new way with a node _not_ on an existing way, snapping to another existing way works as expected:

https://user-images.githubusercontent.com/120452/213291396-5ea80575-7c93-41ec-8e74-cea859af6c1d.mov

However when the new way starts with a node on an existing way, no snapping for you!

https://user-images.githubusercontent.com/120452/213291458-a190e70c-b5b2-461c-8ff3-8936dd082727.mov

### Version

2.00-alpha.3.3

### What browser are you seeing the problem on? What version are you running?

Firefox v108.0

### Steps to reproduce

1. start drawing a new way with the first node on an existing way
2. hover the pointer over another existing way

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha3#background=EsriWorldImagery&datasets=fbRoads,msBuildings&disable_features=boundaries&map=21.25/40.76630/-111.83770

**Comment by Bonkles** [comment]
Short explanation: 

CLicking ways, clicking nodes, and clicking empty locations all run through different codepaths in the 'mode' code. The correct logic was being used for the 'click empty location' code but not the other two.

**Comment by Bonkles** [comment]
Fixed in `b58e9da63`.
