### ISSUE TITLE
Task Boundary and Grid re-implementation

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#768]
### Description

As of RapiD v2, we do not draw the task border supplied to us via .gpx file in the url params.  Traditionally, .gpx files have been used as a means for tasking manager to say 'edit within this area, but not outside of it'. These .gpx files could specify arbitrary geometries, not just bounding boxes, to limit edits. 

In turn, RapiD would display these borders and limit edits to happen only inside of them. 

In RapiD v1, we also had the ability to subdivide a square task boundary into a 2x2, 3x3, 4x4, 5x5, or 6x6 grid (a RapiD-only feature, not something in iD). These were purely cosmetic and just helped mappers 'see' how much they had left to map as they methodically proceeded to map a large boxed area. 

Now, we still have the machinery around parsing the .gpx files in place, but we need to ensure that the task border is drawn correctly. Furthermore, we need to detect if the .gpx specifies a rectangular shape and allow the user to subdivide it with the 2x2 <--> 6x6 grid. 

The Task boundary predates rapid (iD had it as of tag 2.15.3)
Here's the original pull requests from RapiD v1 to add this task grid, for some context. 

https://github.com/facebook/RapiD/pull/26
https://github.com/facebook/RapiD/pull/135

**Comment by Bonkles** [comment]
Fixed this while i was taking care of #913 - the grid should work once again. Grid lines have a transparency and are thinner than the task boundary: 

https://user-images.githubusercontent.com/1887955/231550519-85795967-9885-47c7-9e20-56cdd49e5721.mov

**Comment by matheusgomesms** [comment]
Hi!

I am using Rapid as external editor in many projects in HOT Tasking Manager, and I don't like/am not used to use the embedded editor straight in the TM. I use the Custom Editor function and the https://rapideditor.org/rapid URL. Since some time (don't remember, maybe since v2?), the GPX with the task boundary is not passed to Rapid.

Is this something weird from TM or Rapid side?

Thanks!

**Comment by bhousel** [comment]
> Is this something weird from TM or Rapid side?
> Thanks!
> (you can test is here, for example: https://tasks.hotosm.org/projects/18369/)

Hey @matheusgomesms ,  I took a look at that task and it is trying to launch Rapid with a link like this:

`https://rapideditor.org/rapid?#map=17/-4.417613653658051/-40.9295654296875&comment=%23hotosm-project-18369%20%23ProjetoCeara%20Adi%C3%A7%C3%A3o%20de%20vias%20em%20Croat%C3%A1%2C%20Cear%C3%A1&gpx=https%3A%2F%2Ftasking-manager-tm4-production-api.hotosm.org%2Fapi%2Fv2%2Fprojects%2F18369%2Ftasks%2Fqueries%2Fgpx%2F%3Ftasks%3D337`

It seems like this should work, so I'm going to open up a new issue.
