### ISSUE TITLE
Building Request: Malawi

### ISSUE THREAD

**Issue by cbeddow** [facebook/RapiD#77]
Is this the right place to request these?

**Comment by danil-kirsanov** [comment]
Yes! The good news is that Malawi was already released a few days ago -- so you can start mapping immediately. ;)

**Comment by jeffdefacto** [comment]
Reopening as this is specifically for buildings.

Currently, only the Microsoft data set is supported, but we'll leave this open to show interest.

**Comment by danil-kirsanov** [comment]
Oops, I didn't read the title!

**Comment by cbeddow** [comment]
Should I crosspost to Microsoft to ask about buildings?

**Comment by jeffdefacto** [comment]
You can contact them directly at MS_Buildings_MwAI@microsoft.com
