### ISSUE TITLE
Only show `mapwithai` in sources when Rapid roads / buildings layers were actually used

### ISSUE THREAD

**Issue by mvexel** [facebook/RapiD#775]
### Description

see for example https://www.openstreetmap.org/changeset/131890149 

I used Rapid to just delete a node, no Rapid specific layer was used.

Even better would be to identify exactly with Rapid layer was used (ML roads, MS buildings, one of the Esri layers)

### Version

2.00-alpha.3.3

### What browser are you seeing the problem on? What version are you running?

Chrome v109.0

### Steps to reproduce

1. make some regular OSM edits
2. upload them

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha3#background=EsriWorldImagery&datasets=fbRoads,msBuildings&disable_features=boundaries&map=20.00/40.78716/-111.93538

**Comment by bhousel** [comment]
I think this is just #701 still?  We fixed it but it's not deployed yet?

**Comment by mvexel** [comment]
Yea you are correct!
