### ISSUE TITLE
Change "hide rapid layer" shortcut key to more closely match "hide OSM data" shortcut key

### ISSUE THREAD

**Issue by mvexel** [facebook/Rapid#778]
### Description

This is really minor, but:

Currently, you can toggle showing OSM data with <kbd>Alt</kbd> / <kbd>Option</kbd> + <kbd>w</kbd>
You can toggle showing Rapid roads / buildings with <kbd>Shift</kbd> + <kbd>r</kbd>

It would be nice if both would have either shift or option / alt as a modifier. And add a shortcut to hire both if it does not already exist?

**Comment by bhousel** [comment]
I missed this, but we actually did this in #1400 !

Now:
<kbd>Shift</kbd>+<kbd>O</kbd> Toggle OSM Data
<kbd>Shift</kbd>+<kbd>N</kbd> Toggle OSM Notes
<kbd>Shift</kbd>+<kbd>R</kbd> Toggle Rapid Data

We're continuing this pattern with other data layers too in #1592
