### ISSUE TITLE
If I load without the backround=XXX in URL then no background

### ISSUE THREAD

**Issue by atiannicelli** [facebook/RapiD#779]
### Description

When I load without the background=XXX in the URL then I get no background. No default as I expected it would just pick one. But then I was also unable to pick one from the menu as well.

### Version

2.00-alpha.3.3

### What browser are you seeing the problem on? What version are you running?

Chrome v109.0

### Steps to reproduce

go to
https://mapwith.ai/rapid-v2-alpha3#datasets=fbRoads,msBuildings&disable_features=boundaries&map=20.06/44.08708/-103.20483
Then go to the menu and choose a background. Nothing happens.

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha3#datasets=fbRoads,msBuildings&disable_features=boundaries&map=18.68/42.78848/-83.92366

**Comment by mvexel** [comment]
May be a dupe of https://github.com/facebook/RapiD/issues/767

**Comment by atiannicelli** [comment]
yup - dupe - I will close.
