### ISSUE TITLE
road also tagged with railway=abandoned is rendered as railway

### ISSUE THREAD

**Issue by mvexel** [facebook/Rapid#788]
### Description

https://www.openstreetmap.org/way/165024953 is tagged as `highway=secondary` but also as `railway=abandoned`. However, the rendering prioritizes the `railway` tag over the `highway` tag:

![SCR-20230201-glq](https://user-images.githubusercontent.com/120452/216137682-4276c41f-f56b-4d97-9fc5-cfc50f644655.jpeg)

It should be rendered as a `highway` instead.

### Version

2.00-alpha.3.3

### What browser are you seeing the problem on? What version are you running?

Firefox v109.0

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha3#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=19.08/32.39764/-86.98759

**Comment by bhousel** [comment]
see note on #535 - that will fix this as well.
