### ISSUE TITLE
Country request: Poland

### ISSUE THREAD

**Issue by Atrate** [facebook/RapiD#79]
Poland's roads are in a not so bad state, but there are tens of thousands buildings not mapped

**Comment by jeffdefacto** [comment]
Thanks for the request @MegaArthur

**Comment by cbeddow** [comment]
@Atrate how is this looking now?

**Comment by Atrate** [comment]
I haven't checked out whether there are RapID buildings available now, but Poland has recently made available its govt buildings dataset, which is of much higher quality than MS building footprints. You can see and import them (with appropriate review) through https://budynki.openstreetmap.org.pl/
