### ISSUE TITLE
area halo protrudes too much for sharp angles

### ISSUE THREAD

**Issue by mvexel** [facebook/Rapid#792]
### Description

When an area outline has really sharp angles, like here: https://www.openstreetmap.org/node/960721045 the halo protrudes in a wild way: 

![image](https://user-images.githubusercontent.com/120452/216715170-87819589-c6a6-44f0-bccd-6327d3ec71bd.png)

### Version

2.00-alpha.3.3

### What browser are you seeing the problem on? What version are you running?

Firefox v109.0

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha3#background=EsriWorldImageryClarity&datasets=fbRoads,msBuildings&disable_features=boundaries&map=13.00/27.4300/-81.2183

**Comment by bhousel** [comment]
good catch - just adding this screenshot of Rapid v1 for comparison with the previous rendering.

<img width="424" alt="Screenshot 2023-02-03 at 4 52 43 PM" src="https://user-images.githubusercontent.com/38784/216718082-b552daaa-616a-49c2-adfd-f89decc73407.png">
