### ISSUE TITLE
"Parking Lot" implies `parking=surface`

### ISSUE THREAD

**Issue by mvexel** [facebook/RapiD#794]
### Description

When I use the "Parking Lot" preset on an area, I expect the tag `parking=surface` to be added by default. Right now, the Type is left undefined.

![image](https://user-images.githubusercontent.com/120452/217064982-39f38437-3bc6-4d41-b3cb-eb6be1147ae4.png)

### Version

2.00-alpha.3.3

### What browser are you seeing the problem on? What version are you running?

Firefox v109.0

### Steps to reproduce

1. Apply the "Parking Lot" preset to an area

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha3#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries,rail&id=w-12&map=20.17/40.38219/-80.69696

**Comment by jjiglesiasg** [comment]
I do agree, surface tag should be part of the preset data

**Comment by tordans** [comment]
Presets for Rapid and iD are part of the https://github.com/openstreetmap/id-tagging-schema project.

I disagree that this is a good idea. Its easy to have apps like StreetComplete catch all cases where the sub tag is missing and ask for it to be added. It is super hard to re-validate an existing default tag.

In areas that are mapped in more details, parking areas represent street side parking more often than surface parking. Example: https://parkraum.osm-verkehrswende.org/project-prototype-neukoelln/?map=parkingmap#19/52.47699/13.44574 (Website in GER).

It might be an option to have a preset that implies surface parking for regions of the world that usually have big surface parking areas, like the US.

**Comment by mvexel** [comment]
good point @tordans 

I actually have a MapRoulette challenge where I set up *larger* areas ( I think with a circumference of more than 250m) and ask if these are `parking=surface`. The smaller the area the more likely it is to be `street_side` or something else.

**Comment by boothym** [comment]
Suppose this is something for the tagging schema project, but perhaps it would good to have a generic "Car Parking" preset for amenity=parking and then also have "Car Park" (en-gb) and "Parking Lot" (en-us) referring to parking=surface?

**Comment by mvexel** [comment]
Perhaps the name "Parking Lot" is what needs reconsidering. 

At least in U.S. English, "Parking Lot" implies a (usually paved) area at street level that is dedicated to parking cars. This is (I think?) what `parking=surface` would also designate.

**Comment by bhousel** [comment]
For now we are still using the presets that are published at 
https://github.com/openstreetmap/id-tagging-schema

So any issues related to the tagging, or what fields appear on this screen, would have to be made over in that other project.
