### ISSUE TITLE
2-finger touchpad gesture to zoom the map

### ISSUE THREAD

**Issue by fpurcell** [facebook/RapiD#799]
### Description

Similar to google / leaflet / etc..., I want to zoom the map on my laptop with 2 fingers on the touchpad.  Not having that (or dbl-click) to zoom the map breaks well established ui functionality.

See https://github.com/facebook/RapiD/issues/798

**Comment by Bonkles** [comment]
Hi @fpurcell - can you give us more information about what type of system you're using? Macbookpro, thinkpad, etc.? Also, if you use the built-in bug nub (pic: 
<img width="143" alt="image" src="https://user-images.githubusercontent.com/1887955/218829329-f02f85c9-f011-434a-854c-d9e94957cd2c.png">
) that will auto-fill a bunch of information for us like browser version, OS, version of RapiD you're using, etc.

**Comment by fpurcell** [comment]
Closing ... on return visit, these gestures now working.

MacBook Air 2020 w/ Ventura 13.2.1

Firefox 109.0.1 
Chrome 109.0.5414.119
