### ISSUE TITLE
Scroll wheel moves map up and down but doesn't zoom

### ISSUE THREAD

**Issue by watmildon** [facebook/RapiD#801]
### Description

I clicked on the RapiD 2.0 link at the bottom of this diary: https://www.openstreetmap.org/user/mvexel/diary/400973

Tried to use the scroll wheel to zoom into an area of interest and got this: 

![image](https://user-images.githubusercontent.com/118567155/218910621-cccf415c-1e31-46bc-a2fd-c63e6669d71b.png)

### Version

2.0.0-beta.0

### What browser are you seeing the problem on? What version are you running?

Chrome v109.0

### Steps to reproduce

Same as above.

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-beta#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=paths,building_parts,landuse,boundaries,water,rail,pistes,aerialways,power,past_future,others&map=2.00/-87.7/0.0

**Comment by bhousel** [comment]
Thanks! I'm going to close here as we are tracking this on #680 ..
The code to guess trackpad 2-finger-pans from 2-finger-pinches is notoriously complicated and gets it wrong too often.
As a workaround, if you hold down the <kbd>Shift</kbd> key, mousewheels should always zoom/unzoom.

BTW @Bonkles is there a way to add the user's detected Operating System to the bug reporting tool?

**Comment by watmildon** [comment]
Gotcha. I must have had a total brain failure when I searched. Sorry for the noise!

**Comment by Bonkles** [comment]
No problem @watmildon - I'd much rather have too many bugs filed than not enough. Thanks for reporting! 

@bhousel I opened #805 to add OS/platform to the ingestion form autocomplete.
