### ISSUE TITLE
Map URL with streetside imagery confuses Rapid

### ISSUE THREAD

**Issue by mvexel** [facebook/RapiD#803]
### Description

Some URLs that include streetside imagery parameters throw an error like this and the application won't load completely:

Chrome:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'captured_at')
    at PixiLayerMapillaryPhotos.js:84:63
    at Array.filter (<anonymous>)
    at Y6.filterSequences (PixiLayerMapillaryPhotos.js:84:29)
    at Y6.renderMarkers (PixiLayerMapillaryPhotos.js:114:31)
    at Y6.render (PixiLayerMapillaryPhotos.js:185:10)
    at s7.render (PixiScene.js:134:13)
    at a7._app (PixiRenderer.js:428:16)
    at a7._tick (PixiRenderer.js:261:14)
    at a0.emit (TickerListener.ts:67:25)
    at Jn.update (Ticker.ts:427:37)
```

Firefox:
```
Uncaught TypeError: o.properties is undefined
    t PixiLayerMapillaryPhotos.js:84
    filterSequences PixiLayerMapillaryPhotos.js:84
    renderMarkers PixiLayerMapillaryPhotos.js:114
    render PixiLayerMapillaryPhotos.js:185
    render PixiScene.js:134
    _app PixiRenderer.js:428
    _tick PixiRenderer.js:261
    emit TickerListener.ts:67
    update Ticker.ts:427
    _tick Ticker.ts:129
.....
```

### Version

2.0.0-beta.0

### What browser are you seeing the problem on? What version are you running?

Firefox v109.0

### Steps to reproduce

1. Load URL below
2. Inspect console

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-beta#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=19.00/36.09668/-86.73818&photo=streetside/1148715026&photo_dates=2020-01-01_&photo_overlay=mapillary,streetside

**Comment by bhousel** [comment]
I fixed this in 571c50c62, will merge to main soon.
