### ISSUE TITLE
Line endpoint snapping results in two 'very close nodes' that need to be merged

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#807]
### Description

This one was reported by @jjiglesiasg as part of #804 - splitting it out here to track separately. 

### Version

2.0.0-beta.0

### What browser are you seeing the problem on? What version are you running?

Chrome v110.0

### Steps to reproduce

To repro this issue, you must draw one line with two points, then end the draw. 

Then, create another line by clicking one point, then for its second point, snap to one of the endpoints of the first line.

You will see that while the second line has 'snapped' to the first one, it looks like we are actually creating two separate points for these lines in the same area. 

This results in the following lint warning: 

![image](https://user-images.githubusercontent.com/1887955/219438022-95b9914d-0154-4b0e-897f-69d338febcc2.png)

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-beta#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=n-27&map=19.97/42.58940/-71.33772

**Comment by mvexel** [comment]
related to other snapping issues reported earlier like #752 #572 #758 #688 #719 ?
