### ISSUE TITLE
Cliff styling differences from v1

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#809]
### Description

Cliff lines have a thicker stroke than they do in Rapid v1. Also, it looks like the directionality indicator arrows are offset from the center of the way, leaving gaps: 

![image](https://user-images.githubusercontent.com/1887955/219443751-9d1185a1-ec47-45a8-ac43-41d0f96b92fc.png)

Compare this with v1 cliffs, which are thinner and gapless: 

![image](https://user-images.githubusercontent.com/1887955/219443844-3aba2c9b-b62d-4c0c-96bb-6f651bd5b43c.png)

### Version

2.0.0-beta.0

### What browser are you seeing the problem on? What version are you running?

Chrome v110.0

### Steps to reproduce

Simple create a line and assign it the 'cliff' attribute to see the difference in style.

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-beta#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=18.70/36.01815/-114.73878

**Comment by bhousel** [comment]
Does this matter much?

**Comment by mvexel** [comment]
@bhousel I don't think it's a huge issue. And I say that as an occasional ridge mapper.

**Comment by bhousel** [comment]
going to close this, I think the new one looks better actually
