### ISSUE TITLE
Cannot switch from move mode to rotate mode

### ISSUE THREAD

**Issue by cbeddow** [facebook/Rapid#818]
### Description

In v1, I typically select a building, hit M key to move it, then before clicking, I hit R key to switch to rotate mode, so I can align it with the satellite map, then click to finish.

In v2 when I am in move mode, I hit the R key and nothing happens to the building, it stays in move mode. I have to click first then hit R to rotate. This adds a step so slows me down.

### Version

2.0.0-beta.0

### What browser are you seeing the problem on? What version are you running?

Chrome v110.0

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-beta#background=EsriWorldImageryClarity&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w-1314881948303995373&map=20.06/25.40854/-101.01982

**Comment by bhousel** [comment]
Ah yeah I was just looking at this a few days ago. It was bothering me too 😆 

The details on this one are: previously we had this complicated architecture with Modes and Behaviors but also some of the Modes had special built in Behaviors to do the key listening.  We made a new Behavior for key listening but it needs some cleanup.
