### ISSUE TITLE
When trying to move a way node close to an area edge, the node jump

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#821]
### Description

I was trying to align a road close to and area edge when sudenly the node jump to another place dragging the road, try 3 times and the behavior was the same. Took some screenshoots
![Screenshot 2023-02-18 03 40 20](https://user-images.githubusercontent.com/22849578/219848578-aa5646eb-1405-405d-b1af-177bb075c31c.png)
![Screenshot 2023-02-18 03 40 45](https://user-images.githubusercontent.com/22849578/219848581-1559563b-51cc-4499-9ce0-5da0f9e3e482.png)

### Version

2.0.0-beta.0

### What browser are you seeing the problem on? What version are you running?

Chrome v110.0

### The OS you're using

Win10

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-beta#background=Mapbox&datasets=fbRoads,msBuildings&disable_features=power&map=18.44/-18.18017/-68.70825&overlays=osm-gps

**Comment by jjiglesiasg** [comment]
This behavior seems similar when the area edge highlight as selected when you are adding or editing a line/way adjacent or close to the edge of such area

**Comment by Bonkles** [comment]
I'm going through these bugs, trying to repro on a windows machine. This one was filed a few minor versions ago, and I can't seem to reproduce it.  I know we have fixed a bunch of bugs/issues with the border snapping since then though!

**Comment by Bonkles** [comment]
Cannot repro.
