### ISSUE TITLE
New Data should not be abide by same rules of edition than ID, before being uploaded to the OSM Database

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/RapiD#822]
### Description

One of the problems that I ever encounted with the AI Data suggestion is that several magenta lines once accepted as highway=residential (despite what later will become) are too big to be moved, adjusted or otherwise edited, that produce an unnessesary burden for the mapper to be splitting the line and adjust move or offset chunck by chunck.  This is totally ilogic to me, we should be able to move or adjust the whole line created independently of the size or zoom, because that line is not yet in the Database of OSM.

Mappers are being restricted, by an ID rule that is perhaps Ok for EXISTING DATA, but not ok for data that is not YET part of the Database, as is the data suggested by RAPID AI.

**Comment by bhousel** [comment]
I agree that we can relax the rules about what the user can edit , for features that they just drew and haven't been uploaded to OSM yet.  👍
