### ISSUE TITLE
FetchError: request to https://raw.githubusercontent.com/openstreetmap/id-tagging-schema/main/dist/presets.min.json failed, reason: getaddrinfo ENOENT

### ISSUE THREAD

**Issue by dlfming** [facebook/Rapid#835]
When I ran "npm run all" to "build:data", I got an error.

**Comment by dlfming** [comment]
my node version is 18.13.0
my npm version is 8.19.3

**Comment by bhousel** [comment]
Thanks for reporting - I did comment this out a while ago, see #474, so I haven't seen errors like this in a while.
Is your repo definitely up to date with the code on our main branch?

**Comment by bhousel** [comment]
Since I can't repro this, I'm going to assume it was just an intermittent issue with the user's network.
I'm closing for now, but happy to reopen if it happens again?
