### ISSUE TITLE
When moving the minimap, the extent box should remain centered

### ISSUE THREAD

**Issue by mvexel** [facebook/RapiD#836]
### Description

A useful feature of the minimap is that you can drag it and move the main map. Because the box that indicates the current main map extent moves with the minimap as you drag it, it becomes harder to move the minimap accurately:

https://user-images.githubusercontent.com/120452/223285168-ae93d250-4283-4cae-a966-fc9ac1ec11f4.mov

I would prefer it if the box remained centered, so you can accurately predict what the main map extent will be when you release.

### Version

2.0.0-beta.0

### What browser are you seeing the problem on? What version are you running?

Chrome v110.0

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-beta#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=indoor,boundaries,pistes&map=18.36/38.77665/-112.07941

**Comment by bhousel** [comment]
I agree - we have this on #485 as a followup todo item
