### ISSUE TITLE
Preference settings missing; mouse wheel behavior option

### ISSUE THREAD

**Issue by repairfox** [facebook/Rapid#841]
### Description

My scroll wheel pans the map. I read issue [#680 ](https://github.com/facebook/RapiD/issues/680), and it seems I should have the option to change behavior in preferences.
![rapid](https://user-images.githubusercontent.com/94087824/223598341-ecd3a647-5cf3-4d14-b4a4-77cfda1df9f0.png)

Using Chrome on Windows 10 with wireless mouse. 

I tried full browser refresh no no avail.

### Version

2.0.0-beta.0

### What browser are you seeing the problem on? What version are you running?

Chrome v110.0

### The OS you're using

Windows 10 Pro

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-beta#background=VBMPImagery_Most_Recent&datasets=msBuildings&map=17.00/38.12945/-79.06190&poweruser=true

**Comment by bhousel** [comment]
Thanks! the preference option was added in #680 - we have to push out a new beta that includes the fix.
