### ISSUE TITLE
Upgrade to id-tagging-schema v6

### ISSUE THREAD

**Issue by bhousel** [facebook/RapiD#846]
Just tracking that I updated the preset code to add partial support for the [id-tagging-schema v6](https://github.com/openstreetmap/id-tagging-schema/blob/main/CHANGELOG.md#600) that was recently released.

Some things we don't support at this time:
- Röntgen icons (there are only a few of these anyway and they are hard to generate)
- Preset "Aliases" (these are like terms but different)
- New types of fields yet (like `colour` , `date`, or `directionalCombo`) but mappers can still add this information in the raw tag editor like they used to be able to. 
- Icons in combo field values

I'll link back to this issue if/when we add more support for these things.

Work was done in these commits 
- 0bef7fbea - Resolve preset and field references new to id-tagging-schema v6
- 53699bbac - Fetch strings for id-tagging-schema v6 as well
- df41f3d4d - Upgrade to id-tagging-schema v6

**Comment by bryceco** [comment]
The Röntgen dependency is a PITA and really ridiculous. There's no way I'm adding all those prerequisites to my project, so for now I'm just copying them from iD from https://raw.githubusercontent.com/openstreetmap/iD/develop/svg/roentgen/*

Hopefully they fix this upstream.

**Comment by tordans** [comment]
FYI I created https://github.com/enzet/map-machine/issues/149 to track the issues of having the icons more easily consumed. I think there was no issue, yet, and it sounds like that really should be easier.

**Comment by bhousel** [comment]
Yes, I know I could copy the icons from the iD repo, but I really don't want the increased maintenance burden of looking there for new icons.  For now these are the replacements I hardcoded:

https://github.com/facebook/RapiD/blob/0bef7fbea4a120201135335d39b7196564c8889f/modules/presets/index.js#L25-L37

**Comment by bhousel** [comment]
I just added the Röntgen icons in 589d43d78 .

The work I just completed on #925 gives us much more flexibility to support new spritesheets.  These get converted to WebGL textures on the fly now, so we don't need to prepare a separate spritesheet for Pixi anymore.
