### ISSUE TITLE
CORS error accessing imagery for Portugal provided by the DGT

### ISSUE THREAD

**Issue by waldyrious** [facebook/Rapid#848]
### Description

I'm getting a black background if I try to use the DGT-provided satellite imagery for Portugal. This happens with both the 2018 and the 2021 layers:
- Orthophotos of mainland Portugal - 25cm - 2018 (DGT)
- Orthophotos of the northern portion of mainland Portugal - 25cm - 2021 (DGT)

Here's the full error message for one of the missing tiles, as reported by the browser:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cartografia.dgterritorio.gov.pt/wms/ortos2018?LAYERS=Ortos2018-RGB&STYLES=default&FORMAT=image/jpeg&CRS=EPSG:3857&WIDTH=256&HEIGHT=256&BBOX=-936353.5963630663,5090247.460914459,-936277.1593347918,5090323.897942733&VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)
```

The 2018 background layer is usable in v1.1.9. I don't know about the 2021 layer because it doesn't show up in the list of available layers there :thinking:

### Version

2.0.0-beta.0

### What browser are you seeing the problem on? What version are you running?

Firefox v111.0

### The OS you're using

Linux (Ubuntu 20.04)

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-beta?fbclid=IwAR0g6790Ozoj9eYhScyDhCxxV8h2qH0CHaTxNCOuL5p6f7rE-K_JqrWUKtI#background=ORTOS_DGT_2018_WMS&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w-2821748028026636346&map=20.16/41.52672/-8.41103

**Comment by bhousel** [comment]
Thanks for reporting, but unfortunately Rapid isn’t able to display imagery or data from another server unless the server is configured to allow [cross origin-resource-sharing (CORS)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

Although browsers can sometimes display images or data as “passive” content, our application isn’t allowed to read those pixels into a Canvas or WebGL context.

There is a lot more information on this link below, along with examples of how to configure a server to allow cross origin requests. 
https://webglfundamentals.org/webgl/lessons/webgl-cors-permission.html

**Comment by waldyrious** [comment]
Thanks for the response. I thought this could be a bug because Rapid v1.1.9 _is_ able to use at least the 2018 layer. Is it because the implementation is different? I mean, is the way Rapid 1.x uses those tiles considered "passive" content, to use your words?

**Comment by bhousel** [comment]
> I mean, is the way Rapid 1.x uses those tiles considered "passive" content, to use your words?

Yes, the implementation is a bit different - Rapid v1 loaded the tiles in `img` tags and positioned them below the map.. Rapid v2 actually loads the images into WebGL.
