### ISSUE TITLE
CICD Deploys broken after repo rename from RapiD-> Rapid

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#849]
### Description

![image](https://user-images.githubusercontent.com/1887955/226698897-b8ccb256-89c7-4f75-8fb7-f2b39aea5aa1.png)

Since the repo was renamed we have been unable to deploy artifacts to s3. 

This is because we explicitly grant ONLY this repo to assume an AWS Role that is defined in our cloud config. The role granted allows github actions to write to an S3 bucket we control, but ONLY if it comes from the repo 

https://github.com/facebook/RapiD

Since we just renamed the repo, we need to alter this rule to allow from

https://github.com/facebook/Rapid

### Version

any

### What browser are you seeing the problem on? What version are you running?

n/a

### The OS you're using

n/a

### Steps to reproduce

Commit to main and watch the actions listing at https://github.com/facebook/Rapid/actions, find any deploy run today, see a failure. 

### The browser URL at the time you encountered the bug

n/a

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

n/a

**Comment by Bonkles** [comment]
Steps to fix: 

<see the internal sister task to this issue for detailed cloud config steps>

**Comment by bhousel** [comment]
Was this #855?  They seem to be working now..

**Comment by Bonkles** [comment]
Yes, they're only working because I restored the 'old way' of doing things, just spoke with Martijn about this. Will re-open #855.

**Comment by bhousel** [comment]
Still not sure whether there is anything to do here - our deploys seem fine now.

**Comment by bhousel** [comment]
Closing, as I think this is working now?
