### ISSUE TITLE
Feature request: show heatmap of buildings or other layers at zoom 10-13

### ISSUE THREAD

**Issue by cbeddow** [facebook/Rapid#857]
### Description

When zoomed out, it would be nice to see a heatmap of where currently visible Rapid assist layers are, in order to identify a hotspot to zoom into

This might be possible by either converting the data just to dots at zoom 10-13 and displaying those, on the fly, or maybe it would need server side work (I can help, but tough with so many datasets) to bucket things

Another idea could be to make a generic tile layer of just quadkeys and then color code it darker to lighter based on the count of centroids of the activated layer (buildings, roads, addresses, etc) in the quadkey, by cross checking to the API, for zoom 10-13

**Comment by Bonkles** [comment]
Bumpity-bump. Going to see if I can't dust this one off for some upcoming projects we have coming down the pike.
