### ISSUE TITLE
Undo/redo not possible during draw line/area modes

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#858]
In RapiD v1, we were able to undo/redo a draw gesture while still in the middle of drawing. 

We should restore this functionality before GA of rapid 2.0.

**Comment by bhousel** [comment]
looks like this is also #819

**Comment by bhousel** [comment]
In bc32bc2f6 I ended up making it so that it doesn't work yet, but it at least won't crash
This is probably a first thing to fix post-launch.

**Comment by jjiglesiasg** [comment]
This is still happening, and is a big problem while mapping. Needs to be fixed ASAP...
