### ISSUE TITLE
By default, "Shift" must be pressed to zoom in the map

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [facebook/Rapid#860]
### Description

This is super counterintuitive. It's the first time that I see such a thing, except when it's Google Maps embedded in another website. Shift shouldn't have to be pressed just to zoom in. Except if there's something I really didn't understand, at least let us disable this feature

### Version

2.0.0-beta.0

### What browser are you seeing the problem on? What version are you running?

Chrome v111.0

### The OS you're using

Windows 11

### Steps to reproduce

Try to zoom in the map

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-beta#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=6.32/46.606/3.569

**Comment by bhousel** [comment]
Thanks! the preference option was added in https://github.com/facebook/Rapid/issues/680 - we have to push out a new beta that includes the fix.
