### ISSUE TITLE
Unable to use French public satellite imagery (IGN)

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [facebook/Rapid#861]
### Description

When trying to use the BDOrto IGN imagery, no tile is loaded. When going into the console, here are the 2 errors : 
"Access to image at 'https://proxy-ign.openstreetmap.fr/94GjiyqD/bdortho/15/16844/11479.jpg' from origin 'https://mapwith.ai' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."

"GET https://proxy-ign.openstreetmap.fr/94GjiyqD/bdortho/19/269514/183672.jpg net::ERR_FAILED 302"

### Version

2.0.0-beta.0

### What browser are you seeing the problem on? What version are you running?

Chrome v111.0

### The OS you're using

Windows 11

### Steps to reproduce

Use the BDOrtho layer in France

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-beta#background=fr.ign.bdortho&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w58294608&map=19.04/47.34221/5.06107&overlays=osm-gps

**Comment by bhousel** [comment]
Thanks for reporting, but unfortunately Rapid isn’t able to display imagery or data from another server unless the server is configured to allow [cross origin-resource-sharing (CORS)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

Although browsers can sometimes display images or data as “passive” content, our application isn’t allowed to read those pixels into a Canvas or WebGL context.

There is a lot more information on this link, along with examples of how to configure a server to allow cross origin requests. 
https://webglfundamentals.org/webgl/lessons/webgl-cors-permission.html

**Comment by TheWonderfulTartiflette** [comment]
Sorry for the very late answer
I understand, but with the 1.X version of Rapid, we were able to, but not anymore with the former beta, now 2.0 version of Rapid

**Comment by bhousel** [comment]
I tried this out and browsers still expect the proxy server to also set the `Access-Control-Allow-Origin` header too.  Maybe openstreetmap.fr can do this?

https://stackoverflow.com/questions/18539403/chrome-cancels-cors-xhr-upon-http-302-redirect


> Investigation of the problem showed that his XHR was not landing on the CORS-enabled URL directly, but was being redirected to it through an HTTP 302 (redirect) response.
>
> So bear in mind that the redirecting URL must also include an Access-Control-Allow-Origin header, else the browser will stop right there with its attempted cross-domain request.

#### Fails through openstreetmap.fr proxy:

![Screenshot 2023-05-02 at 3 34 21 PM](https://user-images.githubusercontent.com/38784/235767506-ef2f98b5-0d7f-4b74-8944-a868b566dfc8.png)

#### Seems ok on ign.fr:
![Screenshot 2023-05-02 at 3 38 17 PM](https://user-images.githubusercontent.com/38784/235768357-f68ec38b-c889-4cce-8c1e-8315678a40af.png)

**Comment by Nekzuris** [comment]
You can use the direct URL in the custom layer
`https://data.geopf.fr/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=ORTHOIMAGERY.ORTHOPHOTOS&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&FORMAT=image/jpeg`

**Comment by Nekzuris** [comment]
Should be fixed by https://github.com/osmlab/editor-layer-index/pull/2468
