### ISSUE TITLE
Hungarian orthophoto cannot be used + mouse wheel + problem list missing

### ISSUE THREAD

**Issue by misibacsi** [facebook/Rapid#862]
### Description

1. We prefer using the "FÖMI orthophoto" on territory of Hungary. However in Rapid v2 they are missing (we have two time versions of these).

2. Mouse wheel must do zoom.

3. When I click on "problems" icon on the right panel (key button: "I"), it does not show the list of problems. At the bottom of the page, it shows there are x number of problems.

### Version

2.0.0-beta.0

### What browser are you seeing the problem on? What version are you running?

Firefox v111.0

### The OS you're using

Win 11

### Steps to reproduce

1. Go to over the territory of Hungary, "B" and select "FÖMI". (it is Hungary-only photo, other areas are not covered, they are black - it is not error)

2. Use mouse wheel, it scrolls the screen up and down, instead of zoom.
3. Select "I", when problem number is shown at the bottom.

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-beta#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=indoor,landuse,boundaries,pistes,aerialways,power,past_future,others&map=16.00/45.8555/18.0385

**Comment by bhousel** [comment]
> 1. We prefer using the "FÖMI orthophoto" on territory of Hungary. However in Rapid v2 they are missing (we have two time versions of these).

Hey @misibacsi thanks for opening this.. 
I try to take a look at the "FÖMI orthophoto" sources, but I'm getting a CORS error when I try to use them.

![Screenshot 2023-03-28 at 7 12 59 PM](https://user-images.githubusercontent.com/38784/228387382-7233373b-73a6-4bbf-a28f-e2525143ad24.png)

I'll see whether this is something we can workaround..

**Comment by misibacsi** [comment]
Did you previously go to territory of Hungary? (Try to search "Budapest"
city). FÖMI photo is made over it. All other territory is black, this is
normal.
I did not receive error messages.

Bryan Housel ***@***.***> ezt írta (időpont: 2023. márc. 29.,
Sze 1:14):

**Comment by bhousel** [comment]
I think these issues might be working now in the latest beta.. Please let me know if I've missed any!

**Comment by misibacsi** [comment]
The FÖMI orthophoto is still black over Hungary, so this is not solved yet.
The problems 2. and 3. are OK now.

[https://mapwith.ai/rapid-v2-beta#background=FOMI_2007_2010&datasets=fbRoads,msBuildings&disable_features=indoor,landuse,boundaries,pistes,aerialways,power,past_future,others&map=13.48/47.5357/19.0556&overlays=OpenAerialMapMosaic,hu-hillshade](url)

**Comment by bhousel** [comment]
> The FÖMI orthophoto is still black over Hungary, so this is not solved yet.

I did some investigation today and it turns out that we aren't able to display imagery in WebGL unless it's configured for cross-origin-resource-sharing.

There is a lot more information on this link below, along with examples of how to configure a server to allow cross origin requests. 
https://webglfundamentals.org/webgl/lessons/webgl-cors-permission.html

**Comment by misibacsi** [comment]
I modify and correct my report:
1. FÖMI orthophoto now can be used by installing an extension into Firefox which blocks the CORS error report.
2. The "problem list" is usable, but not OK, as at the first load it is always empty (although there are indicated problems), and the list only later is populated.

**Comment by waldyrious** [comment]
> an extension into Firefox which blocks the CORS error report

Apparently there are several extensions to do this. FWIW, the [CORS Unblock](https://addons.mozilla.org/en-US/firefox/addon/cors-unblock/) extension, which is [open source](https://github.com/balvin-perrie/Access-Control-Allow-Origin---Unblock), did work for me as a way to bypass this issue.

I will nevertheless try to reach out to the imagery provider to request that they add the `Access-Control-Allow-Origin: *` header, as recommended [here](https://community.openstreetmap.org/t/rapid-v2-5-released-today/123326/10).

**Comment by gy-mate** [comment]
> I will nevertheless try to reach out to the imagery provider to request that they add the Access-Control-Allow-Origin: * header, as recommended [here](https://community.openstreetmap.org/t/rapid-v2-5-released-today/123326/10).

I've just sent an email about this to the [server administrator](https://wiki.openstreetmap.org/wiki/Hungary/%C3%9Czemeltet%C3%A9s#:~:text=Miszori%20Kriszti%C3%A1n).

**Comment by gy-mate** [comment]
It looks like that @grinapo is the current server administrator.

**Comment by gy-mate** [comment]
@grinapo fixed it—thanks! :)
