### ISSUE TITLE
Toolbars freeze 

### ISSUE THREAD

**Issue by aronkvh** [facebook/Rapid#864]
### Description

The point,line,area + save toolbar freezes every now and then. Hover states and tooltips work, but clicking on them does nothing. The side toolbar still works. The only way solve it (ctrl+s doesn't work either) is to force reload the page.

### Version

2.0.0-beta.0

### What browser are you seeing the problem on? What version are you running?

Firefox v111.0

### The OS you're using

Linux - KDE Neon

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-beta#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=20.40/47.98803/22.51389&offset=-3.75,-1.31

**Comment by jjiglesiasg** [comment]
Happening to me as well. Quit using V2 for a while because I lost some serious works

**Comment by bhousel** [comment]
Closing here, it seems to be working now..
