### ISSUE TITLE
Duplicate data from MS Buildings layer in some places

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#873]
### Description

As reported by user `zbrown` on the osm US slack, it looks like we're getting duplicated buildings in some areas in Rapid. 

This behavior seems to occur in both rapid v1 and in rapid v2 beta. 

We will need to break down the investigation into several parts: 
1) Are we receiving duplicate way IDs from the back-end? Or are we receiving different way IDs with the same node data? 
2) Are we introducing the duplicates as part of the map with AI backend service, or are we receiving the duplicates from the microsoft back-end? 

### Version

1.1.x, 2.0.0.b0

### What browser are you seeing the problem on? What version are you running?

Chrome 107

### The OS you're using

MacOS

### Steps to reproduce

navigate to the spot indicated in the URL, you can observe that the microsoft buildings are addable *twice* per building, as opposed to once. 

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=20.64/45.08908/-93.49389

**Comment by tsmock** [comment]
I'll go ahead and add what I put in chat a few weeks ago:
> How are you guys handling duplicate data?
> Specifically, with https://mapwith.ai/maps/ml_roads?bbox=-95.7946849,39.030297,-95.7886398,39.0346355&result_type=road_building_vector_xml&conflate_with_osm=true&theme=ml_road_vector&collaborator=josm&token=ASb3N5o9HbX8QWn8G_NtHIRQaYv3nuG2r7_f3vnGld3KhZNCxg57IsaQyssIaEw5rfRNsPpMwg4TsnrSJtIJms5m&hash=ASawRla3rBcwEjY4HIY I am getting duplicated data.
>
> Look for 39.033121373812 (node id=`-4222309733446286915`). There are two duplicate entries with it, and more importantly, there are two buildings with the same node ref list but with different ids.
>
> Playing around with https://mapwith.ai/rapid#map=19.93/39.03307/-95.79104 shows that there is (minimally) a UI issue, and it is possible to add both of the buildings.

So, to answer the questions in the ticket:
1. Yes, we are receiving duplicate data from the backend
2. I don't know

**Comment by Bonkles** [comment]
Okay, in that case I will dig in on #2.

**Comment by tsmock** [comment]
I'm going to _guess_ that `we [are] receiving the duplicates from the microsoft back-end` since we have two ways with separate ids but the same node ids.

**Comment by Bonkles** [comment]
Idea for a patch on our (client) end of things: is it sufficient to simply discard duplicate buildings by examining their start nodes, and if equal, deduplicate?  I will include this idea in an email to the MS Api maintainers.

**Comment by Bonkles** [comment]
Email sent, awaiting response.
