### ISSUE TITLE
Can't drag the map while drawing a road anymore

### ISSUE THREAD

**Issue by mvexel** [facebook/Rapid#875]
### Description

I used to be able to drag the map while drawing a line / way. This is very convenient when you draw longer ways especially if you're zoomed in. 

I think as of beta 2 I can no longer draw and drag. See the movie for visual illustration.

What's sad is that the entirety of the way already drawn disappears as well :(

https://user-images.githubusercontent.com/120452/229169094-a360ad64-1b2a-47ea-bc42-177524529440.mov

### Version

2.0.0-beta.2

### Steps to reproduce

1. Start drawing a way.
2. While drawing, left click and hold to initiate dragging
3. See your way in progress disappear :(

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-beta#background=EsriWorldImagery&datasets=fbRoads,msBuildings&map=21.56/40.54441/-111.84823

**Comment by mvexel** [comment]
This is related to https://github.com/facebook/Rapid/issues/687 which is now fixed but not in the way I expected. The 'nudging' is..okay as is the arrow key panning, but I really prefer to be able to do this: (taken from iD)


https://user-images.githubusercontent.com/120452/229171818-d7179a8f-79b1-4d00-863c-a76dc74b50d6.mov

**Comment by bhousel** [comment]
Oh yeah, I agree the nudging that happens at viewport edge is still messed up ..

**Comment by mvexel** [comment]
I think this is superseded, but not the same as, https://github.com/facebook/Rapid/issues/879

I can now drag the map while drawing a way or area, but it results in the line or area in progress disappearing altogether.
