### ISSUE TITLE
Address layer ends up underneath OSM objects

### ISSUE THREAD

**Issue by Busterama452** [facebook/Rapid#877]
### Description

When trying to use the National Address Dataset, or pretty much any of them, the rapid feature for that address ends up layered underneath of existing openstreetmap objects and it can be difficult to near impossible to select the feature to add and use it.

### Version

2.0.0-beta.0

### What browser are you seeing the problem on? What version are you running?

Chrome v111.0

### Steps to reproduce

Using this building
https://www.openstreetmap.org/way/1120420627

Go to that building on Rapid
https://mapwith.ai/rapid#background=Maxar-Premium&datasets=msBuildings,e75b56f13b404d7d8b47ef8be1c619ec&disable_features=boundaries&map=21.00/33.34317/-111.43846
Add the United States Address features dataset.
The address feature will then be underneath a line for that building and cannot be selected without going to extreme zoom levels to select and add it.

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-beta#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=boundaries&map=2.00/0.0/0.0

**Comment by bhousel** [comment]
Thanks @Busterama452 , can you refresh your browser and confirm that you are using the latest software?  It should say "2.0.0-beta.2" in the bottom right corner of the editor?

We fixed the layer stacking for points/areas a while ago in #626 and it seems correct when I test with that location with OSM and NAD together:

<img width="891" alt="Screenshot 2023-03-31 at 5 53 29 PM" src="https://user-images.githubusercontent.com/38784/229239893-b6134e9c-9179-4d75-992a-e3b11f42fea8.png">

**Comment by Busterama452** [comment]
Whoops, sorry.  I wasn't in the beta that time.   Works as it should.
