### ISSUE TITLE
Undoing while drawing a polygon undoes the entire thing

### ISSUE THREAD

**Issue by mvexel** [facebook/Rapid#878]
### Description

See this video:

https://user-images.githubusercontent.com/120452/229175425-d8a7ad26-5ffb-4a99-a778-ed55820340f7.mov

### Version

2.0.0-beta.2

### Steps to reproduce

1. Start drawing a polygon
2. Undo after drawing at least 2 nodes

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-beta#background=EsriWorldImagery&datasets=fbRoads,msBuildings&map=20.54/40.54438/-111.8481922

**Comment by bhousel** [comment]
Yeah, this is actually #858 
It's probably the next main thing I'll fix..
