### ISSUE TITLE
Line disappears when dragging the map while drawing

### ISSUE THREAD

**Issue by mvexel** [facebook/Rapid#879]
### Description

See this short video: 

https://user-images.githubusercontent.com/120452/229176801-3246605e-f4bf-4ef7-9efb-d15853ae4af9.mov

### Version

2.0.0-beta.2

### What browser are you seeing the problem on? What version are you running?

Firefox v111.0

### The OS you're using

mac

### Steps to reproduce

1. Start drawing a line
2. While drawing the map, click and hold to pan the map
3. See your work disappear :(

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-beta#background=EsriWorldImagery&datasets=fbRoads,msBuildings&map=20.77/40.54663/-111.84692

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/111.0

**Comment by bhousel** [comment]
Is this the same as #875?

**Comment by mvexel** [comment]
Not the same exactly, but the 'not being able to drag while drawing' is replaced with this 'I can drag while actively drawing but it just makes the line / area in progress disappear' which I described above. I closed #875
