### ISSUE TITLE
Nodes disappeared out of nowhere

### ISSUE THREAD

**Issue by kechan000** [facebook/Rapid#881]
### Description

I was using RapiD v2 beta and the map lagged, came back, and nodes stopped rendering. However, you could still interact with them

Here is a video of what I'm talking about: https://www.youtube.com/watch?v=9oe8Kg8Qsjs

### Version

2.0.0-beta.0

### What browser are you seeing the problem on? What version are you running?

Chrome

### The OS you're using

Windows 11

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-beta#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=19.76/38.91001/-104.83664

**Comment by bhousel** [comment]
Closing, as this seems to be fixed sometime since it was reported..
