### ISSUE TITLE
When undoing a line in progress, the entire way gets undo-ed / undone

### ISSUE THREAD

**Issue by mvexel** [facebook/Rapid#890]
### Description

See vid --> 

https://user-images.githubusercontent.com/120452/229622331-b8b8d189-74b3-49ec-ac22-83f512ab4997.mov

### Version

2.0.0-beta.2

### What browser are you seeing the problem on? What version are you running?

Chrome v111.0

### The OS you're using

mac

### Steps to reproduce

1. start drawing a new way
2. Undo after drawing at least 2 nodes

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-beta#background=EsriWorldImagery&datasets=fbRoads,msBuildings&disable_features=boundaries&map=19.54/27.35583/-82.47374

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

**Comment by bhousel** [comment]
yes this is #858
