### ISSUE TITLE
Difficult to connect lines to other lines and areas.

### ISSUE THREAD

**Issue by JoscTr** [facebook/Rapid#896]
### Description

I find that I have to wiggle, click, whatever, multiple times before white dot of a feature connects to another feature with or without a white dot to connect them showing a grey dot.

### Version

2.0.0

### What browser are you seeing the problem on? What version are you running?

Edge v111.0

### The OS you're using

win 11

### Steps to reproduce

As in description.

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=boundaries&map=21.00/12.10386/-68.90118

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.62

**Comment by bhousel** [comment]
yes this is #863
