### ISSUE TITLE
Hungarian orthophoto unusable, problem list missing

### ISSUE THREAD

**Issue by misibacsi** [facebook/Rapid#898]
### Description

1.
The Hungarian FÖMI orthophoto is still unusable, the background is black.
This is a "gold standard" orthophoto in Hungary regarding the geo-reference accuracy.
Please solve this serious problem, or tell me what I can do to use this background.

2.
At the bottom of the screen it it shown the number of problems. 
However, the problem list shows nothing.

Images are attached.

![rapid03](https://user-images.githubusercontent.com/11352049/229990583-e784df23-898f-413e-b572-a79ab40a2803.png)
![rapid02](https://user-images.githubusercontent.com/11352049/229990588-9c92d1c2-9a9b-4323-b5dd-6b479c6422b7.png)
![rapid01](https://user-images.githubusercontent.com/11352049/229990590-1c0f9149-05a1-45c0-a74a-a7382868fa2f.png)

### Version

2.0.0

### What browser are you seeing the problem on? What version are you running?

Firefox v111.0

### The OS you're using

win11

### Steps to reproduce

Just use the software.

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid#background=FOMI_2007_2010&datasets=msBuildings&disable_features=indoor,landuse,boundaries,pistes,aerialways,power,past_future,others&map=12.15/46.7135/17.7685&photo_overlay=streetside

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0

**Comment by misibacsi** [comment]
1. Probably I had a CORS-related error (without error message), which could be fixed with an extension for Firefox. Now it seems to show the selected FÖMI background. (I did not try to use it yet)
2. The "problem list" is now filled after a while. I tried to recreate it, and it seems  it is always empty at the first occasion.

**Comment by bhousel** [comment]
re #862

**Comment by bhousel** [comment]
> The Hungarian FÖMI orthophoto is still unusable, the background is black.
This is a "gold standard" orthophoto in Hungary regarding the geo-reference accuracy.
Please solve this serious problem, or tell me what I can do to use this background.

The easiest way to get this working is for whomever is running the `e.tile.openstreetmap.hu` web server to send this header:  `Access-Control-Allow-Origin : "*"`

It's the standard way of saying "stuff from this server can also be used by scripts on other servers".
