### ISSUE TITLE
Panning map while digitizing road road leads to lose of digitization data.

### ISSUE THREAD

**Issue by bradlewt** [facebook/Rapid#900]
### Description

While digitizing a road, whenever I click and drag to pan the background, all digitized work is lost.  This is a marked departure from the previous version where one could pan the map while a road (or other feature was selected and actively being extended).  This means that one must finish the digitization.  Video of process is [here](https://www.dropbox.com/s/8wyijjs0lkgf5w6/RoadExtensionSample.mp4?dl=0)

### Version

2.0.0

### What browser are you seeing the problem on? What version are you running?

Firefox v111.0

### The OS you're using

win

### Steps to reproduce

Start digitizing line, try to pan without stopping digitization, observe all digitized data disappear.

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid#background=Maxar-Premium&datasets=fbRoads&disable_features=boundaries&map=19.20/15.94577/-11.66542

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0

**Comment by bradlewt** [comment]
So there's no chance to _not_ have to exit drawing mode to move the map?  Rapid version 1 didn't have this issue, and neither does vanilla iDEditor.  I digitize thousands of kilometers of road and this new shift is certainly going to slow things down.

**Comment by bhousel** [comment]
> So there's no chance to _not_ have to exit drawing mode to move the map? Rapid version 1 didn't have this issue, and neither does vanilla iDEditor. I digitize thousands of kilometers of road and this new shift is certainly going to slow things down.

No, sorry, I closed it because I fixed the issue.  Pushing out an update soon.
