### ISSUE TITLE
Can't drag and draw

### ISSUE THREAD

**Issue by aronkvh** [facebook/Rapid#901]
### Description

I can't drag while drawing with the gesture or by holding shift. It makes working with 2.0 much slower than 1.0 or iD

### Version

2.0.0

### What browser are you seeing the problem on? What version are you running?

Firefox v112.0

### The OS you're using

Linux - KDE Neon

### Steps to reproduce

https://user-images.githubusercontent.com/57704946/230191824-a4617259-8ca6-48fd-a45c-f29e03ba8feb.mp4

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=boundaries&map=18.88/46.99167/18.78927

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0

**Comment by bhousel** [comment]
Sorry! yes this is #879 and we just deployed a fix for it. 
If you refresh the Rapid page, you may see v2.0.1 in the corner which contains the fix.
