### ISSUE TITLE
While drawing a line if you hit the UNDO/REDO (Crtl+Z) delete all Nodes of the line and not just the last one

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#904]
### Description

Was drawing a continuos line for a Stream and one node intersected in the wrong position a way, I hit the Undo button and all the nodes in the line were delected. I tryed several times and the behaviour was the same.

In ID and Rapid V1, undo means DELETE just the LAST NODE, not the whole element. Quite anoying behaviour

Thanks

### Version

2.0.1

### What browser are you seeing the problem on? What version are you running?

Chrome Version 105.0.5195.127 (Official Build) (64-bit)

### The OS you're using

Win10

### Steps to reproduce

Just draw any line of several nodes, and hit the Undo button. Everything drawn dissapear, not just the last node of the sequence

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w-14&map=16.84/-18.19248/-64.08329

**Comment by bhousel** [comment]
Thanks! this is a duplicate of #858
