### ISSUE TITLE
Library graphic symbol is not shown on map

### ISSUE THREAD

**Issue by misibacsi** [facebook/Rapid#910]
### Description

I created a building some hours ago. It is a library.
The graphic symbol of the library is visible on "normal" OSM.
However, the symbol is not shown on Rapid OSM.

![osm-normal_library_symbol_visible](https://user-images.githubusercontent.com/11352049/230738212-81a42a3c-f7dc-4c3d-96fd-4e4b03a4a331.png)
![osm-rapid_library_symbol_missing](https://user-images.githubusercontent.com/11352049/230738215-86c1b3d0-2fe9-4b1d-b6b9-76770fbb1476.png)

### Version

2.0.1

### What browser are you seeing the problem on? What version are you running?

Firefox v111.0

### The OS you're using

win

### Steps to reproduce

Just make sure the building is a library.

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid#background=FOMI_2007_2010&datasets=fbRoads,msBuildings&disable_features=indoor,landuse,boundaries,pistes,aerialways,power,past_future,others&map=18.28/48.18213/20.67602&photo_overlay=streetside

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0

**Comment by bhousel** [comment]
It looks like we are only adding the virtual pin if the POI has a name.  I agree it would be useful to add it even if a library doesn't have a name.
