### ISSUE TITLE
Control-click on MacOS is not producing a right-click 

### ISSUE THREAD

**Issue by bhousel** [facebook/Rapid#920]
Reported by @danil-kirsanov 👋 

Right clicking should bring up a contextual edit menu - this still works when using a physical mouse or device with a right button.  
However, on MacOS you should be able to simulate a right click by control-clicking, and this is not working.

**Comment by dankarran** [comment]
Is there a workaround for this? Using only a trackpad, I can't find a way to get the context menu, either using the ctrl button or tapping with two fingers, which I have configured in my settings.

**Comment by bhousel** [comment]
Hey @dankarran thanks for being patient -  there were a bunch of things all contributing to the right clicks sometimes being reported incorrectly.  I think I have them all fixed , so hopefully this should be better in the next release.

In the mean time, you can test in https://rapideditor.org/canary (latest build from our main dev branch) and let me know if I missed anything, thanks!

**Comment by dankarran** [comment]
Ah that's great, thank you @bhousel! I'll give it a try and let you know.

**Comment by dankarran** [comment]
I've only given it a light test based on the tasks I often need to do, but so far so good 👍
