### ISSUE TITLE
Can't extract node from a line.

### ISSUE THREAD

**Issue by mxxcon** [facebook/Rapid#921]
### Description

Trying to extract streetlight node 10812280254 from sidewalk throws error in dev console:

![image](https://user-images.githubusercontent.com/847140/232138903-ba93f12f-2bc3-447b-951e-fc7a36310885.png)

### Version

2.0.2

### What browser are you seeing the problem on? What version are you running?

Firefox v111.0

### The OS you're using

win

### Steps to reproduce

Select node
Press E or right click and select Extract

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=n10812280254&map=20.44/40.70867/-73.92343

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0

**Comment by jjiglesiasg** [comment]
Same problem happens to me. No action once requested extracting any node

**Comment by mxxcon** [comment]
> Same problem happens to me. No action once requested extracting any node

This bug is already fixed. Just gotta wait for the next release 🙂
