### ISSUE TITLE
Double-click to connect line features zooms in and snaps

### ISSUE THREAD

**Issue by bradlewt** [facebook/Rapid#923]
### Description

When one is extending a road segment and connecting it to another road segment, one has to double-click to end the line segment.  Unless one does a very slow double click, the map zooms in and ends the line segment.  When a feature is highlighted, could stop the map from zooming in upon double click?

### Version

2.0.1

### What browser are you seeing the problem on? What version are you running?

Firefox v112.0

### The OS you're using

win

### Steps to reproduce

1. start line feature
2. connect line feature to preexisting line feature with double-click
3. observe the map zoom in simultaneously with the ending of the line feature.

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid#background=Maxar-Premium&datasets=fbRoads&disable_features=paths,indoor,landuse,boundaries&map=14.20/9.8100/13.4743

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0

**Comment by bhousel** [comment]
Hey @bradlewt , just catching up on old issues that fell through the cracks. 🙈 
I do remember that we had this issue a while ago, but it seems to be fixed now.  
I'm going to close it, but please let me know if I'm missing something, thanks!
