### ISSUE TITLE
Streetside bubbles no longer loading

### ISSUE THREAD

**Issue by arch0345** [facebook/Rapid#928]
### Description

Enabling Streetside no longer loads bubbles in areas where Streetside is available:
![image](https://user-images.githubusercontent.com/85302075/233814110-67c25320-c480-4413-8432-e6fc3a2b525c.png)

Expected behavior (image from https://github.com/openstreetmap/iD/issues/9230):
![image](https://user-images.githubusercontent.com/85302075/233814122-7a6250c3-0085-4584-8222-1f8fa9339497.png)

It looks like this is caused by 503 errors in the console which are likely related to https://github.com/openstreetmap/iD/issues/8747#issuecomment-945669204

![image](https://user-images.githubusercontent.com/85302075/233813741-792f8107-94b1-40e9-a532-acb37405cc5a.png)

### Version

2.0.2

### What browser are you seeing the problem on? What version are you running?

Chrome v112

### The OS you're using

Win11

### Steps to reproduce

Enable Bing Streetside in an area where streetside is available.

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#map=20.24/45.50911/-122.78333&photo_overlay=streetside

**Comment by bhousel** [comment]
Hey @arch0345  - are you still seeing this issue?  
I clicked on the link and I'm able to see both the streetside bubbles and the related images in the viewer.

**Comment by arch0345** [comment]
> Hey @arch0345 - are you still seeing this issue? I clicked on the link and I'm able to see both the streetside bubbles and the related images in the viewer.

Yeah, still seeing this issue. I've also been able to reproduce this on Firefox (Win11) and Android 13 (Chrome/Firefox)

**Comment by arch0345** [comment]
It looks like other people on the OSM World Discord are experiencing this issue as well:
https://discord.com/channels/413070382636072960/574786080197443615/1100394503698923620

**Comment by tsmock** [comment]
I think MS just killed the API we (OSM) were using for MS StreetSide.

Sample API call (current Rapid): https://dev.virtualearth.net/mapcontrol/HumanScaleServices/GetBubbles.ashx?appkey=AuftgJsO0Xs8Ts4M1xZUQJQXJNsvmh3IV8DkNieCiy3tCwCUMq76-WpkrBtNAuEm&c=2000&e=-122.7732923187301&jsCallback=jsonpCache.iHAstfznwKIlokV&n=45.5058644057228&s=45.503142114175674&w=-122.77717657228884

We probably need (a) to poke Microsoft on getting or enabling our API keys for the newer API and (b) update all of the OSM applications to use their new API (iD, Rapid, JOSM).

As far as I can tell, we all use the same API key for MS StreetSide.

**Comment by bhousel** [comment]
> I think MS just killed the API we (OSM) were using for MS StreetSide.

Yeah thats what I think too 😭 
`GetBubbles` was always undocumented / unsupported, so I'm not totally surprised to see it go away.

**Comment by eneerhut** [comment]
I am having issues accessing Bing imagery. This seems to happen intermittently. Are we having trouble getting authenticated again and is it worth chasing this up with the MS team?

![image](https://github.com/facebook/Rapid/assets/11349863/ae603da9-dcaf-41ff-9d8e-ad7dbefe92c3)

**Comment by danieldegroot2** [comment]
Happens on regular iD too (and has done for a long time)
Below example happened only after uploading a changeset.

![image](https://github.com/facebook/Rapid/assets/67521919/dd428499-5624-44fe-b33a-da860d55c33b)
