### ISSUE TITLE
Highlight relation members no longer works

### ISSUE THREAD

**Issue by atiannicelli** [facebook/Rapid#939]
### Description

I really miss the feature where when you hover over a relation member in the left hand menu it would highlight that member on the map. I think that this probably changed when we went to the new version, but if I am looking at relations it is very difficult to tell what members are what on the map. The old highlight while mousing over the member was very helpful - any chance that could make a comeback?

### Version

2.0.3

### What browser are you seeing the problem on? What version are you running?

Chrome v112.0

### The OS you're using

mac

### Steps to reproduce

go to: https://mapwith.ai/rapid#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=r3436234&map=12.23/40.7084/69.5660

This is a relation with two members. Now mouse over the members on the left hand menu. The behavior used to be that the member that you are hovering over would highlight on the map. 

Now I think the only way I know how to determine what member is what on the map is to click it and go to that feature. Then I need to come back to the relation to see the next.

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=w256408217&map=12.23/40.7084/69.5660

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

**Comment by bhousel** [comment]
> The old highlight while mousing over the member was very helpful - any chance that could make a comeback?

Yes! I miss this feature too.. 
This is another of those things where the v1 code worked by selecting all the relation's pieces in the SVG surface and classing them with CSS to turn them blue.  We can't use CSS anymore to do stuff like this, but we do have a new way of picking things in the scene and classing them, so we can restore this feature.

**Comment by Bonkles** [comment]
Dum de dooooooo

https://github.com/facebook/Rapid/assets/1887955/a52471d1-2394-483c-9250-8f7e25c17e72

**Comment by atiannicelli** [comment]
Very cool! Thanks guys! This is great - I love being able to do this.

One small possible issue(?) is that the highlight takes a long time to show up and to unhighlight when looking at a relation. It isn't a huge deal, but not sure if it is just networking latency or something else.
To see what I mean go here: https://rapideditor.org/rapid/b1ab600-16.x-/index.html#background=EsriWorldImagery&id=r4129875&map=14.56/42.3595/-71.0903 
And then scroll ver the first way in that relation. If you mouse over it takes about 1 second to highlight and then when I mouse off it it takes at least a second for it to unhighlight.

**Comment by bhousel** [comment]
> To see what I mean go here: https://rapideditor.org/rapid/b1ab600-16.x-/index.html#background=EsriWorldImagery&id=r4129875&map=14.56/42.3595/-71.0903
> And then scroll ver the first way in that relation. If you mouse over it takes about 1 second to highlight and then when I mouse off it it takes at least a second for it to unhighlight.

Interesting - I did try this, but it was pretty snappy, but I _think_ that's because following the URL means that only that relation is loaded and nothing else.
![charles river relation](https://github.com/facebook/Rapid/assets/38784/d6b282d8-e370-436e-89d2-1ff39347ef3d)

I bet when you are trying it, it has all the Boston features displaying and the GPU is way overtaxed.

There are a lot of issues now related to lag when the scene gets too complex.  I'm going to spend some time in the next few months on making our renderer more efficient so it draws less stuff and/or performs better.

**Comment by atiannicelli** [comment]
Yup @bhousel - I talked to @Bonkles last night and he confirmed that I'm an idiot. I was loading an old build that he had provided me as an early release candidate. Once I cleared browser cache and actually loaded the released version (duh!) it works great!! Thanks again to both of you!
