### ISSUE TITLE
Lee County, FL Buildings overlay not displaying

### ISSUE THREAD

**Issue by toroxv** [facebook/Rapid#942]
### Description

Lee County, FL Buildings overlay not displaying when editing ive added the layer even cleared the cookies but still not working

### Version

2.0.3

### What browser are you seeing the problem on? What version are you running?

Chrome v113.0

### The OS you're using

win

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=Bing&datasets=b2c4457aeadc44208685a1ed2dcc101a&disable_features=boundaries&map=18.48/26.69142/-81.75095

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36

**Comment by Bonkles** [comment]
Just double checked this exact area, looks like the buildings are indeed working. Transient error / service outage on Esri's part? 

![image](https://github.com/facebook/Rapid/assets/1887955/fb73a2b4-1be2-415c-b26c-90daa2d9f1bc)
