### ISSUE TITLE
Custom map data should only show supported formats .gpx, .kml, .geojson, .json

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#945]
### Description

When you upload Custom map data, the emergent window shows all the files and formats in the folder, despite the extension. It should only display supported formats like .gpx, .kml, .geojson, .json, or others if there are.

### Version

2.0.3

### What browser are you seeing the problem on? What version are you running?

Chrome Version 105.0.5195.127 (Official Build) (64-bit)

### The OS you're using

Win10

### Steps to reproduce

Just try to upload any file in Custom Data

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=boundaries&map=18.08/-17.10519/-67.34126

**Comment by bhousel** [comment]
Good suggestion, thanks @jjiglesiasg 👍
