### ISSUE TITLE
Features are disappearing while editing

### ISSUE THREAD

**Issue by eneerhut** [facebook/Rapid#954]
### Description

Features I try to add to the map disappear while editing. While adding line segments and areas, the features seem to disappear after adding a few points to the map. I have [added a video here](https://drive.google.com/file/d/1sOGWxtvYQPu3gz50nNsZR5xeV5jOOn-D/view?usp=share_link) showing the issue.

### Version

2.0.0-beta.2

### What browser are you seeing the problem on? What version are you running?

Chrome Version 114.0.5735.106 (Official Build) (arm64)

### The OS you're using

Ventura 13.4

### Steps to reproduce

Visited [rapid](https://mapwith.ai/rapid-v2-beta). Started adding a continuous line to trace sidewalk over satellite imagery. The line segment seems to disappear after a few points have been added to the map.

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-beta#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=20.84/37.56314/-122.25829

**Comment by Bonkles** [comment]
@eneerhut can you retry this using the latest stable rapid v2? It's up at https://rapideditor.org/edit

**Comment by Bonkles** [comment]
whew. Very glad to hear it. :)
