### ISSUE TITLE
Mapillary Image type filtering is not working

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#955]
### Description

This one came to us by way of Mapillary, from Said Turksever. 

**Actual behaviour:** 

- Enable Mapillary imagery layer
- Mapillary imagery layer will be available both flat and panoramic imagery
- Enable only flat or panoramic imagery
- Mapillary Imagery will not be filtered on the map view 

**Expected behaviour** 

- Enable Mapillary imagery layer
- Mapillary imagery layer will be available both flat and panoramic imagery
- Enable only flat or panoramic imagery
- Mapillary Imagery needs to be filtered based on enabled selection based on imagery type

### Version

2.0.1

### What browser are you seeing the problem on? What version are you running?

All

### The OS you're using

MacOS

### Steps to reproduce

See description!

### The browser URL at the time you encountered the bug

n/a

**Comment by tordans** [comment]
@Bonkles I think this should be reopened.

In v2.1 I see that the filter does filter the image circles, but it does not hide the image-lines.

Example: https://rapideditor.org/edit#background=Berlin-2022&data=https://atlas-tiles.s3.eu-central-1.amazonaws.com/berlin-parking-polygons-euvm.pmtiles&datasets=fbRoads,msBuildings&disable_features=boundaries&map=19.21/52.49931/13.34098&photo=mapillary/1003782916887121&photo_overlay=mapillary

FYI, the date filter hides both, the line and the circle.

<img width="935" alt="image" src="https://github.com/facebook/Rapid/assets/111561/e35af2c8-5079-41df-861c-2b6dc78a02cc">

**Comment by Bonkles** [comment]
Fixed the filtering so that the tracks are also hidden on click for pano/flat. 

Uploading mapillary_tracks_hide.mov…

**Comment by Bonkles** [comment]
This should be fixed in 2.1.1.
