### ISSUE TITLE
Create changeset tag if user submits changes in 'Poweruser' mode.

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#964]
### Description

As developers, we'd like to keep an eye on how widespread poweruser feature use is.

**Comment by jjiglesiasg** [comment]
What is a Poweruser, if I may inquire?

**Comment by bhousel** [comment]
> What is a Poweruser, if I may inquire?

Adding `&poweruser=true` to the url will allow the user access to some preview datasets for testing, skip the limit on number of features that can be added, make large edits that extend beyond the visible map, a few other feature flags that we test sometimes.
