### ISSUE TITLE
Bring mapwith.ai offline

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#969]
The mapwith.ai site is going to be retired, so we should do the following: 

- [x] Implement redirects from mapwith.ai->rapideditor.org for all requests EXCEPT to the backend ml_roads service
- [x] ensure that the ml_roads service is still reachable post-redirect
- [x] Keep an eye on traffic from HOT etc to make sure we didn't cut off the service
- [x] debug infra so that calls from rapideditor.org/ml_roads successfully redirects to the same backend endpoint as mapwith.ai/ml_roads

**Comment by jjiglesiasg** [comment]
I opened straight rapieditor.org without any problem. When mapwith.ai will be retired?

**Comment by Bonkles** [comment]
Update: found the issue with forwarding requests from rapideditor.org/maps/ml_roads to the facebook.com origin- the query string parameters weren't being cached, and thus they were not being forwarded onto the facebook servers.  Hence, we couldn't auth or anything close to it. 

After enabling the query strings cache in the Cloudfront behavior for maps/ml_roads, things are working on my local system running a modified rapid instance (which points the Roads service to rapideditor.org).
