### ISSUE TITLE
Maxar Premium Imagery is no longer working

### ISSUE THREAD

**Issue by Bonkles** [facebook/Rapid#970]
### Description

Since three/four weeks ago the Maxar Premium layer has stopped working in multiple editors- i.e. the endpoint has simply come down and is nonresponsive. Trying to investigate the cause. 

Update: 

There are several other reports of same. It looks like this started happening at or around June 1st 2023. 

https://community.openstreetmap.org/t/maxar-imagery-not-working-was-maxar-is-blurred-in-id-and-other-similar-topics/100524/14

https://github.com/hotosm/tasking-manager/issues/4846

Here's the original blog post announcing the sat imagery launch for OSM six years ago in May of 2017: 
https://blog.maxar.com/earth-intelligence/2017/digitalglobe-satellite-imagery-launch-for-openstreetmap

### Version

any/all (iD, JOSM seeing it too)

### What browser are you seeing the problem on? What version are you running?

all

### The OS you're using

n/a

### Steps to reproduce

Simply use Maxar Premium and observe the lack of imagery. :) 

### The browser URL at the time you encountered the bug

n/a

**Comment by Bonkles** [comment]
After looking around this seems to be a larger time break that previous times when the Maxar keys have been rotated. Suspect that this endpoint is gone for good. Others have filed issues with Maxar and not heard back.

**Comment by Bonkles** [comment]
HOT has heard from one of their contacts at Maxar, waiting to hear anything further.

**Comment by jjiglesiasg** [comment]
So Maxar imagery is history. Mapbox and Esri is what remains fairly updated in several places of the World
