### ISSUE TITLE
A line could in Rapid, but Should NOT be depicted as a single node

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#971]
### Description

If you start to draw a line and you quit drawing such line, it remains as a DOT (Node), once you do that you could NOT delete such node until you continue the line and add more nodes. In ID a line is composed by at least 2 Nodes interconnected.

### Version

2.0.3

### What browser are you seeing the problem on? What version are you running?

Version 114.0.5735.199 (Official Build) (64-bit)

### Steps to reproduce

Just draw a line with a single node, and then try to delete such node.

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=Bing&datasets=fbRoads,msBuildings&map=17.56/-20.01212/-68.28700

**Comment by Bonkles** [comment]
@jjiglesiasg it looks like you're talking about a case where no node should be left on the map, yet one is displayed.  

Is this what you are talking about? 


https://github.com/facebook/Rapid/assets/1887955/6158d41e-9105-4240-97e4-8b4c404b3724


[Above: video showing a user clicking 'line', then drawing the first point, then clicking on that point again. The point remains on the map even though this is a degenerate case of a polygon or line.]


One workaround until we get a fix out for this: hitting 'undo' seems to correctly back the node out of the map.

**Comment by Bonkles** [comment]
https://github.com/facebook/Rapid/assets/1887955/ab8d2b99-6973-4cd7-a6f8-3742f66a4830

Above: video showing me clicking 'draw line', then clicking to make a new node, then clicking that same node to 'finish' the degenerate drawing gesture. The node is appropriately removed from the map, just like it used to be.

**Comment by jjiglesiasg** [comment]
Great, Thanks
