### ISSUE TITLE
Restoring unsaved changes breaks mapping pane

### ISSUE THREAD

**Issue by atiannicelli** [facebook/Rapid#974]
### Description

When I load rapid with unsaved changes and I request to restore them everything seems to do the right thing, but the mapping pane goes blank. And nothing I do seems to bring it back.

### Version

2.0.3

### What browser are you seeing the problem on? What version are you running?

Chrome v114.0

### The OS you're using

mac

### Steps to reproduce

I edited the kissimmee river relation. 
I then closed my browser without saving the changes. 
I then opened up rapid and the window to alert me that I have unsaved changes pops up.
I choose "restore my changes"
The map screen goes blank and I can't get it back.

https://github.com/facebook/Rapid/assets/5851115/f29125c5-3615-46cf-963e-6ae02818467b

### The browser URL at the time you encountered the bug

https://rapideditor.org/rapid#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&id=r1240554&map=6.00/43.626/-86.407

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

**Comment by bhousel** [comment]
I remember this was definitely broken, and I vaguely remember fixing it, but I don't remember specifically when I fixed it.

**Comment by atiannicelli** [comment]
Works great now!
