### ISSUE TITLE
Note inspector header icon is messed up

### ISSUE THREAD

**Issue by bhousel** [facebook/Rapid#987]
## Currently messed up:

<img width="390" alt="Screenshot 2023-07-21 at 10 56 00 AM" src="https://github.com/facebook/Rapid/assets/38784/e99e4a86-8e69-4644-aa97-66fa9491d128">

## Should look like this:

<img width="379" alt="Screenshot 2023-07-21 at 11 01 04 AM" src="https://github.com/facebook/Rapid/assets/38784/a148b0ae-e00a-4917-bd24-ffab65323ccb">

**Comment by tordans** [comment]
The arrows icons that indicate that a block closed/open in the side panel are also missing 
<img width="405" alt="image" src="https://github.com/facebook/Rapid/assets/111561/1f1e212c-8c7c-42ff-9c56-9a2850f7648b">

The HTML looks empty
<img width="498" alt="image" src="https://github.com/facebook/Rapid/assets/111561/07335a16-7f75-412c-8d01-646cf6297cd8">

**Comment by bhousel** [comment]
> The arrows icons that indicate that a block closed/open in the side panel are also missing

oh yea - I fixed these hide/show icons a while ago, but didn't have an issue for it..
Bug Introduced in 05f2f3446
Fixed in  daec2bcd

**Comment by Bonkles** [comment]
![image](https://github.com/facebook/Rapid/assets/1887955/8a47bd15-cc0f-4b7b-9bc8-d1ef38157407)
Fixed! Now the icons in both the sidebar and on the main field should show up correctly.
