### ISSUE TITLE
Nepal: 

### ISSUE THREAD

**Issue by geowOSM** [facebook/RapiD#99]
I noticed for example in Nepal that Facebook’s AI wrongly classifies quite a few streams and ravines as suggestions for „Roads”. It appears that only optical pattern recognition is used and no DEM for plausibility checks, see e.g. https://mapwith.ai/rapid#background=fb-mapwithai-maxar&disable_features=boundaries&map=16.60/29.39309/82.93539

In hilly and mountainous areas, waterways run more or less perpendicular to the gradient, whereas roads and paths are more or less oblique to the slope. Therefore the distinction should be much easier when using an elevation model. Is this intended or planned for the future?

Thanks for providing this service!

**Comment by jeffdefacto** [comment]
Currently, it is just using satellite, but the idea of using DEMs to sanity check it is intriguing.

Thanks for the suggestion!
