### ISSUE TITLE
Google Buildings data set

### ISSUE THREAD

**Issue by jjiglesiasg** [facebook/Rapid#990]
### What kind of data are you inquiring about?

Buildings as released by Google

### Background / where to download this data

As per the OSM 678 Weekly publication: 
The [RapiD](https://wiki.openstreetmap.org/wiki/Rapid) editor has allowed users to trace from Google’s [Open Buildings layer](https://sites.research.google/open-buildings/) since [2022](https://github.com/facebook/Rapid/issues/479#issuecomment-1156400591). Recent changes have made more data available and the licence is now compatible with OSM. Particularly useful is that this dataset includes a [precision threshold](https://github.com/facebook/Rapid/issues/479#issue-1272114720), which should help mappers avoid false positives (which have been a problem with the default Microsoft Buildings layer).

Where this data could be seen in RapID?

**Comment by bhousel** [comment]
It's not available in Rapid yet - I'm not sure why Weekly OSM wrote that.

As far as I know, the only mention of this dataset has been on this issue: https://github.com/facebookmicrosites/Open-Mapping-At-Facebook/issues/29 and our response is just that "it can be added and we are looking in to it".

**Comment by jjiglesiasg** [comment]
Agree, was a surprise to me as well, That's why I raise the issue. To learn more about. Thanks Bryan

**Comment by Bonkles** [comment]
Update- spoke with our partners at Esri about this dataset today and the current Plan of Record is that they will do some QA on the buildings, which will take a bit of time. Then the dataset will replace the existing 'Africa Buildings' dataset and simply become 'Google Buildings' in the rapid data catalog. No ETA on this, but it is in process.

**Comment by Bonkles** [comment]
Also as a point of note- the Africa buildings dataset contained the same accuracy threshold- the data hosted by ESRI only contains the top 10% of shapes by accuracy. We'll likely take the same approach when ingesting this data too.

**Comment by MG-LSJ** [comment]
> Update- spoke with our partners at Esri about this dataset today and the current Plan of Record is that they will do some QA on the buildings, which will take a bit of time. Then the dataset will replace the existing 'Africa Buildings' dataset and simply become 'Google Buildings' in the rapid data catalog. No ETA on this, but it is in process.

Is there any update on the progress?

**Comment by Bonkles** [comment]
Nothing yet- The QA process takes some time! We have been raising this periodically in our sync meetings, I will again this Thursday.

**Comment by bhousel** [comment]
Good news, the Google Buildings will start to become available now, following #1300, #1309  , and released now in [v2.2.5](https://github.com/facebook/Rapid/blob/main/CHANGELOG.md#225)  🎉  

They will be available as per-country datasets through the Esri integration.
They are starting to become available now as "preview" datasets (users who opt into poweruser mode can enable them), and will be available as regular datasets available to everyone once they've been tested a bit more.

<img width="974" alt="Screenshot 2024-02-12 at 12 40 13 PM" src="https://github.com/facebook/Rapid/assets/38784/0897a6e6-3b07-4ff0-a772-2d29eca73aa5">
