### ISSUE TITLE
Can't save changes, comment section disappears

### ISSUE THREAD

**Issue by gyCfjSnO** [facebook/Rapid#997]
### Description

When trying to save changes the changeset comment section disappears as soon as you move your cursor off the save button.

Issue still persists after `Shift + F5 (Reload the current tab, ignoring cached content)` & `Ctrl + Shift + R (Reload the current page, ignoring cached content)`.

### Version

2.0.3

### What browser are you seeing the problem on? What version are you running?

Microsoft Edge Version 115.0.1901.188 (Official build) (64-bit)

### The OS you're using

Windows 11 Pro 22H2 22621.2070 Windows Feature Experience Pack 1000.22659.1000.0

### The browser URL at the time you encountered the bug

https://rapideditor.org/edit#background=EsriWorldImagery&datasets=fbRoads,msBuildings&disable_features=boundaries&map=18.08/-27.32871/152.98828

### The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.188

**Comment by Bonkles** [comment]
Does this occur before or after committing the changes?

**Comment by gyCfjSnO** [comment]
> Does this occur before or after committing the changes?

Before, unable to commit the changes because the text box to put in the comment disappears. Closing the tab and opening a new Rapid Editor tab sometimes resolves the issues on first go.

**Comment by Bonkles** [comment]
I hadn't ever seen this myself, and was ready to close as not reproducible- then I saw you were on windows and was able to repro this near instantly. I'll dig in... thanks VERY much for this report!!!

**Comment by Bonkles** [comment]
@gyCfjSnO Can you please confirm whether or not you had previous clicked the 'Show My Location' Button in the sidebar? I can't tell from the awesome video you captured, as it appears that the right hand side of the screen isn't shown. 

I can seem to get this to happen every time if I leave the location button clicked, like so: 

![image](https://github.com/facebook/Rapid/assets/1887955/3d59ccce-7468-46a0-a2ab-bcd6e1d912dc)

**Comment by gyCfjSnO** [comment]
@Bonkles issue seems to occur when Show My Location is enabled.

**Comment by Bonkles** [comment]
Absolutely excellent- 2.1 will fix this issue for good. Glad to hear it! Closing this one.
